OpenAssetIO/OpenAssetIO

.github/workflows/commit-checks.yml
=> [CI] Check DCO in commit messages on PR

python/openassetio/Specification.py, python/openassetio/_core/audit.py, python/openassetio/exceptions.py, python/openassetio/hostAPI/HostInterface.py, python/openassetio/hostAPI/Manager.py, python/openassetio/hostAPI/ManagerFactoryInterface.py, python/openassetio/hostAPI/Session.py, python/openassetio/hostAPI/terminology.py, python/openassetio/managerAPI/ManagerInterface.py, python/openassetio/pluginSystem/PluginSystemManagerFactory.py
=> [Docs] Fix Doxygen build warnings

python/openassetio/pluginSystem/PluginSystem.py, python/openassetio/pluginSystem/PluginSystemManagerFactory.py, tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
Some minor tweaks to the `PluginSystem` so that it works better in Python 3. Adds test coverage to verify fixes.
=> [PluginSystem] Python 3 fixes

python/openassetio/hostAPI/HostInterface.py, python/openassetio/managerAPI/Host.py
=> The great `pylint` cleanup - Part VII - `Host`/`HostInterface`

python/openassetio/exceptions.py, python/openassetio/hostAPI/Session.py, tests/openassetio/hostAPI/test_session.py
Noticed whilst addressing the documentation omissions caught by #101. Minor improvements to the exception hierarchy.
=> [Core] Improve exception class hierarchy

python/openassetio/constants.py, python/openassetio/hostAPI/Manager.py, python/openassetio/hostAPI/ManagerFactoryInterface.py, python/openassetio/hostAPI/Session.py, python/openassetio/hostAPI/terminology.py, python/openassetio/hostAPI/transactions.py, python/openassetio/pluginSystem/ManagerPlugin.py
Sundry fixes in the name of #101.
=> The great `pylint` cleanup - Part VIII - sundry fixes

python/openassetio/SpecificationFactory.py, python/openassetio/exceptions.py, python/openassetio/pluginSystem/PluginSystemManagerFactory.py
More for #101. Mostly things that aren't in #152 #151 as I got sidetracked by The Bigger Issues™.
=> The great `pylint` cleanup - Part IX - other sundry fixes

.github/workflows/test.yml
=> [CI] Ensure doc build errors fail checks

.github/workflows/code-quality.yml, .github/workflows/docs.yml, .github/workflows/test.yml, CONTRIBUTING.md, doc/CHANGES.md, doc/Dockerfile, doc/Makefile, doc/README.md, doc/package-lock.json, python/openassetio/Specification.py, python/openassetio/SpecificationFactory.py, python/openassetio/_core/objects.py, python/openassetio/hostAPI/ManagerFactoryInterface.py, python/openassetio/logging.py, python/openassetio/pluginSystem/ManagerPlugin.py, python/openassetio/pluginSystem/PluginSystem.py, python/openassetio/pluginSystem/PluginSystemManagerFactory.py, python/openassetio/pluginSystem/PluginSystemPlugin.py, python/openassetio/pluginSystem/__init__.py, tests/openassetio/pluginSystem/resources/README.md, tests/openassetio/pluginSystem/resources/pathA/modulePlugin.py, tests/openassetio/pluginSystem/resources/pathB/packagedPlugin/PackagePlugin.py, tests/openassetio/pluginSystem/resources/pathB/packagedPlugin/__init__.py, tests/openassetio/pluginSystem/resources/pathC/modulePlugin.py, tests/openassetio/pluginSystem/resources/symlinkPath/modulePlugin.py, tests/openassetio/pluginSystem/resources/symlinkPath/packagedPlugin, tests/openassetio/pluginSystem/test_pluginsystem.py, tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py, tests/openassetio/test_logging.py, tests/openassetio/test_specification.py
Some merge conflicts, see final commit, otherwise all commits come from `main`.
=> Merge main into feature/101-pylint

python/openassetio/test/managerValidator/__main__.py, tests/openassetio/test/managerValidator/resources/fixtures_fail.py, tests/openassetio/test/managerValidator/resources/fixtures_pass.py, tests/openassetio/test/managerValidator/resources/plugins/StubManager.py, tests/openassetio/test/managerValidator/test_main.py
=> Fix `managerValidator` exit code when invoked via the CLI

CONTRIBUTING.md, README.md, contributing/CODE_REVIEWS.md, contributing/CODING_STANDARDS.md, contributing/COMMITS.md, contributing/PROCESS.md, contributing/PULL_REQUESTS.md
Covers the fundamentals of how development work is conducted on the project, in preparation for new contributors. Hopefully this captures our existing way of working.
=> [Docs] Add development process guides

contributing/PROCESS.md
=> [Docs] Fix links in `PROCESS.md`

doc/src/MainPage.dox
Signed-off-by: Raihan Kibria <raihan.kibria@foundry.com>
=> [Docs] Fix wording: through not thorough

decisions/DR005-String-encoding.md
We ran this by a variety of people in the wider software development community, and support for this was unanimous.
=> [Docs] Add string encoding decision record

resources/examples/manager/BasicAssetLibrary/README.md, resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/bal.py, resources/examples/manager/BasicAssetLibrary/tests/fixtures.py
Some minor gremlins that snuck through #239
=> Misc BAL fixes

.github/workflows/test.yml, cmake/ThirdParty.cmake, resources/build/bootstrap-windows-2019.bat, src/openassetio-core/CMakeLists.txt, src/openassetio-python/CMakeLists.txt
- Installing the test Python environment works
=> [Build] Re-instate Windows tests

CMakeLists.txt, resources/perftest/CMakeLists.txt, resources/perftest/README.md, resources/perftest/perftest.cpp
Standalone 'perftest' executable for testing performance.
Closes #260
=> [Core] Core API performance test harness

doc/Doxyfile, doc/Makefile, doc/src/ForManagers.dox, doc/src/Testing.dox, python/openassetio/managerAPI/ManagerInterface.py, resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py, resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/__init__.py, resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py, resources/examples/manager/SampleAssetManager/python/SampleAssetManager/__init__.py, src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp, src/openassetio-core/include/openassetio/trait/property.hpp, src/openassetio-core/include/openassetio/typedefs.hpp, src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp, tests/openassetio/managerAPI/test_managerinterface.py, tests/openassetio/test/manager/resources/plugins/StubManager.py
=> [Core] Migrate `ManagerInterface` `identifier` and `displayName` to C++

decisions/DR008-Unify-the-entity-data-model.md
Performance investigations and feedback from the working group ratified this decision.
=> [Docs] Update status of DR008 to decided

resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
A couple of minor fixes for BAL test python that slipped through the cracks.
=> [Examples] BAL test assert fixes

resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
Turns out the "other" misc fix in #322 is only meaningful over here! Doh.
=> [Examples] Fix unused import in BAL tests

README.md, contributing/USER_PERSONAS.md, decisions/DR007-Hierarchical-or-compositional-traits-for-specifications.md, decisions/DR008-Unify-the-entity-data-model.md, resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
Just one minor conflict in `bal_business_logic_suite.py`.
=> Merge `main` into `feature/181-coreCppBuild`

src/openassetio-core-c/include/openassetio/c/StringView.h, src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h, src/openassetio-core-c/private/StringView.hpp, src/openassetio-core-c/private/errors.hpp, src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp, tests/openassetio-core-c/CMakeLists.txt, tests/openassetio-core-c/private/StringViewReporting.hpp, tests/openassetio-core-c/private/StringViewTest.cpp, tests/openassetio-core-c/private/errorsTest.cpp, tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
Part of #290. 
* Rename `SimpleString` to `StringView`
* Add a `ConstStringView` 
* Add a couple of utilities for writing into `StringView`s 
* Add some test coverage.
=> [Core] StringView C API

src/openassetio-core-c/include/openassetio/c/InfoDictionary.h, src/openassetio-core-c/private/InfoDictionary.cpp, tests/openassetio-core-c/private/InfoDictionaryTest.cpp
Part of #290.
This adds a C API "constructor" as well as mutator functions for inserting/updating values in the `InfoDictionary`.
=> [Core] C API InfoDictionary upsert

doc/src/MainPage.dox
... might as well call a spade a spade.
=> [Docs] Improve main UML Class diagram wording

.github/workflows/test.yml, README.md, contributing/CHANGES.md, contributing/PROCESS.md, decisions/DR001-Python-code-style.md, decisions/DR002-Getter-method-naming.md, decisions/DR003-ManagerInterface-method-naming.md, decisions/DR008-Unify-the-entity-data-model.md, doc/Makefile, doc/README.md, doc/src/ForManagers.dox, doc/src/MainPage.dox, python/openassetio/__init__.py, resources/examples/manager/BasicAssetLibrary/schema.json, resources/examples/manager/BasicAssetLibrary/tests/resources/library_apiComplianceSuite.json, resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py, resources/examples/manager/SampleAssetManager/python/SampleAssetManager/__init__.py
Covers links in documentation, as well as the Doxygen docker container package build steps.
=> Update GitHub org references

.github/workflows/test.yml, BUILDING.md, cmake/ThirdParty.cmake, resources/build/bootstrap-macos-10.15.sh
Closes #376
We disable sanitizers for now as we need more `asan` trickery and `ubsan` highlighted something either potentially interesting or a false positive. Added #381 to track this.
=> [CI] Enable macOS in test matrix

CMakeLists.txt, RELEASE_NOTES.md, contributing/COMMITS.md, setup.py, src/openassetio-python/CMakeLists.txt
=> Initial alpha release

CMakeLists.txt, src/openassetio-python/CMakeLists.txt
=> [Build] Better `clean`ing

RELEASE_NOTES.md
Add missing release notes for PR #394
=> [Docs] Update release notes with `clean` fixes

.github/workflows/code-quality.yml, .github/workflows/test.yml, RELEASE_NOTES.md, resources/build/Vagrantfile, resources/build/bootstrap-macos-10.15.sh, resources/build/bootstrap-ubuntu-20.04.sh, resources/build/bootstrap-windows-2019.bat, resources/build/requirements.txt
=> Refactor bootstrap scripts and bump conan version to `1.48.1`

.github/workflows/code-quality.yml, .github/workflows/test.yml, BUILDING.md, CMakePresets.json, RELEASE_NOTES.md
=> Add CMake presets

README.md
A few small changes to make this a little more current.
=> `README.md` updates

RELEASE_NOTES.md, doc/src/Examples.dox, python/openassetio/SpecificationBase.py, python/openassetio/hostAPI/Manager.py, python/openassetio/test/manager/apiComplianceSuite.py, python/openassetio/test/manager/specifications.py, python/openassetio/test/specifications.py, resources/perftest/perftest.cpp, src/openassetio-core/TraitsData.cpp, src/openassetio-core/include/openassetio/TraitsData.hpp, src/openassetio-python/TraitsDataBinding.cpp, tests/python/openassetio/test/manager/resources/suite_executeSuiteTests.py, tests/python/openassetio/test_specificationbase.py, tests/python/openassetio/test_trait.py, tests/python/openassetio/test_traitsdata.py
Im sure I've missed something somewhere........
=> Rename traits-related methods/vars to "traitSet"

CMakePresets.json, resources/perftest/perftest.cpp
Ensures perftest gets built as part of test runs.
=> Enable `OPENASSETIO_BUILD_PERFTEST` for all-targets builds

.github/workflows/code-quality.yml, CMakeLists.txt, CMakePresets.json, RELEASE_NOTES.md, resources/build/bootstrap-ubuntu-20.04.sh
Signed-off-by: Tom Cowland <tom@foundry.com>
=> [Build] Update bootstrap script to use clang-tidy-12

RELEASE_NOTES.md, python/openassetio/managerAPI/HostSession.py, src/openassetio-core/CMakeLists.txt, src/openassetio-core/include/openassetio/managerAPI/Host.hpp, src/openassetio-core/include/openassetio/managerAPI/HostSession.hpp, src/openassetio-core/managerAPI/HostSession.cpp, src/openassetio-python/CMakeLists.txt, src/openassetio-python/_openassetio.cpp, src/openassetio-python/_openassetio.hpp, src/openassetio-python/managerAPI/HostBinding.cpp, src/openassetio-python/managerAPI/HostSessionBinding.cpp, tests/python/openassetio/managerAPI/test_hostsession.py
=> Add HostSession to C++

RELEASE_NOTES.md, doc/src/Examples.dox, doc/src/ManagerState.dox, python/openassetio/Context.py, python/openassetio/hostAPI/Manager.py, python/openassetio/hostAPI/Session.py, python/openassetio/managerAPI/ManagerInterface.py, python/openassetio/test/manager/harness.py, src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp, tests/python/openassetio/hostAPI/test_manager.py, tests/python/openassetio/hostAPI/test_session.py
=> Move Context management functions to `Manager`

RELEASE_NOTES.md, python/openassetio/managerAPI/__init__.py, src/openassetio-core/include/openassetio/managerAPI/ManagerStateBase.hpp, src/openassetio-python/CMakeLists.txt, src/openassetio-python/_openassetio.cpp, src/openassetio-python/_openassetio.hpp, src/openassetio-python/managerAPI/ManagerStateBaseBinding.cpp, tests/openassetio-core/CMakeLists.txt, tests/openassetio-core/managerAPI/ManagerStateBaseTest.cpp, tests/python/openassetio/managerAPI/test_managestatebase.py
=> [Core] Add `ManagerStateBase` class

contributing/CODING_STANDARDS.md, contributing/CODING_STYLE.md, contributing/PROCESS.md, src/openassetio-core-c/private/handles/hostAPI/Manager.hpp, src/openassetio-core-c/private/hostAPI/Manager.cpp, src/openassetio-core/include/openassetio/hostAPI/Manager.hpp, src/openassetio-core/include/openassetio/managerAPI/HostSession.hpp, src/openassetio-python/hostAPI/ManagerBinding.cpp, src/openassetio-python/managerAPI/HostSessionBinding.cpp, tests/openassetio-core-c/private/hostAPI/ManagerTest.cpp
Closes #433.
It will most certainly pay to check my C/Cpp with a fine toothed comb 😉.
=> Use shared ptrs for Python/C bindings

decisions/DR010-TraitsData-value-retrieval-API.md
=> [Docs] Document TraitsData value retrieval API decision

RELEASE_NOTES.md, doc/src/Examples.dox, doc/src/ForHosts.dox, doc/src/ForManagers.dox, doc/src/Glossary.dox, doc/src/Thumbnails.dox, python/openassetio/hostApi/Manager.py, python/openassetio/managerApi/ManagerInterface.py, python/openassetio/test/manager/apiComplianceSuite.py, python/openassetio/traits/managementPolicy.py, src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.cpp, src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.hpp, src/openassetio-core/TraitsData.cpp, src/openassetio-core/hostApi/Manager.cpp, src/openassetio-core/include/openassetio/TraitsData.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/include/openassetio/trait/collection.hpp, src/openassetio-python/TraitsDataBinding.cpp, src/openassetio-python/hostApi/ManagerBinding.cpp, src/openassetio-python/managerApi/ManagerInterfaceBinding.cpp, tests/openassetio-core-c/private/hostApi/ManagerTest.cpp, tests/openassetio-core/TraitsDataTest.cpp, tests/python/openassetio/hostApi/test_manager.py
=> [Core] Migrate managementPolicy to C++

RELEASE_NOTES.md, python/openassetio/hostApi/Manager.py, python/openassetio/hostApi/Session.py, python/openassetio/managerApi/ManagerInterface.py, python/openassetio/test/manager/apiComplianceSuite.py, resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py, resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/bal.py, resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py, resources/examples/manager/BasicAssetLibrary/tests/fixtures.py, resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py, src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.cpp, src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.hpp, src/openassetio-core/hostApi/Manager.cpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/managerApi/ManagerInterface.cpp, src/openassetio-python/hostApi/ManagerBinding.cpp, src/openassetio-python/managerApi/ManagerInterfaceBinding.cpp, tests/openassetio-core-c/private/hostApi/ManagerTest.cpp, tests/python/conftest.py, tests/python/openassetio/hostApi/test_manager.py, tests/python/openassetio/hostApi/test_session.py, tests/python/openassetio/test/manager/resources/plugins/StubManager.py, tests/python/openassetio/test/manager/resources/suite_executeSuiteTests.py
=> [Core] Rework ManagerInterface initialization

RELEASE_NOTES.md
Add missing release notes for #504.
=> [Docs] Add missing release notes

RELEASE_NOTES.md, python/openassetio/hostApi/ManagerInterfaceFactoryInterface.py, src/openassetio-core/CMakeLists.txt, src/openassetio-core/hostApi/ManagerInterfaceFactoryInterface.cpp, src/openassetio-core/include/openassetio/hostApi/ManagerInterfaceFactoryInterface.hpp, src/openassetio-python/CMakeLists.txt, src/openassetio-python/_openassetio.cpp, src/openassetio-python/_openassetio.hpp, src/openassetio-python/hostApi/ManagerInterfaceFactoryInterfaceBinding.cpp, tests/python/conftest.py, tests/python/openassetio/hostApi/test_managerinterfacefactoryinterface.py, tests/python/openassetio/hostApi/test_session.py, tests/python/openassetio/managerApi/test_hostsession.py, tests/python/openassetio/pluginSystem/test_pluginsystemmanagerinterfacefactory.py, tests/python/openassetio/test/manager/conftest.py, tests/python/openassetio/test_log.py
=> [Core] Migrate `ManagerInterfaceFactoryInterface` to C++

RELEASE_NOTES.md, python/openassetio/hostApi/ManagerFactory.py, python/openassetio/hostApi/__init__.py, src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.cpp, src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.hpp, src/openassetio-core/CMakeLists.txt, src/openassetio-core/hostApi/Manager.cpp, src/openassetio-core/hostApi/ManagerFactory.cpp, src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerInterfaceFactoryInterface.hpp, src/openassetio-core/include/openassetio/managerApi/Host.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/include/openassetio/typedefs.hpp, src/openassetio-core/managerApi/Host.cpp, src/openassetio-python/CMakeLists.txt, src/openassetio-python/_openassetio.cpp, src/openassetio-python/_openassetio.hpp, src/openassetio-python/hostApi/HostInterfaceBinding.cpp, src/openassetio-python/hostApi/ManagerFactoryBinding.cpp, src/openassetio-python/hostApi/ManagerInterfaceFactoryInterfaceBinding.cpp, src/openassetio-python/managerApi/ManagerInterfaceBinding.cpp, tests/openassetio-core-c/private/hostApi/ManagerTest.cpp, tests/python/conftest.py, tests/python/openassetio/hostApi/test_managerfactory.py, tests/python/openassetio/test_imports.py
=> [Core] Add ManagerFactory

tests/python/openassetio/test_imports.py
Accidentally omitted during recent additions/changes.
Closes #526
=> [Tests] Add missing Python import checks

RELEASE_NOTES.md
=> [Docs] Add `openassetio-codegen` `RELEASE_NOTES.md`

RELEASE_NOTES.md, python/openassetio/__init__.py, src/openassetio-core/include/openassetio/EntityReference.hpp, src/openassetio-python/module/CMakeLists.txt, src/openassetio-python/module/EntityReferenceBinding.cpp, src/openassetio-python/module/_openassetio.cpp, src/openassetio-python/module/_openassetio.hpp, tests/python/openassetio/test_entityreference.py, tests/python/openassetio/test_imports.py
=> Add `EntityReference` type

README.md
Attempts to add more "why" not "what" to the introductory section in the readme. Formatted view [here](https://github.com/OpenAssetIO/OpenAssetIO/pull/559/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
@mrjoshuak - this any better?
Part of #550.
=> [Docs] Frame `README.md` in terms of the problem 

README.md
Doh! This slipped through the net in #559.
=> [Docs] Fix `README.md` heading case

resources/build/requirements.txt
More and more recipes are making use of recent Conan API features - see https://github.com/OpenAssetIO/OpenAssetIO/runs/8087713477?check_suite_focus=true#step:6:177
We also need to sort out a lockfile for recipe versions.
=> [CI] Update Conan version to 1.51.3

LICENSE, doc/src/Examples.dox, doc/src/ForHosts.dox, doc/src/Glossary.dox, python/openassetio/hostApi/ManagerFactory.py, src/openassetio-core/CMakeLists.txt, src/openassetio-core/hostApi/Manager.cpp, src/openassetio-core/hostApi/ManagerFactory.cpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp, src/openassetio-python/module/hostApi/ManagerBinding.cpp, src/openassetio-python/module/hostApi/ManagerFactoryBinding.cpp, tests/python/openassetio/hostApi/resources/default_manager.toml, tests/python/openassetio/hostApi/test_managerfactory.py, thirdparty/tomlplusplus/LICENSE, thirdparty/tomlplusplus/include/toml.hpp
Closes #494, with a more modern interpretation of the problem :) The commit notes hopefully explain the design choices.
~Draft PR as we need to work out how to get the TOML dependency into the ASWF container for the one-liner builds.~
=> Default manager config mechanism

.github/workflows/build-instructions.yml, .github/workflows/code-quality.yml, .github/workflows/test.yml, CMakeLists.txt, README.md, cmake/ThirdParty.cmake, contributing/CODING_STANDARDS.md, src/openassetio-python/module/CMakeLists.txt, tests/CMakeLists.txt, tests/openassetio-core-c/CMakeLists.txt, tests/openassetio-core/CMakeLists.txt, tests/openassetio-python/CMakeLists.txt
=> Support `ctest --parallel`

contributing/CODE_REVIEWS.md
=> [Docs] Update `CODE_REVIEWS.md` to cover release notes check

RELEASE_NOTES.md, src/openassetio-core/include/openassetio/TraitsData.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp, src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
=> Nodiscard attribute on factory make methods

contributing/USER_PERSONAS.md
Reflects our current usage when discussing features/etc.
=> [Docs] Clarify terminology in `USER_PERSONAS.md`

.github/workflows/build-instructions.yml, .github/workflows/test.yml
Upstream pybind issue fixed.
Closes #476
=> [CI] Re-enable macOS CI runs

RELEASE_NOTES.md, pyproject.toml, resources/codegen/setup.py
=> [Release] Bump version to 1.0.0-alpha.5

pyproject.toml
Closes #688 
The indentation was causing the markdown formatting not to be appplied correctly.
test upload : https://test.pypi.org/project/openassetio/
=> [Docs] Correctly indent PyPI docs.

BUILDING.md, README.md
Minimally update README/BUILDING docs to be appropriate for releasing wheels.
This is not the full documentation update, just a quick edit to make the docs make sense.
co-authored by @foundrytom
=> [Docs] Update README/BUILDING for Release

decisions/DR013-Project-structure.md
=> [Docs] Add DR for project structure refactor

RELEASE_NOTES.md, SANDBOXED_BUILDS.md, contributing/CODING_STYLE.md, contributing/PROCESS.md
Whilst working on #655 various broken links were discovered.
=> [Docs] Fix various links in markdown files

doc/contributing/PROCESS.md
Documenting the release process, based on the comment Tom left on slack.
=> [Docs] Document release process.

RELEASE_NOTES.md, src/openassetio-python/pyproject.toml
=> [Release] Bump version to 1.0.0-alpha.7

.github/workflows/integrations.yml, CMakeLists.txt, RELEASE_NOTES.md
Closes #796
- ~~[ ] I have updated all relevant user documentation.~~
CI passing should be a good indication that all is well.
=> [Build] Don't build C bindings by default

doc/contributing/CODE_REVIEWS.md
Minor additions so we don't forget.
=> [Docs] Add notes on expected Code Review checks

doc/doxygen/src/EntitiesTraitsSpecifications.dox
Fix for minor typos.
- [N/A] ~~I have updated the release notes.~~
Just few obvious things that caught my eye. 
N/A
=> Fix for minor typos

RELEASE_NOTES.md, examples/host/simpleResolver/README.md, examples/host/simpleResolver/simpleResolver.py
Several people have been using `simpleResolver` as a getting started point for a host integration. This is fine, but as it stands, it wasn't the best example of good practice, and needed some additional info to help set people off on the right track.
NB. CI fail is (seemingly) unrelated:  https://github.com/OpenAssetIO/OpenAssetIO/pull/840
=> Update `simpleResolver` and docs with best practices

.github/workflows/integrations.yml
Updates integrations to support the new mediacreation which requires traitgen.
~~- [ ] I have updated the release notes.~~
~~- [ ] I have updated all relevant user documentation.~~
=> Update Integrations to support new MediaCreation

doc/doxygen/src/ForHosts.dox
Capturing a community discussion.
Closes #836
=> Add notes on de-assetization to host reccomendations

examples/host/simpleResolver/simpleResolver.py
Just to help make sure that people realize they should bridge to their own system in real-world scenarios.
=> [Examples] Clarify use of ConsoleLogger in simpleResolver

CODEOWNERS
Facilitates automation, and useful things like [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection).
=> [Docs] Add `CODEOWNERS`

RELEASE_NOTES.md, resources/build/conanfile.py
=> Update `pybind` version

RELEASE_NOTES.md, src/openassetio-core/include/openassetio/BatchElementError.hpp, src/openassetio-core/tests/BatchElementErrorTest.cpp, src/openassetio-core/tests/hostApi/ManagerTest.cpp, src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp, src/openassetio-python/tests/package/hostApi/test_manager.py, src/openassetio-python/tests/package/test_batchelementerror.py
=> [Core] Add eq comparison to BatchElementError

.github/workflows/build-wheels.yml, RELEASE_NOTES.md, src/openassetio-python/pyproject.toml, src/openassetio-python/tests/bridge/CMakeLists.txt, src/openassetio-python/tests/package/hostApi/test_managerimplementationfactoryinterface.py, src/openassetio-python/tests/package/test/manager/test_main.py, src/openassetio-python/tests/package/test_batchelementerror.py
Adds support for Python 3.11, see commit notes.
=> Support Python 3.11

RELEASE_NOTES.md, doc/contributing/CODING_STANDARDS.md, src/openassetio-core/include/openassetio/Context.hpp, src/openassetio-core/include/openassetio/TraitsData.hpp, src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerImplementationFactoryInterface.hpp, src/openassetio-core/include/openassetio/log/ConsoleLogger.hpp, src/openassetio-core/include/openassetio/log/LoggerInterface.hpp, src/openassetio-core/include/openassetio/log/SeverityFilter.hpp, src/openassetio-core/include/openassetio/managerApi/Host.hpp, src/openassetio-core/include/openassetio/managerApi/HostSession.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerStateBase.hpp, src/openassetio-core/include/openassetio/typedefs.hpp, src/openassetio-core/tests/CMakeLists.txt, src/openassetio-core/tests/typedefsTest.cpp
Closes #918
Tests are all compile-time `static_assert` checks.
=> [Core] Add Ptr alias members to classes

RELEASE_NOTES.md
=> [Docs] Fix RELEASE_NOTES ordering

src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #886. Convenience functions and higher-level collection comparisons helps maintainability and readability.
=> Improve readability of Manager tests

RELEASE_NOTES.md, doc/contributing/CODING_STANDARDS.md, src/openassetio-core/include/openassetio/Context.hpp, src/openassetio-core/include/openassetio/TraitsData.hpp, src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerImplementationFactoryInterface.hpp, src/openassetio-core/include/openassetio/log/ConsoleLogger.hpp, src/openassetio-core/include/openassetio/log/LoggerInterface.hpp, src/openassetio-core/include/openassetio/log/SeverityFilter.hpp, src/openassetio-core/include/openassetio/managerApi/Host.hpp, src/openassetio-core/include/openassetio/managerApi/HostSession.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerStateBase.hpp, src/openassetio-core/include/openassetio/typedefs.hpp, src/openassetio-core/tests/CMakeLists.txt, src/openassetio-core/tests/typedefsTest.cpp, src/openassetio-python/bridge/CMakeLists.txt, src/openassetio-python/bridge/include/openassetio/python/converter.hpp, src/openassetio-python/bridge/src/python/converter.cpp, src/openassetio-python/cmodule/src/EntityReferenceBinding.cpp, src/openassetio-python/tests/bridge/CMakeLists.txt, src/openassetio-python/tests/bridge/lsan_suppressions.txt, src/openassetio-python/tests/bridge/python/test_converter.cpp, src/openassetio-python/tests/package/hostApi/test_manager.py, src/openassetio-python/tests/package/test_entityreference.py
=> Merge `main` into related ref feature branch

doc/doxygen/src/EntitiesTraitsSpecifications.dox
=> [Docs] Fix some typos

doc/doxygen/src/Examples.dox
Hopefully makes this part of the "recommended flow" easier to grok
=> [Docs] Add managementPolicy example

doc/doxygen/src/Examples.dox
=> [Docs] Fix typos in the resolving example

doc/decisions/DR018-Result-pager-design.md
Part of #936 
Pretty version [here](https://github.com/OpenAssetIO/OpenAssetIO/blob/c7996576ba27f8f078ac41dc006b6f93dd3449cd/doc/decisions/DR018-Result-pager-design.md).
=> [Docs] Add DR covering high-level pager design

RELEASE_NOTES.md, src/openassetio-python/package/openassetio/constants.py, src/openassetio-python/tests/package/test/manager/test_harness.py
Preparatory work for #998, removing some very old and redundant constants.
=> Remove old constants

RELEASE_NOTES.md, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-core/src/managerApi/ManagerInterface.cpp, src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp, src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp, src/openassetio-python/package/openassetio/hostApi/Manager.py, src/openassetio-python/package/openassetio/managerApi/ManagerInterface.py, src/openassetio-python/package/openassetio/test/manager/harness.py, src/openassetio-python/tests/package/hostApi/test_manager.py, src/openassetio-python/tests/package/managerApi/test_managerinterface.py
=> Migrate `flushCaches` to C++

README.md, ROADMAP.md
=> [Docs] Add high-level `ROADMAP.md`

RELEASE_NOTES.md, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-python/tests/conftest.py, src/openassetio-python/tests/package/hostApi/test_manager.py
=> `isEntityReferenceString` prefix optimisation

RELEASE_NOTES.md, src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
Closes #972.
See BAL PR https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/52 that exercises the new tests.
=> API compliance suite for paged relationship methods

.github/workflows/code-quality.yml, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp, src/openassetio-python/tests/package/hostApi/test_manager.py
See commit messages, closes #26
=> [Core] Remove backdoor access to Manager internals

RELEASE_NOTES.md, doc/contributing/CODING_STANDARDS.md, src/openassetio-core-c/src/managerApi/CManagerInterfaceAdapter.cpp, src/openassetio-core-c/src/managerApi/CManagerInterfaceAdapter.hpp, src/openassetio-core-c/tests/hostApi/ManagerTest.cpp, src/openassetio-core-c/tests/managerApi/CManagerInterfaceAdapterTest.cpp, src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/Host.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/src/hostApi/HostInterface.cpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-core/src/managerApi/Host.cpp, src/openassetio-core/src/managerApi/ManagerInterface.cpp, src/openassetio-core/tests/hostApi/ManagerTest.cpp, src/openassetio-python/cmodule/src/hostApi/HostInterfaceBinding.cpp, src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
Closes #518, see commit message/CODING_STANDARDS.md
=> Conform use of `const` with Interface methods.

doc/decisions/DR020-Coding-style.md
Better late than never... hopefully this captures our thinking _at the time_ (we shouldn't include any new motivations we have thought of in the interim, to allow fair criticism).
=> [Docs] Add coding style DR

doc/decisions/DR021-Cross-language-consistency.md
Better late than never... hopefully this captures our thinking at the time (we shouldn't include any new motivations we have thought of in the interim, to allow fair criticism).
NB, needs #1096 for cross-link.
=> [Docs] Add DR for language consistency

src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp, src/openassetio-python/bridge/include/openassetio/python/converter.hpp, src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystem.py, src/openassetio-python/tests/cmodule/resources/_openassetio_test/errorsTest.cpp, src/openassetio-python/tests/package/hostApi/test_managerfactory.py, src/openassetio-python/tests/package/managerApi/test_managerinterface.py, src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystem.py
Closes #1102 . Update some docstrings and test names missed in #1089.
=> Minor fixes to exception docs

doc/decisions/DR022-Default-method-implementations.md
@elliotcmorris @feltech does this capture what we talked about? Whilst writing it a few revelations occurred - highlighted as questions in the intro.
Rendered version [here](https://github.com/OpenAssetIO/OpenAssetIO/pull/1101/files?short_path=9af3a64#diff-9af3a643212c76abfa0cf12c698c4efc6e2757c13b5b59d2acbfce61e661131a) for 👁️ 
**Host authors, please share your thoughts! It affects you quite a lot!**
Closes #1099.
=> [Docs] Add DR to cover default method implementation strategy

ROADMAP.md
Updates based on TSC and priorities exercise
=> [Docs] Update `ROADMAP.md`

doc/doxygen/src/ForHosts.dox, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
A few tweaks based on observations of real-world implementations.
=> Minor docs tweaks to aid host development

.github/workflows/integrations.yml, examples/host/simpleResolver/simpleResolver.py
Re-enables integrations. and fixes simpleresolver, as we forgot to fix it.
=> Re-enable integrations.

.github/workflows/integrations.yml
Re-enable now that BAL works with the latest breaking changes, as of OpenAssetIO/OpenAssetIO-Manager-BAL#78
=> Re-enable BAL integration test

RELEASE_NOTES.md, doc/doxygen/src/ForManagers.dox, examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py, src/openassetio-core-c/src/managerApi/CManagerInterfaceAdapter.cpp, src/openassetio-core-c/src/managerApi/CManagerInterfaceAdapter.hpp, src/openassetio-core-c/tests/hostApi/ManagerTest.cpp, src/openassetio-core/include/openassetio/access.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/internal.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/src/errors/exceptionMessages.cpp, src/openassetio-core/src/errors/exceptionMessages.hpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-core/tests/hostApi/ManagerTest.cpp, src/openassetio-python/cmodule/src/_openassetio.hpp, src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp, src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp, src/openassetio-python/tests/conftest.py, src/openassetio-python/tests/package/hostApi/test_manager.py, src/openassetio-python/tests/package/managerApi/test_managerinterface.py
Add `hasCapability` method, along with the supporting enum.
Documentation added to the enum in particular to explain the concepts.
Closes #1119 
paired implementation with @foundrytom 
This implementation needed some C-api changes because it's pure virtual, so that's in there.
=> `hasCapability` Method.

src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
Assorted odds and ends we've missed over recent months.
=> [Docs] Fix stale docs

RELEASE_NOTES.md, doc/doxygen/src/Examples.dox, doc/doxygen/src/ForHosts.dox, doc/doxygen/src/ForManagers.dox, doc/doxygen/src/ManagerState.dox, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-core/src/managerApi/ManagerInterface.cpp, src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp, src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py, src/openassetio-python/tests/package/hostApi/test_manager.py, src/openassetio-python/tests/package/managerApi/test_managerinterface.py, src/openassetio-python/tests/package/test/manager/resources/plugins/StubManager.py
=> Finalize abstract methods in ManagerInterface

CPPLINT.cfg, RELEASE_NOTES.md, doc/contributing/CODING_STANDARDS.md, doc/doxygen/src/ForHosts.dox, doc/doxygen/src/ForManagers.dox, src/openassetio-python/cmodule/src/_openassetio.hpp, src/openassetio-python/cmodule/src/hostApi/EntityReferencePagerBinding.cpp, src/openassetio-python/cmodule/src/hostApi/HostInterfaceBinding.cpp, src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp, src/openassetio-python/cmodule/src/hostApi/ManagerFactoryBinding.cpp, src/openassetio-python/cmodule/src/hostApi/ManagerImplementationFactoryInterfaceBinding.cpp, src/openassetio-python/cmodule/src/log/LoggerInterfaceBinding.cpp, src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp, src/openassetio-python/cmodule/src/managerApi/HostBinding.cpp, src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp, src/openassetio-python/tests/cmodule/gil/conftest.py, src/openassetio-python/tests/cmodule/gil/test_entityreferencepager_gil.py, src/openassetio-python/tests/cmodule/gil/test_host_gil.py, src/openassetio-python/tests/cmodule/gil/test_loggerinterface_gil.py, src/openassetio-python/tests/cmodule/gil/test_manager_gil.py, src/openassetio-python/tests/cmodule/gil/test_managerfactory_gil.py, src/openassetio-python/tests/cmodule/gil/test_managerinterface_gil.py, src/openassetio-python/tests/cmodule/resources/_openassetio_test/CMakeLists.txt, src/openassetio-python/tests/cmodule/resources/_openassetio_test/_openassetio_test.cpp, src/openassetio-python/tests/cmodule/resources/_openassetio_test/gilTest.cpp, src/openassetio-python/tests/cmodule/test_gil.py, src/openassetio-python/tests/package/hostApi/test_hostinterface.py, src/openassetio-python/tests/package/log/test_loggerinterface.py, src/openassetio-python/tests/package/managerApi/test_entityreferencepagerinterface.py
=> Python GIL Management

RELEASE_NOTES.md, src/openassetio-core/CMakeLists.txt, src/openassetio-core/include/openassetio/BatchElementError.hpp, src/openassetio-core/src/BatchElementError.cpp, src/openassetio-core/tests/deprecationsTest.cpp, src/openassetio-python/package/openassetio/__init__.py, src/openassetio-python/package/openassetio/exceptions.py, src/openassetio-python/tests/package/test_deprecations.py
Should help allow code to work in `a14` and `b1.rev0`
=> Add deprecations for errors/exceptions

ROADMAP.md
Minor updates to cover b1.0 release until we plan out the next quarter.
=> [Docs] Update ROADMAP for b1.0 release

README.md, ROADMAP.md
In lieu of some more time to rethink onboarding properly.
=> Add useful links to README

.github/workflows/integrations.yml, RELEASE_NOTES.md, doc/doxygen/src/Examples.dox, doc/doxygen/src/Glossary.dox, src/openassetio-core/include/openassetio/access.hpp, src/openassetio-core/include/openassetio/hostApi/Manager.hpp, src/openassetio-core/include/openassetio/internal.hpp, src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp, src/openassetio-core/src/hostApi/Manager.cpp, src/openassetio-core/src/managerApi/ManagerInterface.cpp, src/openassetio-python/cmodule/src/accessBinding.cpp, src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp, src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp, src/openassetio-python/package/openassetio/access.py, src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py, src/openassetio-python/tests/cmodule/gil/test_manager_gil.py, src/openassetio-python/tests/cmodule/gil/test_managerinterface_gil.py, src/openassetio-python/tests/cmodule/resources/_openassetio_test/gilTest.cpp, src/openassetio-python/tests/conftest.py, src/openassetio-python/tests/package/hostApi/test_manager.py, src/openassetio-python/tests/package/managerApi/test_managerinterface.py, src/openassetio-python/tests/package/test/manager/resources/plugins/StubManager.py, src/openassetio-python/tests/package/test_access.py
Closes #31. Add the `entityTraits` method.
=> Add `entityTraits`

doc/doxygen/src/Glossary.dox
Attempting to capture the main sentiment behind the OpenAssetIO approach to publishing as part of #1043.
Ran out of time so this is in need of a good edit and links fixing etc. The idea would be then to expand upon this in each of the respective main doc/method sections with more details from the host/manager perspectives.
=> WIP [Docs] Revise publishing docs

ROADMAP.md
Roadmap was a tad out of date, just move a few things around to make it a little bit more representative.
=> [Docs] Update roadmap

.github/workflows/code-quality.yml
Just fixing a copy paste error from earlier.
=> [CI] Amend unpinned checkout action.

doc/doxygen/src/MainPage.dox
Based on feedback that resources were hard to discover, add an index to the top of the main doc page.
=> [Doc] Add resources callout to top of docs.

src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystemManagerImplementationFactory.py
=> [Doc] Fix incorrect PluginError doc

README.md, doc/contributing/CHANGES.md
OpenAssetIO is beginning to maintain API/ABI guarantees. Add documentation about this to the readme, and update standards about release-notes.
This came from a TSC decision.
=> [Docs] Add versioning/compatibility policy.

doc/doxygen/src/Glossary.dox
=> Docs typo fix

doc/doxygen/src/Examples.dox
Remove temp doc message and link to OpenAssetIO Manager Python and Plugin for Ayon
=> Manager doc update

doc/doxygen/src/EntitiesTraitsSpecifications.dox
=> [Docs] Typo fix

doc/doxygen/src/Glossary.dox
=> [Docs] Fix broken link in glossary

doc/doxygen/src/EntitiesTraitsSpecifications.dox
Adds clarification of non hierarchical nature of traits.
Closes #1393
=> [Docs] Add clarification about non-hierarchical nature of traits

doc/decisions/DR025-UI-delegation-plugin-interface.md
Part of #1367. In order to determine the necessary changes to the existing API in order to support UI delegation, we must first decide how UI delegation implementations should be loaded into an application.
So add a decision record that theorises an implementation based on prior art in Katana and FnAssetAPI, and contrasts this with the naive implementation that extends the existing plugin scaffolding.
[Rendered output](https://github.com/OpenAssetIO/OpenAssetIO/blob/9e84d0ade9921f5967f85e37bde83cd331edc266/doc/decisions/DR025-UI-delegation-plugin-interface.md)
Keep an eye out for, e.g. 
- Things not explained well that need rephrasing or additional information
- Pros and cons that may have been missed
- Entirely different approaches that should be considered
=> DR for UI delegation plugin architecture

RELEASE_NOTES.md
=> Add missing release notes for hybrid plugins

src/openassetio-core/tests/pluginSystem/resources/plugins/working/CMakeLists.txt, src/openassetio-python/tests/bridge/CMakeLists.txt, src/openassetio-python/tests/package/hostApi/test_managerfactory.py, src/openassetio-python/tests/package/pluginSystem/resources/README.md, src/openassetio-python/tests/package/pluginSystem/resources/deprecated/deprecatedPlugin.py, src/openassetio-python/tests/package/pluginSystem/resources/entryPoint/site-packages/packaged_plugin/PackagePlugin.py, src/openassetio-python/tests/package/pluginSystem/resources/entryPoint/site-packages/packaged_plugin/__init__.py, src/openassetio-python/tests/package/pluginSystem/resources/entryPoint/src/packaged_plugin/PackagePlugin.py, src/openassetio-python/tests/package/pluginSystem/resources/pathA/modulePlugin.py, src/openassetio-python/tests/package/pluginSystem/resources/pathB/packagedPlugin/PackagePlugin.py, src/openassetio-python/tests/package/pluginSystem/resources/pathB/packagedPlugin/__init__.py, src/openassetio-python/tests/package/pluginSystem/resources/pathC/modulePlugin.py, src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystemmanagerplugin.py, src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystemplugin.py
Part of #1445. In preparation for re-using much of the test logic for a new UI delegation plugin system, fix a few minor issues with the various plugin system tests. See commits for more details.
=> Tidy tests related to the plugin system
