- doc/Makefile
We should be using the pinned versions. `npm install` doesn't respect package-lock.json. In addition, updates picked up during `make deploy` would then cause the deploy to fail as there are un-staged changes to package-lock.json.
`npm ci` (https://docs.npmjs.com/cli/v6/commands/npm-ci) does what we want.
> [Build] Use `npm ci` instead of `npm install .` for docs build

- .editorconfig
Set the indent size to 2 to match current YAML files in the repo.
> [CI] Add yml section in .editorconfig

- .github/workflows/test.yml
Part of #21, ensures `pytest` is run for all PRs, preventing merges on failures.
There is a [mirror PR](https://github.com/foundrytom/OpenAssetIO/pull/2) that shows the action running.
> [CI] Run `pytest` for Pull Requests

- python/openassetio/exceptions.py
- python/openassetio/managerAPI/ManagerInterface.py
Closes #54, `BaseException` is a built-in type in Python, so we should avoid shadowing it.
> [Core] Rename `BaseException` -> `OAIOException`

- .github/workflows/docs.yml
- doc/Makefile
- doc/README.md
- doc/deploy.sh
For #21, sets up CD that continually deploys `main` to GitHub pages.
This required a little refactoring of the `Makefile` to split out the deployment logic. It was getting a bit complex for single line shell foo.
There are runs for a deployment [here](https://github.com/foundrytom/OpenAssetIO/runs/4326630988?check_suite_focus=true), and one where there is no change to the built docs [here](https://github.com/foundrytom/OpenAssetIO/runs/4326658874?check_suite_focus=true).
> [Docs] Continuous deployment of GitHub Pages from `main`

- .github/workflows/problem-matchers/doxygen.json
- .github/workflows/test.yml
Part of #21, builds docs as for pull requests, and adds the Doxygen problem matcher. 
This should allow us to catch docs build errors through the status checks. 
For now, this is a known-fail until we fix the remaining Doxygen warnings due to the UI and other sundry parameter errors. #94  and #98 resolve many of the warnings reported on `main`, bar the UI ones.
> [CI] Build docs for Pull Requests to catch markup errors

- CONTRIBUTING.md
- doc/src/Examples.dox
- doc/src/ManagerState.dox
- doc/src/Transactions.dox
- python/openassetio/constants.py
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/managerAPI/test_managerinterface.py
Addressing the bulk of #43 by rewriting `Manager` and `ManagerInterface` methods to take/return lists.
The `setMetadata*` methods are deliberately left with minimal changes, since we expect to remove them (see #3 and #4).  Similarly `thumbnailSpecification` is left untouched since we expect to remove it in #86.
> [Core] Batch manager methods

- doc/Doxyfile
- doc/Makefile
- doc/src/ForHosts.dox
- doc/src/ForManagers.dox
- python/openassetio/hostAPI/ManagerFactoryInterface.py
- python/openassetio/pluginSystem/ManagerPlugin.py
- python/openassetio/pluginSystem/PluginSystemManagerFactory.py
- Adds a new Doxygen alias so we can get rid of all the failures from #104 due to docs we haven't migrated from `FnAssetAPI` yet. 
- Adds a `doc/Makefile` target to list them.
> [Docs] Fix broken `@refs` pointing to un-migrated docs

- .github/workflows/test.yml
#104 introduced PR checks for the Doxygen docs build. 
Due to the unique way in which problem matchers work, we require manual effort to actually fail the job.  We'd been using `! grep` for this purpose, and printing its output as a summary of failures. However, some of the Doxygen warnings are multi-line, and so the summary is less helpful. 
This switches grep to quiet mode. The reader can always click-through from the annotation to the correct line in the log anyway, which makes it easier to see the remaining lines of the message until (if) we figure out a multi-line matcher.
> [CI] Suppress summary output from grep when checking for build errors

- .github/workflows/code-quality.yml
Closes #21. This supersedes #105 as the action code has been moved to TheFoundryVisionmongers/fn-pylint-action#1.
This is `on-hold` until that PR has been merged, and the `v1.0.0` release has been made.
> [CI] Run `pylint` for Pull Requests

- python/openassetio/hostAPI/HostInterface.py
Auditing should only be added to the wrapper class, rather than the interface. This was inadvertently left in from the old API structure, where there was no wrapper on the host side.
> [Core] Remove `@auditApiCall` from `HostInterface`

- doc/src/Examples.dox
- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/pluginSystem/ManagerPlugin.py
- tests/openassetio/hostAPI/test_manager.py
It doesn't make much sense to allow the manager's identifier to vary. It has to be consistent with the one reported by the ManagerPlugin. Having this be an instance method makes having a single source of truth a little ugly to no tangible benefit.
Leaving the host side, as it makes more sense to be an instance method, as an application may have different modes served from the same binary (eg: PLE).
Considered making this a read-only property, but keeping it as a method for symmetry with `HostInterface` (which has to be a method in c++).
> [Core] Make `ManagerInterface.identifier` static

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/Host.py
- python/openassetio/managerAPI/HostSession.py
- tests/openassetio/test_imports.py
`managerAPI.Host` was importing `HostInterface`, which meant the `hostAPI` package was initialized, which hoists `Manager`, this in turn was importing `HostSession` which was importing `Host`...
...all in the aid of previously removed Python 3 type hints (#64), which meant they were unused imports anyway!
Definitely looking forward to this all being back in C++ and getting rid of all these hoists.
Adds test coverage to keep an eye on this.
> [Core] Fix cyclic dependencies in module imports

- doc/src/EntitySpecMeta.dox
- doc/src/ForHosts.dox
- doc/src/ForManagers.dox
- doc/src/Glossary.dox
- doc/src/MainPage.dox
- doc/src/Transactions.dox
- python/openassetio/Context.py
- python/openassetio/constants.py
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
Closes #3. Using the term "metadata" was fundamentally misleading. There
is nothing "meta" about the data held in an entity's associated key/value
pairs. It is considered part of the entity itself - as a companion to
the primary string.
Metadata also conjured up thoughts around timestamps, permissions etc. when raised in discussions around the purpose of the API.
We considered 'data', but it was too ambiguous with the 'data' that may be referenced by the primary string when it is an URL.
We considered 'properties', and enjoyed a journey down a philosophical rabbit hole reading Wikipedia articles on the philosphy of attributes and properties and ended up coming up none the wiser.
We settled on attributes, probably for no specific reason. The computing version of the attributes wikipedia …
> [Core] Rename `metadata` to `attributes`

- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/test/managerValidator/__init__.py
- python/openassetio/test/managerValidator/__main__.py
- python/openassetio/test/managerValidator/commandLine.py
- python/openassetio/test/managerValidator/validatorHarness.py
- python/openassetio/test/managerValidator/validatorSuite.py
- resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py
- resources/examples/manager/SampleAssetManager/test/fixtures.py
- tests/openassetio/test/managerValidator/__init__.py
- tests/openassetio/test/managerValidator/conftest.py
- tests/openassetio/test/managerValidator/test_commandLine.py
- tests/openassetio/test/managerValidator/test_validatorHarness.py
Implement the basic manager plugin test harness for #95 
Not covered:
* Nice bootstrap error messages (e.g. loading fixtures, initialising manager)
* Updating wider .dox documentation
> [Test] Add Manager plugin test harness

- pyproject.toml
- python/openassetio/Context.py
Part of #101.
Sets some baseline ignores, and addresses some issues in `Context.py`.
This also fixes up some missing Doxygen documentation for `Context` properties.
> The great `pylint` cleanup - Part I - `Context.py`

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
Part of #101. Once #138 is merged, this should hopefully clean up all `pylint` errors in `Manager.py` and `ManagerInterface.py`
> The great `pylint` cleanup - Part III - `Manager`/`ManagerInterface`

- doc/src/Examples.dox
It was victim of a mid-air-collision when we renamed Metadata to Attributes in #117.
> [Docs] Fix thumbnails example code

- pyproject.toml
- python/openassetio/_core/audit.py
- tests/openassetio/_core/test_audit.py
- tests/openassetio/managerAPI/test_managerinterface.py
- tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
Cleans up assorted bugs spotted by `pytlint`, adds minimal test coverage to verify fixes. This deliberately keeps coverage light as this whole mechanism will have to change significantly when we port to C++.
> The great `pylint` cleanup - Part IV - `audit.py`

- python/openassetio/_core/debug.py
Part of #101. Fixes all `pylint` warnings for `debug.py`, and manages to remove some old docs fudgery required for older python versions.
> The great `pylint` cleanup - Part V - `debug.py`

- python/openassetio/_core/objects.py
Part of #101. Fixes remanning warnings in the `_core` package.
> The great `pylint` cleanup - Part VI - `objects.py`

- .github/workflows/problem-matchers/doxygen.json
- .github/workflows/test.yml
- doc/src/Thumbnails.dox
Inadvertently missed off preprocessing warnings that include a prefix before the file path.
https://github.com/foundrytom/OpenAssetIO/actions/runs/1559423183 is a run prior to the second commit, that shows the improved regex catches the existing failure.
> [CI] Ensure Doxygen problemMatcher catches all warnings

- doc/src/Examples.dox
- python/openassetio/constants.py
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
Technically, saying "some calls won't need it" is a bit of a lie. In theory, if this was provided, we could avoid ever calling `isEntityRefrence`. Shall we gloss over that for now, to make sure that people do still implement that method. If feels ripe for fragility otherwise?
> [Core] Remove `kField_EntityReferencesMatchRegex`

- python/openassetio/Context.py
- python/openassetio/Specification.py
- python/openassetio/SpecificationFactory.py
- python/openassetio/__init__.py
- python/openassetio/_core/audit.py
- python/openassetio/_core/debug.py
- python/openassetio/_core/objects.py
- python/openassetio/constants.py
- python/openassetio/exceptions.py
- python/openassetio/hostAPI/HostInterface.py
- python/openassetio/hostAPI/Manager.py
- python/openassetio/hostAPI/ManagerFactoryInterface.py
- python/openassetio/hostAPI/Session.py
- python/openassetio/hostAPI/__init__.py
- python/openassetio/hostAPI/terminology.py
- python/openassetio/hostAPI/transactions.py
- python/openassetio/logging.py
- python/openassetio/managerAPI/Host.py
- python/openassetio/managerAPI/HostSession.py
- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/managerAPI/__init__.py
- python/openassetio/pluginSystem/__init__.py
- python/openassetio/specifications.py
Part of #101, adds missing docstrings, and/or converts `##` style module comments to docstrings and adds `@namespace` labels.
> The great `pylint` cleanup - Part X - docstrings

- python/openassetio/hostAPI/ManagerFactoryInterface.py
- python/openassetio/logging.py
- tests/openassetio/hostAPI/test_logging.py
Some leftovers form the Python 2 -> 3 update. See #151 for this fix in `Specification`. Currently omitting `ManagerInterface` to do as part of #163.
> [Core] Update Python 2 `__metaclass__` declarations.

- python/openassetio/Specification.py
- python/openassetio/SpecificationFactory.py
- python/openassetio/_core/objects.py
- tests/openassetio/test_specification.py
This started out a routine clean up as part of #101. It however turned up a few bugs in `Specification`. Largely due to the somewhat suspicious dev practices ~we~ I had when I wrote this some very, very, long time ago in a text editor far away.
As `Specification` is quite a pivotal class in this API, it is worth sorting these out now regardless of what is happening when it comes to the `C++` port. 
The first few commits are mild linter fixes, the rest add test coverage to properly define the expected behaviour and fix the issues that surfaced.
> [Core] Misc `Specification` fixes

- .github/workflows/code-quality.yml
- python/openassetio/pluginSystem/ManagerPlugin.py
- python/openassetio/pluginSystem/PluginSystem.py
- python/openassetio/pluginSystem/PluginSystemManagerFactory.py
- python/openassetio/pluginSystem/PluginSystemPlugin.py
- python/openassetio/pluginSystem/__init__.py
- tests/openassetio/pluginSystem/resources/README.md
- tests/openassetio/pluginSystem/resources/pathA/modulePlugin.py
- tests/openassetio/pluginSystem/resources/pathB/packagedPlugin/PackagePlugin.py
- tests/openassetio/pluginSystem/resources/pathB/packagedPlugin/__init__.py
- tests/openassetio/pluginSystem/resources/pathC/modulePlugin.py
- tests/openassetio/pluginSystem/resources/symlinkPath/modulePlugin.py
- tests/openassetio/pluginSystem/resources/symlinkPath/packagedPlugin
- tests/openassetio/pluginSystem/test_pluginsystem.py
- tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
#101 highlighted that `imp` was deprecated. After addressing some minor listing issues, this PR switches the plugin system to `importlib`. Some bonuses include:
- We now support single file modules and packages.
- Test coverage!
This has ended up a little larger than one would like, but due to the holidays opportunities for review have been scarce. As such some linter fixes are in here too, as splitting them out would have meant unpicking a whole bunch of conflicts.
> ~Note: On hold pending https://github.com/TheFoundryVisionmongers/fn-pylint-action/pull/2.~
> [PluginSystem] Switch to `importlib` and other improvements.

- tests/conftest.py
- tests/openassetio/_core/test_audit.py
- tests/openassetio/test_imports.py
Highlighted as part of #101, we were duplicating the module cache cleanup code.
@feltech - know any `pytest` tricks to auto-use an existing fixture without the dance here?
> [Tests] Remove code duplication

- CONTRIBUTING.md
Capturing the discussion around https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/152#discussion_r778299871
Longer-term we should probably split the documentation advice out at some point as there are a bunch of other conventions we follow.
> [Docs] Add notes on doxygen formatting for method params

- .github/workflows/docs.yml
This was inadvertently missed in 33f1f99 in #156.
> [CI] Fix `GITHUB_ORG` used for docs deploy

- .github/workflows/docs.yml
- .github/workflows/test.yml
Lol. Part of #109. Switches (back) to `TheFoundryVisionmongers` org for the docs Docker image, now we can host public packages.
> [CI] Use `TheFoundryVisionmongers` registry for docs Docker image

- .github/workflows/code-quality.yml
- tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
The final part of #101. The `pylint` check should now pass with no warnings, and can be marked as required for Pull Requests.
> The great `pylint` cleanup - Part XII - a journeys end

- python/openassetio/pluginSystem/ManagerPlugin.py
- python/openassetio/pluginSystem/PluginSystem.py
- python/openassetio/pluginSystem/PluginSystemManagerFactory.py
- python/openassetio/pluginSystem/PluginSystemPlugin.py
A few module docstrings were missing their respective `@namespace` prefix that causes the text to actually get rendered in the Doxygen output for the module - see blank spaces in https://thefoundryvisionmongers.github.io/OpenAssetIO/annotated.html
> [Docs] Add missing `@namespace` to module docstrings

- README.md
Long-term, we need to support all three platforms, but right now, testing and development resources are keeping us focused on `linux`.
> [Docs] Add notes on currently supported platforms

- decisions/DR004-Core-language-support.md
Part of #181, documents the high-level strategy for multi-language support. Specifics around the conventions we will use on the ground will come at a later date, once this choice is ratified.
Thanks to @feltech for the comprehensive code sketch.
The most digestible view of the document is [here](https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/189/files?short_path=13a4af3#diff-13a4af328cd7c2e775857a05460352d18efd46f463288a24f7a158495bd2d980).
This PR serves to validate the decision itself, not just the correctness of its writeup (given it's me, I'm sure there will be some copy gremlins 🙃). Any parties with comment on the choice itself should feel free to use this to discuss the topic.
> [Docs] Add decision record for core language strategy

- doc/README.md
> [Docs] Fix manual Docs docker image build instruction

- src/openassetio-python/CMakeLists.txt
For #183 - tidy up to remove the now-pointless `add_custom_command` and roll it into the `add_custom_target`.
Also remove `dev` from the target name, since that was originally there to reflect the `--editable` nature.
> [Build] Simplify Python install build target

- decisions/DR006-Generic-string-type.md
Part of #193.
We must decide what generic string type should be exposed in the API(s).
Strings are a core data type of OpenAssetIO, used as both input and output of entity references and URIs, as well as nested within dictionary types for entity attributes and specifications.
> [Docs] Add decision record for generic string type

- contributing/CODE_REVIEWS.md
- contributing/COMMITS.md
- contributing/PROCESS.md
- contributing/PULL_REQUESTS.md
Closes #197, and catches a few other strays. There is no standardised GitHub sourced MD link checker, which means we'd need to give any broader marketplace tools the once-over first, so saving that for another day.
> [Doc] Development process improvements

- .github/workflows/test.yml
Closes #199
Publishes the documentation html built to allow us to access the docs for QA
> [CI] Publish docs artifacts

- tests/openassetio/test/manager/test_harness.py
- tests/openassetio/test/manager/test_main.py
#216 highlighted that the existing tests on `feature/96-exampleManager` didn't work on Windows. This PR fixes those tests.
**NOTE:** This PR contains cherry-picked commits to enable windows CI. These need to be dropped before merge, but are here to show the tests now pass.
> [Tests] Fix `openassetio.test.manager` tests on Windows

- python/openassetio/hostAPI/Session.py
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/hostAPI/test_session.py
- tests/openassetio/hostAPI/test_terminology.py
- tests/openassetio/hostAPI/test_transactions.py
- tests/openassetio/test_logging.py
- tests/openassetio/test_specification.py
Part of #130, makes a start of refactoring the tests so that they properly describe the expected behaviour rather than the area of code being tested. There are still many test suites to be done, but this PR serves to validate the approach and actually get some of this work in the code base.
The result should be that we have exactly the same coverage, just in a better structure.
Note: This deliberately doesn't address any issues with specific tests, to keep the scope of this work to just the logical structure of the tests themselves. We should pick those up in subsequent work. It also leaves the refactor to move tests above fixtures and utility code to future work.
> Use `when`/`then` form for test names - Part 1

- python/openassetio/Specification.py
- python/openassetio/test/manager/_implementation.py
- python/openassetio/test/manager/harness.py
- python/openassetio/test/manager/specifications.py
- python/openassetio/test/specifications.py
- tests/openassetio/test/manager/conftest.py
- tests/openassetio/test/manager/resources/suite_executeSuiteTests.py
- tests/openassetio/test/manager/test__implementation.py
- tests/openassetio/test/manager/test_harness.py
- tests/openassetio/test_specification.py
Following on from #219, makes the test harness hosts follow best practice of setting a suitably configured locale in all context's passed to API calls. Doing it in the test loader saves the test author from having to write a lot of boilerplate.
Ultimately, we should probably make `Context.locale` required and enforce that is its not `None` somewhere.
> [Test] Provide a suitably configured locale to `FixtureAugmentedTestCase`

- .github/workflows/test.yml
- .gitignore
- BUILDING.md
- CMakeLists.txt
- README.md
- cmake/DefaultTargetProperties.cmake
- resources/build/Vagrantfile
- resources/build/bootstrap-ubuntu-20.04.sh
- resources/build/conanfile.txt
- setup.cfg
- src/openassetio-python/CMakeLists.txt
For #182, re-enable `pytest` testing, wrapped in a `ctest` target. That is, `cmake` configure the project then run `ctest` in Github CI. 
Only Linux is supported and enabled at the moment in Github CI. Windows and OSX support are left for future work.
The `openassetio-python` CTest target is configured to ensure dependencies are built and installed, including a Python environment for running the tests. 
A [Vagrant](https://www.vagrantup.com/) virtual machine config is included that roughly mirrors the Github Linux CI environment, useful for testing CI changes and onboarding devs.
The [Conan](https://conan.io/) package manager is used to source third-party dependencies from the public [ConanCenter](https://conan.io/center/) repository, for both Github CI and the Vagrant VM.
The README is …
> [CI] Build and test via CTest

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
As documented, this method should only be testing if the format of the string is valid, as such, the result of this should _never_ be context dependent. Supplying a context is redundant and just creates ambiguity.
> [Core] Remove context passed to `isEntityReference`

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/test/manager/apiComplianceSuite.py
- resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py
- resources/examples/manager/SampleAssetManager/tests/fixtures.py
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/test/manager/resources/fixtures_cliFail.py
- tests/openassetio/test/manager/resources/fixtures_cliPass.py
- tests/openassetio/test/manager/resources/plugins/StubManager.py
A partial precursor to #115, removes the optional `entityRef` from `managementPolicy`. It seemed like a good idea at the time, but in reality, just opens up ambiguity, and only half solves the problem.
#9 covers the fact that we need a broader mechanism for working out if operation X can be done in the context of Y. One of these things could be to register a new entity to a specific target entity. A more flexible mechanism that covers this and the topics in #9 would be far better than shoehorning the check into `managementPolicy` - which has no mechanism for communicating why.
With the optional reference, it was not clear if a host should always call this prior to `preflight`/`register` or not. Technically, it should! When we do resolve #9, that would then mean two methods potentially …
> [Core] Remove optional entity ref from `managementPolicy`

- python/openassetio/test/manager/apiComplianceSuite.py
- python/openassetio/test/manager/harness.py
- tests/openassetio/test/manager/test_harness.py
It is very easy for test case authors to forget to set the correct locale. This saves everyone getting it wrong, as long as they remember to use it.
> [Test] Fix locale used in `apiComplianceSuite`

- doc/src/Examples.dox
- doc/src/ForHosts.dox
- python/openassetio/_core/debug.py
- python/openassetio/constants.py
- python/openassetio/hostAPI/Session.py
- python/openassetio/log.py
- python/openassetio/managerAPI/HostSession.py
- python/openassetio/test/manager/_implementation.py
- tests/openassetio/hostAPI/test_session.py
- tests/openassetio/managerAPI/test_hostsession.py
- tests/openassetio/pluginSystem/test_pluginsystem.py
- tests/openassetio/pluginSystem/test_pluginsystemmanagerfactory.py
- tests/openassetio/test/manager/conftest.py
- tests/openassetio/test_imports.py
- tests/openassetio/test_log.py
Rename the module from logging to log and fix all references in tests and documentation.
Closes #58
> [API] Rename logging module to log

- contributing/COMMITS.md
Adds a few missing ones that have surfaced over recent months, and fixes the missing `s` in the `Tests` component.
> [Docs] Update commit component tags in `COMMITS.md`

- resources/examples/manager/BasicAssetLibrary/schema.json
- resources/examples/manager/BasicAssetLibrary/tests/resources/library_apiComplianceSuite.json
Now it is actually in GitHub, it illustrated the previous schema URL was incorrect.
Can anyone test this with their IDE to see if it is working ok? Editing the BAL test library json should validate correctly now.
I'm not sure this is set up right yet.
> [Examples] Fix BAL JSON Schema URLs

- .clang-tidy
- cmake/StaticAnalyzers.cmake
- contributing/CODING_STANDARDS.md
- resources/build/bootstrap-ubuntu-20.04.sh
- src/CPPLINT.cfg
Clang-Tidy 10 flags a `performance-unnecessary-value-param` error with the following
```
explicit BaseTrait(SpecificationDataPtr specificationData)
: HasSpecificationData(std::move(specificationData)) {}
```
saying that `specificationData` should be a const reference. However, this snippet isn't a performance concern since `specificationData` is (immediately) moved. This idiom is beneficial in the case that `BaseTrait` was constructed with an rvalue `SpecificationDataPtr`, where a const reference would involve a pointless copy rather than a move.
Clang-Tidy 12 doesn't complain about this.  
Unfortunately Clang-Tidy 12 also doesn't complain if I remove the `std::move`.  Neither does Clang-Tidy 14.  However, if I assign to a member variable rather than pass to the base class constructor …
> [CI] Avoid a couple of false-positives in C++ linters

- doc/src/Examples.dox
- doc/src/ForHosts.dox
- python/openassetio/hostAPI/HostInterface.py
- python/openassetio/managerAPI/Host.py
- tests/openassetio/managerAPI/test_host.py
We still fundamentally believe that the ability for a manager to query the current host for information about entity usage and its documents is critical. However, the current API was not well thought out (as it
assumed a 'current' document, which may be a little tenuous).
This PR closes #6 by removing the current API, so that we can add a more fit-for-purpose API in over time as we have more concrete use cases from manager authors.
> [Core] Remove the host document API

- python/openassetio/hostAPI/transactions.py
- tests/openassetio/hostAPI/test_transactions.py
Changes TransactionCoordinator.thawManagerState to be the reverse of freezeManagerState.
The main motivation is to remove a redundant state creation when the host creates a context, then immediately thaws a serialized state back into it, overwriting the one just made by the manager.
This also makes the API more consistent with the actual behaviour, in terms of "context lifetime associates API calls".
Closes #79.
> [Core] Improve context thawing API

- .github/workflows/commit-checks.yml
Helps mildly protect against supply chain attacks or unexpected behavioural changes. Spotted by @feltech when copying the actions from this repo to `otio-openassetio` [here](https://github.com/TheFoundryVisionmongers/otio-openassetio/pull/2).
> [CI] Pin versions for dco check actions

- contributing/CODING_STANDARDS.md
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/managerAPI/test_managerinterface.py
This hopefully reduces the ambiguity where this method could be considered to be in the same area as the `displayName` methods, and ties it more closely with its counterpart - `entityVersions`.
Closes https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/118.
> [Core] Rename `Manager.entityVersionName`

- resources/build/conanfile.txt
Use the same version as is baked into the CY2022 AWSF Docker image.
See: https://github.com/AcademySoftwareFoundation/aswf-docker/tree/master/ci-base
Amongst other advantages, this version adds a handy `pybind11::attribute_error` exception that can be thrown from C++, appearing in Python as `AttributeError`.
The initial motivation for this PR was to allow use of `attribute_error` in #255, but aligning with ASWF is a compelling reason in its own right.
> [Core] Bump pybind11 version to 2.8.1

- .clang-format
`clang-format` can group includes in such a way that `cpplint` complains. So disable re-grouping of includes (but still sort includes within groups).
For example, given
```
#include <iostream>
#include <cassert>
#include <pybind11/pybind11.h>
#include <openassetio/managerAPI/ManagerInterface.hpp>
```
before this PR running `clang-format` would produce
```
#include <pybind11/pybind11.h>
#include <cassert>
#include <iostream>
#include <openassetio/managerAPI/ManagerInterface.hpp>
```
which `cpplint` would complain with an error like
```
Found C++ system header after other system header. Should be: _openassetio.h, c system, c++ system, other.  [build/include_order] [4]
```
After this PR the result it
```
#include <cassert>
#include <iostream>
#include <pybind11/pybind11.h>
#include …
```
> [Lint] clang-format preserve #include groups

- src/openassetio-python/CMakeLists.txt
ASan hangs in an infinite loop if an exception is raised in a `.so` that was loaded by a `dlopen`ed library. See code comments for more info.
This was discovered during #255 development.
> [CI] LD_PRELOAD libopenassetio if ASan enabled

- src/openassetio-python/CMakeLists.txt
Ensures that `pytest` is run from the project root, and includes the `resources` dir in checks so example code is covered.
Resolves one of two issues surfaced by #276.
> [Build] Fix `ctest` invocation of `pytest`

- tests/openassetio/test/manager/test_main.py
Ensures the tests run the CLI using the same python as the tests themselves. Fixes one of two issues surfaced by #276 (#278 sorts the other).
> [Tests] Ensures `test.manager` checks use correct interpreter

- doc/Doxyfile
- python/openassetio/__init__.py
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/include/openassetio/specification/Specification.hpp
- src/openassetio-core/include/openassetio/trait/BlobTrait.hpp
- src/openassetio-core/include/openassetio/trait/TraitBase.hpp
- src/openassetio-core/include/openassetio/trait/property.hpp
- src/openassetio-core/specification/Specification.cpp
- src/openassetio-core/trait/BlobTrait.cpp
- src/openassetio-python/CMakeLists.txt
- src/openassetio-python/_openassetio.cpp
- src/openassetio-python/_openassetio.hpp
- src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp
- src/openassetio-python/specification/SpecificationBinding.cpp
- src/openassetio-python/trait/BlobTraitBinding.cpp
- tests/openassetio/test_traits.py
For #250 we require the C++ infrastructure to support specifications following the new design of #238 et al. 
This PR introduces an initial draft of specifications as dictionary-like data structures and traits as views on a specification, coded in C++ with Python bindings, and tested exclusively through the Python bindings.
Initial performance tests using #270 and reported in #253 lead us to believe the performance of this dictionary-like design is unlikely to be a serious bottleneck.
The Doxygen config is updated to render docs for the new C++ classes.
> [Core] Add specification/trait C++ implementation

- decisions/DR007-Hierarchical-or-compositional-traits-for-specifications.md
Specifications are used to define the nature of entities, relationships, or locales in OpenAssetIO. The decision we've just made describes a change from a hierarchical structure for specifications to a trait based, more functional approach. Please give your thoughts on this decision record, your feedback makes our work more relevant to you. 
Easy to read view: [DR007-Hierarchical-or-compositional-traits-for-specifications.md](https://github.com/TheFoundryVisionmongers/OpenAssetIO/blob/124790f0d136defff1b292e4b42827d123ff9364/decisions/DR007-Hierarchical-or-compositional-traits-for-specifications.md)
> [Docs] Add hierarchical or compositional specifications decision record

- decisions/DR008-Unify-the-entity-data-model.md
#247 raises an interesting question. This PR presents a decision record to move to a unified entity data model for peer review.
We still need to quantify any concerns around changes to the low-level performance of the old `resolveEntityReference` method that this could introduce. The plan is to solicit feedback from community members as to representative numbers around time spent in different aspects of a typical resolution lookup, and compare these to the API-level overhead involved in bridging the respective data types of each approach.
The pretty view of this DR is available [here](https://github.com/TheFoundryVisionmongers/OpenAssetIO/blob/48e5857045d84b745d48a00b64cb23a48212432d/decisions/DR008-Unify-the-entity-data-model.md).
> [Docs] Add decision record to unify entity data model

- README.md
Add link to the working group meetings from the main project readme. Idea from MovieLabs wanting to attend meetings but not being able to find how.
Signed-off-by: mmazerolle <mathieu.mazerolle@foundry.com>
> [Docs] Add link to working group meetings in Getting Involved section.

- src/openassetio-core/include/openassetio/specification/Specification.hpp
- src/openassetio-core/specification/Specification.cpp
- src/openassetio-python/specification/SpecificationBinding.cpp
- tests/openassetio/test_traits.py
Retrieves the list of traits the Specification has been populated with. This is the first step to allowing introspection of a Specification's data by exposing which traits have been set.
Be kind, it's been a long time since I've been writing `C++` 🙃.
> [Core] Add `Specifications::traitIDs` method

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/managerAPI/test_managerinterface.py
Updates the signature for `defaultEntityReference` to take a set of trait IDs rather than a `Specification`. This removes the ambiguity around whether or not the method should consider the properties of the traits vs their identifiers.
This method is meant as a high-level starting point for some "kind" of entity, before they exist, so it should not be affected by the data of any particular entity itself.
> [Core] Migrate `defaultEntityReference` to use trait sets

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- src/openassetio-core/include/openassetio/specification/Specification.hpp
- src/openassetio-core/specification/Specification.cpp
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/test_traits.py
For any given set of traits, composed to form a specification, logically:
- Any given trait ID should not be present more than once.
- The order the traits are considered has no meaning.
We previously used `std::vector` as the container for a specifications's trait IDs. This commit switches to a `std::unordered_set` to make the above logic explicit in the implementation.
> [Core] Switch `TraitIDs` to `unordered_set`

- doc/src/Examples.dox
- doc/src/ForHosts.dox
- doc/src/Glossary.dox
- doc/src/Thumbnails.dox
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/test/manager/apiComplianceSuite.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
- resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
- tests/openassetio/test/manager/resources/plugins/StubManager.py
Closes #280.
Sorry if I've missed anything, too many meetings these days!
NB: This assumes #305 is merged imminently, and defines trait sets as a `set` not `list`/`tuple`.
> [Core] Migrate `managementPolicy` to use trait sets

- .gitignore
As these are created by README instructed steps, it helps make the default dev experience less chaotic.
> [Lint] Add other build artifacts to `.gitignore`

- src/openassetio-python/CMakeLists.txt
Running ctest on an existing and previously built and run codebase
checkout fails if there is no internet connection because pip will
attempt to look online for the packages. The pip documentation
recommends caching the archives locally and then referring to them in
the install step:
https://pip.pypa.io/en/stable/user_guide/#installing-from-local-packages
For unknown reasons setuptools and wheel are not archived
automatically, so I had to manually store them in an additional step.
The archives are stored in BUILD/downloads.
Closes #300
Signed-off-by: Raihan Kibria <raihan.kibria@foundry.com>
> [Build] Cache test requirements locally

- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/openassetio/hostAPI/test_manager.py
Updates the signature for `getRelatedReferences` to take a set of trait IDs rather than a `Specification`. This removes the ambiguity around whether or not the method should consider the properties of the traits vs their identifiers.
This argument is meant to indicate the "type" of entities returned, trait properties form the data of a specific entity.
Closes https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/282.
NB: This assumes #305 is merged imminently, and defines trait sets as a `set` not `list`/`tuple`.
> [Core] Migrate `getRelatedReferences` to use trait sets

- .github/workflows/build-instructions.yml
Ensures the steps listed in README.md work. Ideally we'd be grabbing this from the file itself, but this is progress...
This does add some time to the CI check suite though 😞 but given we list these instructions in the top-level readme, and compliance with the reference platform is critical, we need to make sure local dev doesn't diverge.
A failing run is available [here](https://github.com/foundrytom/OpenAssetIO/runs/5867268090?check_suite_focus=true) to show errors in the command are reported.
It could be said that this should be part of the `Test` check, but ideally this would be a "check the steps in the documentation work" PR...
> [CI] Add check to ensure ASWF docker builds work

- contributing/C_API.md
Closes #293. A sketch was proposed in #310. This PR extracts the markdown portion of that sketch as a document that
contributers can review to understand our C API strategy.
The markdown doc in #310 has been reworded a little, and the _Opaque handles_ section has been expanded to list alternative schemes.
> [Docs] Add doc for basic C API design choices

- BUILDING.md
- tests/python/openassetio/test/manager/resources/plugins/StubManager.py
> [Doc] Fix `pip` `requirements.txt` path in build instructions

- doc/src/Examples.dox
- doc/src/Thumbnails.dox
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/python/openassetio/hostAPI/test_manager.py
Updates the signature for `preflight` to take a set of trait IDs rather than a `Specification`. This removes the ambiguity around whether or not the method should consider the properties of the traits vs their identifiers.
This argument is meant to indicate the "type" of entities that are about to have their data generated. Supplying the properties for a trait here makes no sense, as that data _is_ the data of the entity, and so the host can't provide it yet, as its not been made!
I think I got all the documentation updates here, but am some what sleepy so let me know if anything has slipped through the cracks!
Closes https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/283.
> [Core] Migrate `preflight` to use trait sets

- .clang-tidy
- CMakeLists.txt
- CPPLINT.cfg
- cmake/StaticAnalyzers.cmake
- src/CPPLINT.cfg
- tests/openassetio-core-c/private/errorsTest.cpp
- tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
Now that we have C/C++ tests, we need to add the `tests` directory to the linter search paths.
> [Lint] Lint C/C++ test directory

- python/openassetio/hostAPI/Manager.py
- tests/python/openassetio/hostAPI/test_manager.py
Closes #328.
This is a follow up PR to #327, so ignore anything other than [this commit](https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/329/commits/a7f8ba6b78f453b68315e96f24e53d01cbf50415) until it is merged.
> [Core] Validate specification trait sets passed to `register`

- src/openassetio-core-c/CMakeLists.txt
- src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
- src/openassetio-core-c/include/openassetio/c/errors.h
- src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
- src/openassetio-core-c/private/InfoDictionary.cpp
- src/openassetio-core-c/private/errors.hpp
- src/openassetio-core-c/private/handles.hpp
- src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
- src/openassetio-core/include/openassetio/InfoDictionary.hpp
- src/openassetio-core/include/openassetio/specification/Specification.hpp
- src/openassetio-core/include/openassetio/trait/BlobTrait.hpp
- src/openassetio-core/include/openassetio/trait/property.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-core/trait/BlobTrait.cpp
- src/openassetio-python/trait/BlobTraitBinding.cpp
- tests/openassetio-core-c/CMakeLists.txt
- tests/openassetio-core-c/private/InfoDictionaryTest.cpp
- tests/openassetio-core-c/private/errorsTest.cpp
- tests/openassetio-core-c/private/handlesTest.cpp
- tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
Part of #290. 
~We may want to think of a better name than `InfoDictionary`.~
Future PRs will expand the C API to include:
* Creating a new `InfoDictionary`from the C API (currently only pre-existing C++ `InfoDictionary`s can be converted).
* Querying the value type of an entry.
* Iteration through entries.
* Writing (insert/update) entries.
> [Core] Add InfoDictionary type(def) with initial C API

- src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
- src/openassetio-core-c/private/InfoDictionary.cpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- tests/openassetio-core-c/private/InfoDictionaryTest.cpp
Part of https://github.com/TheFoundryVisionmongers/OpenAssetIO/issues/290. 
Add introspection functions allowing 
* The number of entries currently in the container.
* The type of an existing entry to be queried, so that the correct accessor function can be chosen.
> [Core] C API InfoDictionary basic introspection

- doc/src/Examples.dox
- python/openassetio/hostAPI/ManagerFactoryInterface.py
- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/pluginSystem/PluginSystemManagerFactory.py
- src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
- src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
- src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
- src/openassetio-core-c/private/managerAPI/CManagerInterface.hpp
- src/openassetio-core/include/openassetio/InfoDictionary.hpp
- src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
- src/openassetio-core/managerAPI/ManagerInterface.cpp
- src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp
- tests/openassetio-core-c/private/managerAPI/CManagerInterfaceTest.cpp
- tests/python/openassetio/managerAPI/test_managerinterface.py
Closes #290. Migrate `info` method from Python to C++ with Python binding, and add its C API.
> [Core] Migrate `ManagerInterface` `info` method to C++

- .github/workflows/build-instructions.yml
- CMakeLists.txt
- README.md
- src/openassetio-python/CMakeLists.txt
As tests require extra build-time dependencies (Catch2, Trompeloeil), it limits the use of some off-the-shelf build environments such as the ASWF docker containers. Moving the venv build outside of the test-only target set allows these environments to be used to produce a working deployment without the test dependencies.
For consumers of OpenAssetIO, this is helpful, as they are most likely using a sanctioned tag/release and so don't need to test the API itself.
This will also facilitate interim CI for the `otio-openassetio` plugin.
> [Build] Allow python venv build without tests

- pyproject.toml
- python/openassetio/__init__.py
- python/openassetio/hostAPI/Manager.py
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/hostAPI/Manager.cpp
- src/openassetio-core/include/openassetio/hostAPI/Manager.hpp
- src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-python/CMakeLists.txt
- src/openassetio-python/_openassetio.cpp
- src/openassetio-python/_openassetio.hpp
- src/openassetio-python/hostAPI/ManagerBinding.cpp
- tests/python/conftest.py
- tests/python/openassetio/hostAPI/test_manager.py
- tests/python/openassetio/hostAPI/test_session.py
- tests/python/openassetio/hostAPI/test_terminology.py
- tests/python/openassetio/hostAPI/test_transactions.py
Closes #345. Migrate `Manager`'s `identifier`, `displayName` and `info` methods from Python to C++ and add Python bindings. Wrangle tests to work with the enhanced type checking caused by this.
> [Core] Minimal Manager C++ implementation

- cmake/DefaultTargetProperties.cmake
- src/openassetio-python/CMakeLists.txt
- tests/openassetio-core-c/CMakeLists.txt
This is incomplete, but gets basic tests running on macOS. The asan section still needs some work along with figuring out our deployment target.
Set up so RPATH uses `@loader_path` for libs, and `@executable_path` for the test binaries.
> [Build] Reinstate basic macOS build support

- .editorconfig
- python/openassetio/Trait.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- src/openassetio-core/include/openassetio/specification/Specification.hpp
- src/openassetio-core/include/openassetio/trait/TraitBase.hpp
- src/openassetio-core/specification/Specification.cpp
- src/openassetio-python/specification/SpecificationBinding.cpp
- tests/python/openassetio/test_specification.py
- tests/python/openassetio/test_trait.py
Closes #335.
Assorted tweaks to the `Specification` and `Trait` APIs to make it easier to implement common scenarios.
A couple of variations:
- I left the constructor in that takes a list of traits, as it was used a lot in tests already, and we are building a framework, so its a potentially valid use case in a manager too.
- Happy to change the static `imbueTo` if we can think of a better name to differentiate - having the same names in C++ and Python is generally important where we can.
> [Core] Allow lazy trait population

- contributing/CHANGES.md
- contributing/PROCESS.md
Autogenerated notes have been discussed, but this approach has the pros of:
- Curated, meaningful change documentation.
- Changelog is always in sync with the codebase.
- Release process is simplified.
At the expense of:
- PR Conflicts when many PRs are in flight at once.
> [Docs] Add change log process documentation

- BUILDING.md
- RELEASE_NOTES.md
- cmake/StaticAnalyzers.cmake
> Support un-versioned `clang-tidy`

- .github/workflows/test.yml
Cancelling other runs in the matrix masks whether any given problem is platform specific.
> Disable `fail-fast` for CI

- RELEASE_NOTES.md
- src/openassetio-core-c/include/openassetio/c/InfoDictionary.h
- src/openassetio-core-c/include/openassetio/c/StringView.h
Closes #337. Swap C++ headers for "deprecated" C headers, such that gcc/clang compiles them fine in `c99` mode.
Note that `c99` is the minimum version we can support, since we require `bool` and `int64_t`, which are unavailable in previous C standards.
No tests are included, this is left for #338. As a manual check, assuming
* Working directory is the root of the repository
* Compiler is `clang`
* Build directory is `./cmake-build-debug`
then
```sh
( cd ./src/openassetio-core-c/include/ && find * -name "*.h" | while read f; do echo "#include <$f>"; done ) | clang -c -xc -std=c99 -o /tmp/deleteme.o -Isrc/openassetio-core-c/include -Icmake-build-debug/include -
```
> [Build] Fix C headers to assume C compiler

- .gitignore
CMake user presets can be used to inherit from and override project-level presets on a per-user basis, and hence it is expected not to be overridden by a git checkout.
> [Build] Ignore CMakeUserPresets.json

- .editorconfig
The reason for not doing this before is that some languages may have significant trailing whitespace. In particular, a double trailing whitespace in markdown forces a line break. However, there are better alternatives to achieving the same effect. The amount of trailing whitespace that slips through is far more of a problem.
> [Lint] Default to trim whitespace in .editorconfig

- BUILDING.md
- README.md
> [Docs] Refer to correct default location of `dist`

- RELEASE_NOTES.md
- doc/Doxyfile
- doc/Makefile
- src/openassetio-core-c/include/openassetio/c/namespace.h
- src/openassetio-core-c/private/StringView.hpp
- src/openassetio-core-c/private/errors.hpp
- src/openassetio-core-c/private/handles/Converter.hpp
- src/openassetio-core-c/private/handles/InfoDictionary.hpp
- src/openassetio-core-c/private/handles/hostAPI/Manager.hpp
- src/openassetio-core-c/private/handles/managerAPI/ManagerInterface.hpp
- src/openassetio-core-c/private/managerAPI/CManagerInterface.cpp
- src/openassetio-core-c/private/managerAPI/CManagerInterfaceAdapter.hpp
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/TraitsData.cpp
- src/openassetio-core/hostAPI/Manager.cpp
- src/openassetio-core/include/openassetio/InfoDictionary.hpp
- src/openassetio-core/include/openassetio/TraitsData.hpp
- src/openassetio-core/include/openassetio/hostAPI/Manager.hpp
- src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
- src/openassetio-core/include/openassetio/trait/TraitBase.hpp
- src/openassetio-core/include/openassetio/trait/property.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-core/managerAPI/ManagerInterface.cpp
- src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp
- tests/openassetio-core-c/private/managerAPI/MockManagerInterfaceSuite.hpp
We previously used the major and minor release version components to define the C/C++ symbol namespace. This had the downside that it would change with every minor version, forcing a re-compile even if the ABI had not altered.
There are many cases in which either of these two version components may be bumped without the ABI being affected (python only changes, feature additions, etc.).
The new approach freezes the namespace version to the last major version where the ABI changed (as an ABI break would always require a major release). Hopefully this will avoid the need for recompilation in many situations and reduce the maintenance overhead.
Closes #377
> [Core] Decouple symbol namespace version from release version

- CMakeLists.txt
- RELEASE_NOTES.md
- src/openassetio-python/CMakeLists.txt
Closes #407. Add `OPENASSETIO_PYTHON_PIP_TIMEOUT` CMake cache variable to allow customising `pip install` socket timeout. We had issues with hardcoding the value to 1 second as being insufficient for some CI runs. So instead default to pip's own 15 sec default and allow overriding for those who wish to work offline.
> [Build] `OPENASSETIO_PYTHON_PIP_TIMEOUT` CMake option

- src/openassetio-python/TraitsDataBinding.cpp
- src/openassetio-python/_openassetio.hpp
- src/openassetio-python/hostAPI/HostInterfaceBinding.cpp
- src/openassetio-python/managerAPI/HostBinding.cpp
- src/openassetio-python/managerAPI/ManagerInterfaceBinding.cpp
We added this abstraction to facilitate easier refactoring later on. In use though, it hampers readability of binding code, and potentially allows the pybind holder to differ from what ever pointer we use internally, which could have dire side-effects.
Closes #432
> [Python] Remove `Holder<T>` alias for `openassetio::shared_ptr`

- tests/openassetio-core-c/private/managerAPI/MockManagerInterfaceSuite.hpp
Inadvertently had been relying on this file always being included
in another file that already had these.
> [Tests] Fix includes in `MockManagerInterfaceSuite`

- python/openassetio/hostAPI/Manager.py
- src/openassetio-core-c/include/openassetio/c/hostAPI/Manager.h
- src/openassetio-core-c/include/openassetio/c/managerAPI/HostSession.h
- src/openassetio-core-c/private/handles/managerAPI/HostSession.hpp
- src/openassetio-core-c/private/hostAPI/Manager.cpp
- src/openassetio-core/hostAPI/Manager.cpp
- src/openassetio-core/include/openassetio/hostAPI/Manager.hpp
- src/openassetio-python/hostAPI/ManagerBinding.cpp
- tests/openassetio-core-c/private/hostAPI/ManagerTest.cpp
- tests/python/conftest.py
- tests/python/openassetio/hostAPI/test_manager.py
- tests/python/openassetio/hostAPI/test_terminology.py
Closes #447, required for #445.
> Pass `HostSession` to C++ `Manager` during construction

- RELEASE_NOTES.md
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
- tests/python/openassetio/hostAPI/test_manager.py
This commit splits context creation into two discrete methods (similar to how `createState` is split for `ManagerInterface`. Principally as it more clearly expresses intent, and simplifies language bindings as there are no longer any optional/defaulted arguments.
Closes #452
> [Core] Split `Manager.createContext`

- RELEASE_NOTES.md
- doc/src/Glossary.dox
- doc/src/ManagerState.dox
- python/openassetio/hostAPI/Manager.py
- python/openassetio/managerAPI/ManagerInterface.py
- tests/python/conftest.py
- tests/python/openassetio/hostAPI/test_manager.py
Part of #445, renames the various `freeze` and `thaw` methods.
> [Core] Rename context persistence methods

- RELEASE_NOTES.md
- python/openassetio/hostAPI/Manager.py
- python/openassetio/test/manager/apiComplianceSuite.py
- tests/python/openassetio/hostAPI/test_manager.py
A draft PR (dependent on #467) for review of a more refined approach to context creation, that means we can make the `ManagerInterface` methods easier to implement
Changes start at [this commit](https://github.com/OpenAssetIO/OpenAssetIO/pull/469/commits/a5c83f81ca46487b57f9b1490b9de85488440e55).
> [Core] Refine context creation mechanism

- .github/workflows/test.yml
`pybind` is no longer available for mac in conan center.
See:
https://github.com/conan-io/conan-center-index/pull/11075
https://github.com/pybind/pybind11/issues/3081
> [CI] Temporarily disable macOS CI due to pybind issue

- RELEASE_NOTES.md
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/bal.py
- resources/examples/manager/BasicAssetLibrary/schema.json
- resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
- resources/examples/manager/BasicAssetLibrary/tests/resources/library_business_logic_suite_customManagementPolicy.json
Adds the ability to customize the `managementPolicy` response returned by BAL. Amended defaults, or trait set specific policies can be supplied using new keys in the library JSON file.
We decided to keep-it-simple for now, and just have the JSON hold the raw policy value. Its a little opaque, but we can revisit this when we have more use cases.
NB: This also follows the "BAL style" of "slightly rough and ready programming".
Closes #459
> [Examples] Support custom `managementPolicy` responses in BAL

- doc/src/EntitiesTraitsSpecifications.dox
- doc/src/Examples.dox
- doc/src/ForHosts.dox
- doc/src/ForManagers.dox
- doc/src/Glossary.dox
- doc/src/MainPage.dox
- doc/src/ManagerState.dox
- doc/src/Testing.dox
- python/openassetio/Trait.py
- python/openassetio/hostAPI/Manager.py
- python/openassetio/hostAPI/ManagerFactoryInterface.py
- python/openassetio/hostAPI/Session.py
- python/openassetio/hostAPI/__init__.py
- python/openassetio/managerAPI/HostSession.py
- python/openassetio/managerAPI/ManagerInterface.py
- python/openassetio/pluginSystem/PluginSystemManagerFactory.py
- python/openassetio/test/manager/_implementation.py
- src/openassetio-core-c/include/openassetio/c/hostAPI/Manager.h
- src/openassetio-core-c/include/openassetio/c/managerAPI/CManagerInterface.h
- src/openassetio-core-c/include/openassetio/c/managerAPI/HostSession.h
- src/openassetio-core-c/include/openassetio/c/managerAPI/ManagerInterface.h
- src/openassetio-core/include/openassetio/InfoDictionary.hpp
- src/openassetio-core/include/openassetio/managerAPI/Host.hpp
- src/openassetio-core/include/openassetio/managerAPI/HostSession.hpp
- src/openassetio-core/include/openassetio/managerAPI/ManagerInterface.hpp
We had a mix of . and :: use when invoking the custom Doxygen command 'fqref.' Both work, but we elected to use . as the documentation is used for multiple languages.
Closes #472
> [Docs] Conform use of `fqref`

- contributing/CODING_STANDARDS.md
- resources/perftest/perftest.cpp
- src/openassetio-core/hostApi/Manager.cpp
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/include/openassetio/TraitsData.hpp
- src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/Host.hpp
- src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerStateBase.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-python/ContextBinding.cpp
- src/openassetio-python/hostApi/ManagerBinding.cpp
- src/openassetio-python/managerApi/HostBinding.cpp
Closes #446. 
Best practice in C++ is to forward declare types where possible, to reduce compilation time as well as reliance on transient
`#include`s that tightly couple units of code together. 
To keep this DRY, add macros that forward declare classes and their associated smart pointer wrappers (currently just `shared_ptr`). Then use these macros across C++ headers.
> [Core] Add and use forward declaration macros

- src/openassetio-core/include/openassetio/typedefs.hpp
For const-correctness we should try to use pointer-to-const where possible. Hence add a `const` variant to our `shared_ptr` forward declaration macro(s). This will be used in subsequent C++ migrations.
> [Core] Forward declare shared_ptr-to-const aliases

- RELEASE_NOTES.md
- contributing/CODING_STANDARDS.md
- resources/perftest/lib.cpp
- resources/perftest/perftest.cpp
- src/openassetio-core-c/private/hostApi/Manager.cpp
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/Context.cpp
- src/openassetio-core/TraitsData.cpp
- src/openassetio-core/hostApi/Manager.cpp
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/include/openassetio/TraitsData.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/Host.hpp
- src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-core/managerApi/Host.cpp
- src/openassetio-core/managerApi/HostSession.cpp
- src/openassetio-python/ContextBinding.cpp
- src/openassetio-python/TraitsDataBinding.cpp
- src/openassetio-python/hostApi/ManagerBinding.cpp
- src/openassetio-python/managerApi/HostBinding.cpp
- src/openassetio-python/managerApi/HostSessionBinding.cpp
- tests/openassetio-core-c/private/hostApi/ManagerTest.cpp
- tests/openassetio-core/CMakeLists.txt
- tests/openassetio-core/ContextTest.cpp
- tests/openassetio-core/TraitsDataTest.cpp
- tests/openassetio-core/hostApi/ManagerTest.cpp
- tests/openassetio-core/managerApi/HostSessionTest.cpp
- tests/openassetio-core/managerApi/HostTest.cpp
- tests/openassetio-core/trait/TraitBaseTest.cpp
This deliberately omits classes that are not constructed by API code, or callers of the API (from either side). `HostInterface`, `ManagerInterface` and `ManagerStateBase` are only ever constructed by their direct owners (the host, the manager's plugin and manager respectively).
Closes #481
> C++ Factory methods

- RELEASE_NOTES.md
- python/openassetio/_core/debug.py
- python/openassetio/log.py
- python/openassetio/managerApi/HostSession.py
- python/openassetio/managerApi/ManagerInterface.py
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/LoggerInterface.cpp
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/include/openassetio/LoggerInterface.hpp
- src/openassetio-core/include/openassetio/enum.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-python/CMakeLists.txt
- src/openassetio-python/LoggerInterfaceBinding.cpp
- src/openassetio-python/_openassetio.cpp
- src/openassetio-python/_openassetio.hpp
- tests/python/openassetio/managerApi/test_hostsession.py
- tests/python/openassetio/test_log.py
Closes #504.
Migrate the `LoggerInterface` to C++ with Python bindings., removing `LoggerInterface.progress()` along the way.
This will then enable future work to fully migrate `HostSession` and `ManagerFactoryInterface` C++ without requiring Python wrappers.
Testing is a little minimal. We currently have no (Python->)C++->Python `log()` calls.  Once `HostSession` is migrated to C++, its Python tests will implicitly include a round-trip of `log()` through C++.
> [Core] Minimal C++ logging interface

- RELEASE_NOTES.md
- doc/src/Examples.dox
- doc/src/ForHosts.dox
- python/openassetio/hostApi/ManagerInterfaceFactoryInterface.py
- python/openassetio/hostApi/Session.py
- python/openassetio/hostApi/__init__.py
- python/openassetio/pluginSystem/ManagerPlugin.py
- python/openassetio/pluginSystem/PluginSystemManagerInterfaceFactory.py
- python/openassetio/pluginSystem/__init__.py
- python/openassetio/test/manager/_implementation.py
- tests/python/openassetio/hostApi/test_session.py
- tests/python/openassetio/pluginSystem/test_pluginsystemmanagerinterfacefactory.py
- tests/python/openassetio/test/manager/conftest.py
- tests/python/openassetio/test_imports.py
Closes #506.  Renames both `ManagerFactoryInterface` as well as the subclass `PluginSystemManagerFactory` to `ManagerInterfaceFactoryInterface` and `PluginSystemManagerInterfaceFactory`, respectively.
> [Core] Rename `ManagerFactoryInterface`

- src/openassetio-python/CMakeLists.txt
Part of #395. We run Python unit tests against a full install of OpenAssetIO, for better dogfooding. The time taken by this install
significantly slows the TDD feedback loop. Any time we can shave off this will improve dev efficiency.
So reduce the time taken to "build" our pure Python package by avoiding use of temporary build directories. This also removes the need to download/upgrade `setuptools` and `pip`, shaving a little more time. However, it does necessitate installing `wheel` into the venv.
> [Build] Reduce Python install time for tests

- RELEASE_NOTES.md
- python/openassetio/log.py
- python/openassetio/managerApi/HostSession.py
- python/openassetio/pluginSystem/PluginSystem.py
- python/openassetio/pluginSystem/PluginSystemManagerImplementationFactory.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- src/openassetio-core/include/openassetio/LoggerInterface.hpp
- src/openassetio-python/LoggerInterfaceBinding.cpp
- tests/python/conftest.py
- tests/python/openassetio/managerApi/test_hostsession.py
- tests/python/openassetio/pluginSystem/test_pluginsystemmanagerimplementationfactory.py
- tests/python/openassetio/test_log.py
The existing order was the reverse of most common logging libraries. Swap for familiarity.
Part of #531.
> [Core] Swap `LoggerInterface::log` arguments

- resources/build/bootstrap-ubuntu-20.04.sh
- resources/build/requirements.txt
Due to a new [`xorg/system` recipe](https://conan.io/center/xorg?version=system&revision=7c176593b897dc32de475df95d7e506c&tab=recipe), which the cpython recipe depends on, the `conan install` step on CI (and Vagrant) fails attempting to install system packages (i.e. `apt` packages).
This failure only occurred recently due to our GitHub CI cache being busted (a separate mystery).
The primary cause of the failure is because the `xorg/system` recipe has been refactored and will now always try to install the latest version of system packages, even if they are already available.
The default conan mode in this case is to only "check" if packages are installed and throw an error if they're not found (the alternative behaviour being to "install" if not found). 
However, this has a bug (reported …
> [Tests] Fix conan install of cpython

- RELEASE_NOTES.md
- python/openassetio/log.py
- src/openassetio-core/include/openassetio/LoggerInterface.hpp
- tests/python/openassetio/test/manager/test_main.py
- tests/python/openassetio/test_log.py
Reverses the order of logging severity constants, such that a logically higher severity now has a higher associated numeric value.
Closes #516
> [Core] Invert log severity constant order

- decisions/DR011-Entity-reference-type-safety.md
- decisions/DR012-Entity-reference-validation-workflow.md
Closes #532.
Add two decision records. Firstly decide on and justify the type-safety of entity references, with respect to the entity reference string validation workflow. Secondly, decide on and justify the host API  for the validation workflow, assuming strongly typed entity references will be used.
> [Docs] Decision records for entity reference validation workflow

- RELEASE_NOTES.md
- decisions/DR011-Entity-reference-type-safety.md
- decisions/DR012-Entity-reference-validation-workflow.md
- doc/src/Examples.dox
- doc/src/ForHosts.dox
- doc/src/Glossary.dox
- doc/src/Testing.dox
- python/openassetio/constants.py
- python/openassetio/hostApi/Manager.py
- python/openassetio/managerApi/ManagerInterface.py
- python/openassetio/test/manager/apiComplianceSuite.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- resources/examples/manager/SampleAssetManager/python/SampleAssetManager/SampleAssetManagerInterface.py
- src/openassetio-core/include/openassetio/EntityReference.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- tests/python/conftest.py
- tests/python/openassetio/hostApi/test_manager.py
Part of #549, refactors `isEntityReference` to the non-batch `isEntityReferenceString`, see the individual commit messages for more details.
> `isEntityReference` refactor

- RELEASE_NOTES.md
- doc/src/ForHosts.dox
- doc/src/Glossary.dox
- doc/src/Testing.dox
- python/openassetio/hostApi/Manager.py
- python/openassetio/managerApi/ManagerInterface.py
- src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.cpp
- src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.hpp
- src/openassetio-core/hostApi/Manager.cpp
- src/openassetio-core/include/openassetio/EntityReference.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-python/module/hostApi/ManagerBinding.cpp
- src/openassetio-python/module/managerApi/ManagerInterfaceBinding.cpp
- tests/openassetio-core-c/private/hostApi/ManagerTest.cpp
- tests/python/openassetio/hostApi/test_manager.py
Part of #549. In order for a C++ host to use an entity reference string as a parameter to manager API methods, the host is required to validate that it is relevant to the target manager.
Currently, this is expected to be an explicit validation by the host application, but in upcoming work this will also be performed by entity reference factory functions.
So as a prerequisite step toward C++ migration of manager API methods that use entity references, migrate `isEntityReferenceString` to C++, so that entity reference strings can be validated before use.
> [Core] Migrate `isEntityReferenceString` to C++

- RELEASE_NOTES.md
- src/openassetio-core/hostApi/Manager.cpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-python/module/hostApi/ManagerBinding.cpp
- tests/python/openassetio/hostApi/test_manager.py
Part of #549. Added the `createEntityReference` method to C++ and Python, which should always be used to create `EntityReference` objects.
The method will validate that the provided entity reference string is relevant to the manager and throw a `std::domain_error` if it isn't (exception type to be migrated to a custom type in future work).
> [Core] Add `Manager.createEntityReference`

- RELEASE_NOTES.md
- doc/src/Examples.dox
- python/openassetio/exceptions.py
- python/openassetio/hostApi/Manager.py
- python/openassetio/managerApi/ManagerInterface.py
- python/openassetio/test/manager/apiComplianceSuite.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- resources/examples/manager/BasicAssetLibrary/tests/bal_business_logic_suite.py
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- tests/python/conftest.py
- tests/python/openassetio/hostApi/test_manager.py
Update tests and docs to use `EntityReference` object workflows.
Since most of the implementation is still in weakly-typed Python, there isn't much in the way of core code changes.
Though I can't help the nagging feeling I've missed something :thinking:
> [Core] Update Manager to expect EntityReference

- python/openassetio/__init__.py
- src/openassetio-core-c/include/openassetio/c/errors.h
- src/openassetio-core/include/openassetio/BatchElementError.hpp
- src/openassetio-core/include/openassetio/errors.h
- src/openassetio-python/module/BatchElementErrorBinding.cpp
- src/openassetio-python/module/CMakeLists.txt
- src/openassetio-python/module/_openassetio.cpp
- src/openassetio-python/module/_openassetio.hpp
- tests/openassetio-core/BatchElementErrorTest.cpp
- tests/openassetio-core/CMakeLists.txt
- tests/python/openassetio/test_batchelementerror.py
Closes #557.
Add a simple `BatchElementError` aggregate class, initially containing just an error code and string message. The error code is a strongly typed enumeration, currently only supporting a fallback code of `kUnknown`.
To prevent ambiguity of these error codes with the C API's exception error codes, and to allow reuse of the error codes between C++ and C, add a new C-compatible header the core library, with `#define`s computing the new error codes as offset from the C API's exception error codes.
> [Core] Add BatchElementError

- RELEASE_NOTES.md
- python/openassetio/hostApi/Manager.py
- python/openassetio/managerApi/ManagerInterface.py
- tests/python/conftest.py
- tests/python/openassetio/hostApi/test_manager.py
Removes the `prefetch` method as the new batch-first architecture makes this redundant.
Closes #511
> [Core] Remove `Manager.prefetch`

- python/openassetio/hostApi/Manager.py
- python/openassetio/pluginSystem/PythonPluginSystemManagerPlugin.py
- src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/Host.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
Conforms the use of reverse-dns style identifiers in examples.
Closes #59.
> [Docs] Ensure consistent use of reverse-dns identifiers

- resources/build/requirements.txt
Github CI error:
> ERROR: freetype/2.12.1: Cannot load recipe.
>  Error loading conanfile at
> '/home/runner/conan/.conan/data/freetype/2.12.1/_/_/export/conanfile.py':
> Current Conan version (1.50.0) does not satisfy the defined> one
> (>=1.50.2).
> [CI] Bump conan version

- resources/perftest/perftest.cpp
- src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.cpp
- src/openassetio-core-c/private/managerApi/CManagerInterfaceAdapter.hpp
- src/openassetio-core/hostApi/Manager.cpp
- src/openassetio-core/include/openassetio/BatchElementError.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-core/log/SeverityFilter.cpp
- src/openassetio-core/managerApi/ManagerInterface.cpp
- src/openassetio-python/module/hostApi/ManagerFactoryBinding.cpp
- src/openassetio-python/module/managerApi/ManagerInterfaceBinding.cpp
- tests/openassetio-core-c/private/managerApi/CManagerInterfaceAdapterTest.cpp
- tests/openassetio-core/BatchElementErrorTest.cpp
We may opt to remove aliases for primitive types in future (see https://github.com/OpenAssetIO/OpenAssetIO/issues/572). In the meantime, we should at least be consistent in our usage.
So update the errant usages of `std::string` to instead use `openassetio::Str`.
> [Core] Use Str typedef alias throughout

- tests/python/openassetio/hostApi/test_manager.py
Inspired by #582, where we inadvertently neglected to delete the Python implementation when migrating to C++.
Attempts to ensure that the method is implemented in the expected language during the Python -> C++ transition. The approach is slightly tenuous, but seem to work ok.
Methods like `getsource` could also be used, but ultimately, they raise a `TypeError` if the supplied object isn't a function... so this seems msimpler to invoke/manager.
> [Tests] Add checks for source of `Manager` implementation

- RELEASE_NOTES.md
- python/openassetio/test/manager/apiComplianceSuite.py
- resources/examples/manager/BasicAssetLibrary/plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
- src/openassetio-core/include/openassetio/BatchElementError.hpp
- src/openassetio-core/include/openassetio/errors.h
- src/openassetio-python/module/BatchElementErrorBinding.cpp
- tests/python/openassetio/test_batchelementerror.py
As part of #587, we need to properly define the API behaviour when calling `preflight` or `register` for an un-versionable, immutable entity.  This required a new error code. Rather than tying this to the specific method, this adds `kEntityAccessError`, that can be used in all cases where the access is the sole cause of error.
As this also applies to `resolve`, updates the `apiComplianceSuite` to check for this too (and consequently updates BAL to be compliant).
> [Core] Add `kEntityAccessError` to `BatchElementError`

- RELEASE_NOTES.md
- python/openassetio/hostApi/Manager.py
- python/openassetio/managerApi/ManagerInterface.py
- python/openassetio/test/manager/apiComplianceSuite.py
- tests/python/conftest.py
- tests/python/openassetio/hostApi/test_manager.py
- tests/python/openassetio/managerApi/test_managerinterface.py
Closes #587.
Whilst looking at the doc-update aspect of this, I noticed that we didn't update the examples for `resolve` when we did #571, so have added #592 to cover this more holistically.
Takes the opportunity to expand test coverage to (attempt) to capture the required behaviour of a manager when transitioning to callbacks.
> [Core] Migrate `preflight`/`register` to callbacks

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/managerApi/ManagerInterface.cpp
- src/openassetio-python/module/managerApi/ManagerInterfaceBinding.cpp
- tests/python/openassetio/managerApi/test_managerinterface.py
In #549, we added a 'strongly typed' entity reference workflow. This required hosts to ensure that strings are validated through the manager before being used as an entity reference. This ensures that once initial checks have been completed, manager implementations no longer need to worry about re-checking method inputs to see if they are one of their references.
We plan on adding assorted validation checks in the API middleware that will help avoid coding errors when multiple managers are in use.
This raises the question of how should a manager implementation create these strongly typed objects - where it doesn't need the validation?
We wanted to avoid direct construction of `EntityReference` objects on the stack by code so that we can evolve the manager validation aspect with minimal …
> [Core] Add `ManagerInterface._createEntityReference`

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
`TraitsDataConstPtr` is currently unsupported by (C++) trait views, which require a pointer-to-non-const currently. This will change when we tackle autogeneration of C++ traits.
In the meantime, fix the `resolve` callback signature to take a `TraitsDataPtr`, so that trait views can be utilised in the callback
implementation.
> [Core] Ensure `resolve` callback implementation can use trait views on the provided trait data

- tests/python/conftest.py
- tests/python/openassetio/hostApi/test_manager.py
- tests/python/openassetio/managerApi/test_managerinterface.py
Add test for robustness against forgetful developers migrating Python methods to C++ then leaving the old Python implementation around, masking the new C++ implementation.
I.e. ensure the `Manager` Python class hierarchy only has a single implementation of each method.
> [Tests] Assert Manager methods implemented once

- .github/workflows/code-quality.yml
- .github/workflows/test.yml
Part of #484. A no-brainer to speed up builds is to enable parallel compilation.
Using the Ninja generator for CMake gives us this automatically, scaling to the number of CPUs available on the build host. Github CI gives each runner two CPUs.
We don't get a linear improvement, and the improvement is not as great  as running locally (vCPU vs. real CPU, perhaps), but it's still a quick win that shaves a good 20% off the build time.
> [CI] Use Ninja CMake generator

- RELEASE_NOTES.md
- src/openassetio-python/module/PyRetainingSharedPtr.hpp
- tests/openassetio-python/PyRetainingSharedPtrTest.cpp
- tests/python/openassetio_test/test_PyRetainingSharedPtr.py
Discovered during work on #608
`RetainPyArgs` is a utility to decorate C++ functions such that certain `shared_ptr` arguments are swapped out for equivalent `PyRetainingSharedPtr` arguments. These decorated functions are then used for Python bindings in lieu of the original functions. A custom Pybind type caster then detects `PyRetainingSharedPtr` arguments and ensures any associated Python objects are not destroyed prematurely.
The `RetainPyArgs` helper was using strict type matching when comparing function arguments against its `PtrsToPyRetain` (`shared_ptr`) list. This meant, for example, that a `const shared_ptr<SomeType>&` argument would not match because of the const reference qualifiers.
The decorated function returned from `RetainPyArgs::decorator` would then be missing the …
> [Core] Fix `RetainPyArgs` for const ref args

- .github/workflows/code-quality.yml
- .github/workflows/test.yml
- resources/build/bootstrap-ubuntu-20.04.sh
Closes #613. `ccache` can save us ~30-50% in build step times for the C++ linter and sanitizer CI jobs.
Use the `restore-keys` trick to simulate updating a Github `actions/cache` cache, which is technically immutable. I.e. restore the most recently used cache by giving a prefix match to `restore-keys`, and generate a whole new cache to save any updates by giving the prefix plus run id (i.e. a unique key per run) as the `key`.
This will rapidly fill our cache quota, but the Github cache evicts based on least-recently used cache keys, which works for this use case.
> [CI] Add ccache to speed up linter/sanitizer build

- doc/src/Examples.dox
- resources/examples/manager/BasicAssetLibrary/tests/test_bal.py
- resources/examples/manager/SampleAssetManager/tests/test_sam_apiCompliance.py
@antirotor spotted a few uses of "legacy terminology"... and highlighted some ambiguity around manager tests.
> Misc Docs fixes

- RELEASE_NOTES.md
- doc/Doxyfile
- python/openassetio/exceptions.py
- python/openassetio/hostApi/Manager.py
- python/openassetio/hostApi/terminology.py
- python/openassetio/managerApi/ManagerInterface.py
Closes #600 
Add an @unstable doxygen alias, which warns that a method/function has not yet been ported to C++ and is liable to change. Adds this tag to all as-yet-unported methods/classes in the python api.
> Unstable warning on non-ported python functionality

- RELEASE_NOTES.md
- resources/examples/host/simpleResolver/README.md
- resources/examples/host/simpleResolver/bal_animals.json
- resources/examples/host/simpleResolver/bal_animals_openassetio_config.toml
- resources/examples/host/simpleResolver/simpleResolver.py
- resources/examples/host/simpleResolver/test_simpleResolver.py
Adds a very simple CLI host, that resolves the supplied entity reference for the given trait set. The resulting data is written to stdout as JSON.
This was a sprint demo, but since the addition of the OPENASSETIO_DEFAULT_CONFIG mechanism in #608, it's generally a lot more useful to the wider world.
> [Examples] Add `simpleResolver` CLI host example

- resources/examples/host/simpleResolver/README.md
This was inadvertently lost in a PR revision edit to the copy. It has been proven useful to highlight these things in the past.
> [Examples] Add note on runtime requirements to `simpleResolver.py` docs

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/log/LoggerInterface.hpp
- src/openassetio-core/log/LoggerInterface.cpp
- src/openassetio-python/module/log/LoggerInterfaceBinding.cpp
- tests/python/openassetio/test_log.py
The severity + message signature of `LoggerInterface::log` becomes somewhat verbose in regular use. We want to encourage implementations to make good use of `debug` and similar, these conveniences hopefully reduce to overhead of adding "useful logging".
@elliotcmorris @feltech Let me know if there are better/more performant ways of implementing this, went for the "simple" option in my aged brain.
> [Core] Add logging convenience methods

- .github/bootstrap_platform/action.yml
- .github/workflows/build-instructions.yml
- .github/workflows/build-wheels.yml
- .github/workflows/code-quality.yml
- .github/workflows/test.yml
- BUILDING.md
- RELEASE_NOTES.md
- pyproject.toml
- resources/build/bootstrap-cibuildwheel-manylinux-2014.sh
- resources/build/bootstrap-macos-10.15.sh
- resources/build/bootstrap-ubuntu-20.04.sh
- resources/build/bootstrap-windows-2019.bat
- resources/build/conanfile.py
Add workflow that invokes `cibuildwheel` to build a set of python wheels upon push to main branch (or manual invocation)
Prerequisite for having an automated PyPI release pipeline, but useful in its own right. Will archive built wheels into github storage for later retrieval.
Currently, we create 4 wheels, win-x86_64-python3.9, win-x86_64-python3.10, manylinux-x86_64-python3.9, manylinux-x86_64-python3.10
---
It's worth noting that `cibuildwheel` has a very different paradigm when building on linux platforms vs mac and windows. On linux platforms, a docker container is invoked, (using the `manylinux` images,) whereas on windows and mac, a virtual environment is configured directly inside the existing environment.
This is the reason you'll see a new bootstrapping script, as we need to …
> Package wheels CI workflow

- .github/workflows/deploy-pypi.yml
Closes #653 
Release workflow for uploading to pypi, including verification tests.
Runs upon a release being created, or upon being manually triggered.
Above release run was done prior to this PR. (I had the changeset on main at the time to most fully replicate the expected environment.) Notice that the real pyPI upload fails, the reason for this being that this fork intentionally dosen't have the real pyPI secret on it.
Putting this up as a draft as there's a few things I want to run by some folks and perhaps change, and seeing the source is helpful. Although it's not really a lot of code anyway...
---
**1.** Python Venvs. We discussed doing the testing in a virtual environment, but i'm really not sure if it's necessary in this formulation. As the testing is done in a dependent job, one …
> PyPI Release Process

- .github/workflows/build-instructions.yml
- .github/workflows/build-wheels.yml
- .github/workflows/test.yml
- CMakeLists.txt
- resources/build/bootstrap-macos-11.sh
The issue was that 11 comes with Clang 13, for which there are no re-built packages on Conan. This adds `automake` tools so that Conan can build them locally. They should then be cached so hopefully this won't impact normal CI run times.
> Bump CI runners to macOS-11

- .github/dependabot.yml
Actions deprecation warnings only show up in the detailed logs for an action, so are easily missed.
Part of #668.
Im not entirely sure how best to test this!
Notes: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> [CI] Enable Dependabot tracking of GitHub Action versions

- .github/workflows/populate-cache.yml
This should hopefully allow us to populate the actions cache to speed up first-runs on PRs. These are currently very slow, now we have to build certain conan packages on macOS (see #680).
Signed-off-by: Tom Cowland <tom@foundry.com>
Closes #686
> [CI] Populate cache on push to main/feature branches

- .github/workflows/build-instructions.yml
- .github/workflows/build-wheels.yml
- .github/workflows/code-quality.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/commit-checks.yml
- .github/workflows/populate-cache.yml
- .github/workflows/test.yml
This should ensure that we don't waste runners repeatedly running jobs for out-of-date commits.
Anchoring to `github.ref`[1] seems like it should "do the right thing" so they are unique to each PR/etc.
[1] https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
Closes #696 
It can be seen in action [here](https://github.com/foundrytom/OpenAssetIO/actions).
> [CI] Set concurrency groups for CI jobs

- .github/bootstrap_platform/action.yml
- .github/workflows/code-quality.yml
- .github/workflows/test.yml
Avoids assorted deprecations. For some reason Dependabot didn't spot these. Hopefully this will remove the remaining warnings on CI runs.
> [CI] Update action versions

- .github/workflows/build-instructions.yml
- BUILDING.md
- README.md
Closes #624 
Updates Building.md to contain the new build instructions following the pip work, and attempts to refresh the entire document to be clearer and more cohesive.
Rendered version of the new doc [here](https://github.com/OpenAssetIO/OpenAssetIO/blob/a6c3c6d6bc11b4abe477f765b3086eeefca3649c/BUILDING.md).
> Update Building.md with new build instructions.

- .github/workflows/integrations.yml
Corresponding changes on test repo: https://github.com/OpenAssetIO/OpenAssetIO-Test-CMake/pull/4
Closes [#714](https://github.com/OpenAssetIO/OpenAssetIO/issues/714)
> [CI] Add `OpenAssetIO-Test-CMake` integration test

- resources/build/conanfile.py
Closes #699. We were using `tool_requires` for all dependencies, but that function establishes a build requirement, rather than a runtime requirement. This has a few implications
* Dependency versions cannot be overridden by `--require-override`.
* Other packages in the same dependency tree will not be forced to have compatible versions of shared dependencies.
* The package hash is unaffected by changes in the dependencies.
The first issue is more immediate, since we now support a range of Python versions, and it is useful to be able to override the Python version for testing.
The latter two are important more in the future, when we submit a package to ConanCenter.
So split out the "runtime" dependencies from `build_requirements` into `requirements`, allowing `--require-override` to work. …
> [Build] Use `requires` rather than `tool_requires` in conanfile.py

- decisions/DR013-Project-structure.md
Fixing up #627. This was merged a little prematurely. Add missing fields, plus an extra whitespace fix to match the template.
> [Docs] Add missing fields to DR 13

- .github/workflows/docs.yml
After merging the project restructure (#740), deployment of generated Doxygen docs failed. So fix the erroneous path.
> [CI] Fix Doxygen docs deployment

- src/openassetio-python/module/src/TraitsDataBinding.cpp
- src/openassetio-python/module/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/module/src/log/SeverityFilterBinding.cpp
- src/openassetio-python/module/src/managerApi/ManagerInterfaceBinding.cpp
Closes #743. Fix class methods in Python bindings to have the same argument names as the C++ member functions they're wrapping, insomuch as that is possible/relevant.
A quick-and-dirty `libclang`-based script was used for the majority of the mismatch detection (see issue). Manual checks were still required for constructors and other Python methods where the script couldn't find a C++ match.  
Any non-method symbols were skimmed over but not checked thoroughly (enums, constants, member variables, etc).
> [Core] Conform Python to C++ method argument names

- RELEASE_NOTES.md
Part of #743. Release notes were missing from the original PR.
> [Docs] Add release notes for Python arg renames

- .github/workflows/git.yml
Closes #746 
Add a small integration that prevents fixup commits being merged.
Only takes 10s or so to run, and only needs to run on the one platform, so not a big CI load.
Note how the fixup before the force push [failed](https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/3533323086/jobs/5928798700), as there was a fixup, and after, they [succeed](https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/3533336591/jobs/5928829222).
Note : One could argue that the DCO checks will also serve to catch fixups, because they tend not to be signed, but i've had this nearly catch me out before, when using the github UI to make fixup commits, which allows signing now, and I guess there's no law written that fixups coming in arn't signed.
> Block fixup merges.

- .github/workflows/integrations.yml
- examples/host/simpleResolver/test_simpleResolver.py
Ensures they will work after https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/11 changes the way tests must be run.
> Update BAL integration tests

- .github/ISSUE_TEMPLATE/issue.md
- .github/PULL_REQUEST_TEMPLATE/pull_request.md
Add minimal issue template and minimal pull request template, as discussed at retro.
The main purpose of the issue template is to include a refinement reminder checklist so we remember to discuss release-notes, docs, and tests when doing planning.
The main purpose of the pull request template is to include a reminder to write notes to make the review easier, as well as notes on how to test your changeset. Also adds a reminder to have a #closes tag
Have attempted to keep these as minimal as possible because it's very easy for these things to become bloated and useless.
I'm not entirely sure the pull-request template justifies its own existence, let me know what you think, it can be annoying deleting non-relevant sections all the time. Conversely, it is nice to have these around though, …
> Add issue/PR template.

- doc/contributing/PROCESS.md
Add docs describing the process to be taken when an openassetio change causes unavoidable breakages in downstream repos, and how to mitigate that.
Since you last saw this, have addressed the few comments made in the early doc. Notably
- Changed the branch formatting to conan style suggested by david.
- Removed the dependent repo unit test retargetting steps, on the assumption that the tests will be setup to run automatically on those branch formats.
- Added a short paragraph to the end explaining motivation and alternatives.
This doc is written from the perspective of the future, when we have done a couple of things to support the process. I've logged an issue about that here : https://github.com/OpenAssetIO/OpenAssetIO/issues/771
> Breaking changes to integrations mitigation process

- .github/workflows/build-wheels.yml
- .github/workflows/deploy-pypi.yml
Avoids PyPI release failing if the wheels haven't built yet.
> [CI] Block PyPI deploy whilst wheels are building

- src/openassetio-python/bridge/include/openassetio/python/hostApi.hpp
Until #797 is properly addressed, add a warning to the Doxygen docs for `createPythonPluginSystemManagerImplementationFactory` that the Python GIL must be acquired before using it.
This is just a temporary fix until we add the code to acquire the GIL in the function.
```
cd docs/Doxygen
make
```
Then view `file:///path/to/OpenAssetIO/doc/doxygen/html/namespaceopenassetio_1_1v1_1_1python_1_1host_api.html`.
> [Docs] Warn GIL required for Python plugin system

- RELEASE_NOTES.md
- src/openassetio-python/bridge/include/openassetio/python/hostApi.hpp
- src/openassetio-python/bridge/src/python/hostApi.cpp
- src/openassetio-python/tests/bridge/python/test_hostApi.cpp
Fixes #797. 
If the host thread does not hold the GIL when `createPythonPluginSystemManagerImplementationFactory` is called, then segfaults abound when trying to `import` the Python plugin system via pybind11.
So ensure the GIL is acquired first. pybind11's `gil_scoped_acquire` is clever enough to restore the state to whatever it was before, upon function exit.
Note that, as described below, this can be tested using OpenAssetIO's CTest suite, so no need for changes to the OpenAssetIO-Test-CMake integration test project to check this fix.
The `openassetio.internal.python-bridge-test` CTest in OpenAssetIO has been updated to trigger the bug.  If you leave that change, but remove the fix, and run CTest, then the segfault (or exception, if in Debug mode) will be apparent.
> [Core] Acquire GIL before C++ imports Python plugin system

- RELEASE_NOTES.md
- src/openassetio-python/private/include/openassetio/private/python/pointers.hpp
- src/openassetio-python/tests/cmodule/CMakeLists.txt
- src/openassetio-python/tests/cmodule/resources/_openassetio_test/PyRetainingSharedPtrTest.cpp
- src/openassetio-python/tests/cmodule/resources/_openassetio_test/_openassetio_test.cpp
- src/openassetio-python/tests/cmodule/test_PyRetainingSharedPtr.py
The `PyRetainingSharedPtr` mechanism in OpenAssetIO allows a C++ `shared_ptr` chain to keep a `PyObject` alive, even if that object is not currently visible from the Python interpreter. This allows e.g. a C++ host to hold a reference to (and call) a Python manager plugin.
A side effect of this mechanism is that it is possible for a C++ object to keep a `PyObject` alive beyond the lifetime of the Python interpreter. Then, when the C++ object is finally destroyed (e.g. on application exit), attempting to clean up the `PyObject` is a use-after-free error, causing segfaults or hangs.
So ensure cleanup of the `PyObject` is trivial, in the case that the Python interpreter has been shut down, by not trying to acquire the GIL and by `release`ing the pybind11 handle.
- ~~[ ] I have updated all …
> [Core] Fix PyObject cleanup if interpreter gone

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/_implementation.py
- src/openassetio-python/package/openassetio/test/manager/harness.py
- src/openassetio-python/tests/package/test/manager/resources/suite_executeSuiteTests.py
- src/openassetio-python/tests/package/test/manager/test__implementation.py
The `openassetio.test.manager` harness used to create a single manager for the entire test run, reusing it for each case. This was mainly for performance reasons.
This does however, preclude the ability to test manager initialization behaviour.
This adds a class variable that instructs the harness to create a new, uninitialized manager for each case instead.
Part of OpenAssetIO/OpenAssetIO-Manager-BAL#26.
Note: I've had a world of a time getting builds working again on my laptop, so hopefully I haven't missed something obvious!
> [Core] Add ability to create a new manager for each harness test case

- .github/workflows/code-quality.yml
- resources/build/bootstrap-cibuildwheel-manylinux-2014.sh
- resources/build/bootstrap-macos-10.15.sh
- resources/build/bootstrap-macos-11.sh
- resources/build/bootstrap-ubuntu-20.04.sh
- resources/build/bootstrap-windows-2019.bat
- resources/build/conanfile.py
- resources/build/requirements.txt
The latest Conan recipe for the `ncurses` dependency of `cpython` is incompatible with Conan V1, so we must pin it.
One of the initial attempted fixes was to upgrade to the latest Conan. This may not actually have been required, but is worth keeping.  This necessitated a slight change in our conanfile.py to no longer use `tool_requires`, since their CMake config files are no longer installed (into the `.conan` directory).
Also fixed a couple of minor issues discovered whilst debugging
* The linter CI job was using the wrong GitHub runner (Ubuntu 22.04 rather than 20.04), meaning, at best, duplicated packages in the Conan package cache, or at worst, cache misses due to the caching race condition between jobs.
* A long-standing TODO comment was resolved, since the latest Conan versions no …
> [CI] Fix CI for latest version of Conan/recipes

- doc/decisions/DR014-Management-policy-responses.md
Part of #778, this aspect of the API has not been documented in any detail. This DR is in a proposed state, to seek wider council before accepting the choice and updating the other project documentation.
Rendered version available [here](https://github.com/OpenAssetIO/OpenAssetIO/pull/792/files?short_path=0b35e59#diff-0b35e59eec7ea3a13caa38ad0890930a980657332193ce29c79d177d352d638f).
> [Docs] Add DR covering canonical use of `managementPolicy`

- RELEASE_NOTES.md
- doc/doxygen/src/Examples.dox
- src/openassetio-core/include/openassetio/trait/TraitBase.hpp
- src/openassetio-core/tests/trait/TraitBaseTest.cpp
- src/openassetio-python/package/openassetio/TraitBase.py
- src/openassetio-python/tests/package/test_trait.py
Closes #815
For symmetry with `imbue` and `imbueTo` methods, rename the `isValid` method to `isImbued.`
For C++ in particular, where performance is likely a concern, constructing a `TraitBase`-derived instance, just to check `isImbued`, is wasteful. So add a static `isImbuedTo` (for symmetry with `imbueTo`), which tests a `TraitsData` without unnecessary temporary
construction.
> `TraitBase` `isImbued` and `isImbuedTo`

- doc/decisions/DR015-Strategy-for-methods-with-several-signature-variations.md
DR to help form a decision on how best to handle function overloads given some of our target languages don't support them, and we need to try and build a consistent, coherent experience.
Rendered version for 👀 [here](https://github.com/OpenAssetIO/OpenAssetIO/pull/824/files?short_path=efab4f6#diff-efab4f65e4e97ca6600b8a302c55d1bd5fd3d1c2f5fff2d8394d93bb78fab4aa).
> [Doc] Add DR for method overload naming

- doc/BUILDING.md
[Recently](https://github.com/OpenAssetIO/OpenAssetIO/commit/3ffc8897bff874215ecbe61a16879f11119f9a56), we had changed the default behaviour of the OpenAssetIO build to not build the C libraries, due to how they are unstable and shouldn't be considered ready-for-use.
This commit updates a flag in the build docs to reflect that.
> [Doc] Update C Flag default doc

- README.md
Keeps cropping up until we sort `aarch64` and `sdist` releases...
> [Docs] Add notes on PyPi aarch64 support

- .github/workflows/integrations.yml
TraitGen now includes C++ tests. This causes two issues. Firstly, the C++ AST is tested with a third-party library, "tree-sitter". So we must install the appropriate `requirements.txt` to get that dependency.
Secondly, the C++ CMake CTest tests require an OpenAssetIO C++ install tree. This will be fixed as a follow-up issue (#841). In the meantime they will be automatically skipped, since we don't specify the required `OPENASSETIO_TRAITGENTEST_CMAKE_PRESET` environment variable.
> [CI] Fix TraitGen integration test dependencies

- doc/doxygen/src/Examples.dox
- src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
Our previous examples lead people to think they need to include 'Host' or similar in these strings. This attempts to make it clearer that it's supposed to just be the common name for host/manager in question.
Closes #829
> [Docs] Add more examples to displayName and identifier docs

- .github/workflows/test.yml
When we refactored the repo, we inadvertently neglected to update the path in the step that publishes the built docs as an artifact of the run.
Test from CI run: https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/4532689159
> [CI] Fix docs build artifact path

- src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
- src/openassetio-core/include/openassetio/log/LoggerInterface.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
There isn't anything we can do in code to help with this (as you can't force a derived class constructor to be private, or inherit static methods without Template Fun™). So document how to do the right thing...
Closes #822
> [Docs] Document C++ `make` convention

- doc/doxygen/src/Configuration.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/footer.html
An attempt to capture the snippets of setup notes scattered around the docs in once place.
Pre-built version here: https://github.com/OpenAssetIO/OpenAssetIO/suites/11835979369/artifacts/618358855
`index.html` -> Configuring OpenAsset IO
Closes #770
> [Docs] Document plugin loading and config mechanisms

- CPPLINT.cfg
- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/BatchElementError.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/tests/BatchElementErrorTest.cpp
- src/openassetio-core/tests/hostApi/ManagerTest.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
Closes https://github.com/OpenAssetIO/OpenAssetIO/issues/849. 
Previously, the only interface to `resolve` assumed a batch of entity references with success/error callbacks executed for
each element. This is somewhat clunky when only resolving a single reference in particular, and requires significant boilerplate.
So add convenience overloads that present the API in a friendlier and more versatile manner.
As resolve conveniences in C++ and Python are going to be somewhat distinct, add C++ tests to verify behaviour of `variant` and exception error modes.
> C++ `resolve` method host conveniences

- RELEASE_NOTES.md
- doc/doxygen/src/Examples.dox
- doc/doxygen/src/ManagerState.dox
- examples/host/simpleResolver/simpleResolver.py
- src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp
- src/openassetio-python/cmodule/src/_openassetio.hpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/test_batchelementerror.py
Closes #850. Follows on from #849 (not just numerically).
For parity with C++ methods, bind `resolve` convenience overloads to Python.
Python unit tests added.
> Python `resolve` method host conveniences

- cmake/DefaultTargetProperties.cmake
By defalut, CMake ommits this if the compiler default matches the project. We run clang-tidy as part of build, version mismatches can resut in failed checks if the discoverd linter has an older default std. Explicitly setting this ensures checks run with the right std version.
> [Build] Always set `-std=c++17`

- RELEASE_NOTES.md
- cmake/StaticAnalyzers.cmake
- src/openassetio-core-c/.clang-tidy
- src/openassetio-core-c/src/InfoDictionary.cpp
- src/openassetio-core-c/src/errors.hpp
- src/openassetio-core-c/src/hostApi/Manager.cpp
- src/openassetio-core-c/tests/.clang-tidy
- src/openassetio-core-c/tests/InfoDictionaryTest.cpp
- src/openassetio-core-c/tests/StringViewReporting.hpp
- src/openassetio-core-c/tests/StringViewTest.cpp
- src/openassetio-core-c/tests/errorsTest.cpp
- src/openassetio-core-c/tests/hostApi/ManagerTest.cpp
- src/openassetio-core-c/tests/managerApi/CManagerInterfaceAdapterTest.cpp
- src/openassetio-core-c/tests/managerApi/MockManagerInterfaceSuite.hpp
- src/openassetio-core/include/openassetio/errors.h
- src/openassetio-core/src/hostApi/ManagerFactory.cpp
- src/openassetio-core/src/log/SeverityFilter.cpp
- src/openassetio-core/tests/BatchElementErrorTest.cpp
- src/openassetio-core/tests/TraitsDataTest.cpp
- src/openassetio-core/tests/managerApi/ManagerStateBaseTest.cpp
- src/openassetio-core/tests/trait/TraitBaseTest.cpp
- src/openassetio-python/bridge/src/python/hostApi.cpp
- src/openassetio-python/cmodule/src/_openassetio.cpp
- src/openassetio-python/private/include/openassetio/private/python/pointers.hpp
- src/openassetio-python/tests/bridge/main.cpp
- src/openassetio-python/tests/bridge/python/test_hostApi.cpp
Although we have yet to move to the newer `clang-tidy` on CI, we aim to support devs using a newer `clang-tidy` than v12.
We seem to be getting cross-platform differences coming from a `std::rethrow_exception` call in `src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp`.  That is, MacOS gives a warning that the `std::exception_ptr` cannot be `std::move`d, for some reason.  See also https://github.com/OpenAssetIO/OpenAssetIO/pull/867#issuecomment-1492211562
> Fix clang-tidy v15 warnings

- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/tests/hostApi/ManagerTest.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
Closes #876. Currently `variant`s returned from `resolve` seem the wrong way around, in particular when default-constructed, where the current formulation would create a variant holding a `nullptr` `TraitsDataPtr`, which is dangerous and less informative than a `BatchElementError` with a default error code.
Does the volume of changes, and the fact that it's easy to get the ordering wrong, lend some weight to the idea of having a `typedef` for this?
> Default to `BatchElementError` in `variant` returns

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/tests/hostApi/ManagerTest.cpp
Closes #853. Similar to recent work on `resolve`, we wish to make our users' lives easier by having overloads of `register_` that model common usage scenarios. In particular, single-element and/or exception-less workflows.
So add these conveniences to the c++ API, with Python to follow in future work.
~- [ ] I have updated all relevant user documentation.~
Similar to resolve, although the signature is slightly different.
Have attempted to stick to standards established in https://github.com/OpenAssetIO/OpenAssetIO/pull/877 re: minor naming things.
The pybind declaration is already in the fully expanded form for register, so no need to amend it :)
> C++ `register` convenience signatures

- RELEASE_NOTES.md
- doc/doxygen/src/Examples.dox
- doc/doxygen/src/ManagerState.dox
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #852
Add Python bindings to `preflight` overloads that allow single-element and/or exception-less workflows.
> Python bindings for `preflight` conveniences

- RELEASE_NOTES.md
- doc/doxygen/src/Examples.dox
- doc/doxygen/src/ManagerState.dox
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #854 Add Python bindings to `register` overloads that allow single-element and/or exception-less workflows.
Tests will be tidied somewhat as part of #886
Also related is #881, which at time of writing is awaiting review/merge, so may prompt an update of this PR if it is merged first.
> Python bindings for `register` conveniences

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
- src/openassetio-core/src/managerApi/HostSession.cpp
- src/openassetio-core/tests/managerApi/HostSessionTest.cpp
Avoids unneccesary copies when invoked as follows:
```
session->logger()->warning("Something bad")
```
Closes #814.
> Return a `const&` from `HostSession::logger`

- RELEASE_NOTES.md
- doc/doxygen/src/ForManagers.dox
- src/openassetio-python/package/openassetio/hostApi/Manager.py
- src/openassetio-python/package/openassetio/managerApi/ManagerInterface.py
- src/openassetio-python/tests/conftest.py
Part of #16.
`set` was not well considered, as it has the potential for race conditions in real-world scenarios. A re-design is in the works, so remove for now to avoid dead code in the release.
> Remove `setRelatedReferences`

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
> Deep-copy locale in `createChildContext`

- resources/build/bootstrap-ubuntu-20.04.sh
This got added to the upstream conan recipe for xorg, so we need it installed.
> [CI] Add libxcb-cursor-dev to ubuntu bootstrap.

- doc/contributing/COMMITS.md
From action item from last weeks retro.
As `Core` was becoming a bit of a catch all, and there is a fair bit of utility to be gained by being able to see whether a commit is solely python focused or not, add additional code components for other api types.
Given the nature of OpenAssetIO being C++ first, and internal work also normally being C++ api work, i decided not to explicitly have a `C++` tag, and leave that under the auspices of `Core`, since to do so I fear would create situation where you need more than 1 tag to describe something properly.
~- [ ] I have updated the release notes.~
~- [ ] I have updated all relevant user documentation.~
> [Docs] Add additional commit message components

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/managerApi/HostSession.hpp
- src/openassetio-core/src/managerApi/HostSession.cpp
- src/openassetio-core/tests/managerApi/HostSessionTest.cpp
Avoids unneccesary copies when used inline.
Closes #904
> [Core] Return a `cont&` from `HostSession::host`

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
It is a lot easier to work with the locale if it is never null. Otherwise, appending to a locale ends up needing branches which adds unneccesary complexity.
Closes #903
> Create new Contexts with pre-initialized locale

- .github/workflows/integrations.yml
- RELEASE_NOTES.md
- doc/doxygen/src/EntitiesTraitsSpecifications.dox
- doc/doxygen/src/ForManagers.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/Thumbnails.dox
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-python/package/openassetio/hostApi/Manager.py
- src/openassetio-python/package/openassetio/managerApi/ManagerInterface.py
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/managerApi/test_managerinterface.py
Closes #847, takes the opportunity to add a default implementation as these are optional methods for a manager.
> Refactor `getRelatedReferences`

- RELEASE_NOTES.md
- src/openassetio-python/cmodule/src/EntityReferenceBinding.cpp
- src/openassetio-python/tests/package/test_entityreference.py
Had a moment to chip away at the backlog a little, so was looking for a small task.
Allows them to be used with fstrings, print, etc. Retains the `toString` method for compatibility and/or more explicit programming.
Part of #573.
> [Python] Add `__str__` implementation for `EntityReference`

- RELEASE_NOTES.md
- src/openassetio-python/bridge/CMakeLists.txt
- src/openassetio-python/bridge/include/openassetio/python/converter.hpp
- src/openassetio-python/bridge/src/python/converter.cpp
- src/openassetio-python/tests/bridge/CMakeLists.txt
- src/openassetio-python/tests/bridge/lsan_suppressions.txt
- src/openassetio-python/tests/bridge/python/test_converter.cpp
Closes #798. Adds new `openassetio::python::converter` namespace with functions `castToPyObject` and `castFromPyObject`.
AC "Documentation examples updated" - other than docstrings (which contain snippets), we don't have C++ example docs to update(?).
AC "Integration tests added (OpenAssetIO-Test-CMake or otherwise)" - do we still think this is necessary in addition to included Catch2 tests?
Unit tests provided. Tricky to test externally without hacking together a hybrid C++/Python OpenAssetIO host.
> Provide C++ functions to expose objects to Python

- RELEASE_NOTES.md
This hopefully helps avoid accidentally merging feature branch changes into older releases, if a release happens on main whilst the branch is alive.
Experimenting with a `feat!` commit prefix that indicates that we need to massage the commit history before merging to `main` what do people thing?
> Move `getRelated` refactor release notes into feature-specific section

- RELEASE_NOTES.md
- src/openassetio-python/bridge/include/openassetio/python/converter.hpp
We forgot to add these, wanna do it before the release.
Some methods are implemented in python, temporarily, and this means that casted PyObjects wont have access to those methods. Add docs to describe this niggle, even though this problem will disappear soon as these methods get ported to c++.
> [Docs] Docs detailing python cast exceptions

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp
- src/openassetio-core/src/hostApi/ManagerFactory.cpp
- src/openassetio-python/tests/package/hostApi/resources/default_manager.toml
- src/openassetio-python/tests/package/hostApi/test_managerfactory.py
Closes #804.
It is common in test scenarios to create portable, self-contained manager states using BAL.
At the moment, this requires relative paths in the TOML file, and so becomes working directory sensitive. This makes it fragile.
So add support for the substitution in TOML string values of `$config_dir` or `${config_dir}` tokens with the absolute directory to the TOML config file.
This is currently done in the most basic way possible, by direct string find-and-replace, rather than a more complete solution supporting e.g. environment variable interpolation. Such improvement is for future work if/when the need ever arises.
> [Core] Add $config_dir config TOML interpolation

- .github/workflows/code-quality.yml
- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-python/package/openassetio/hostApi/Manager.py
- src/openassetio-python/package/openassetio/managerApi/ManagerInterface.py
- src/openassetio-python/pyproject.toml
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/managerApi/test_managerinterface.py
Still Python only, but should now be the final signature.
Fixes a few typos, and has to disable the `pylint` similarity checker due to  false positives.
Closes #919
> Migrate `getWithRelationship[s]` to callbacks

- examples/host/simpleResolver/bal_animals_openassetio_config.toml
- examples/host/simpleResolver/test_simpleResolver.py
Closes #941. 
Dogfood the new `${config_dir}` substitution in the simpleResolver test example config file.
> Use ${config_dir} in simpleResolver test

- examples/host/simpleResolver/test_simpleResolver.py
Asserting on specific messages in third-party systems is known to create maintenance churn if they change (which they will in the next release).
> [Examples] De-couple simpleResolver tests from BAL

- doc/decisions/DR016-One-to-many-result-paging.md
Closes #188. Add decision record considering options for result paging, in particular for the related entities query.
[Rendered version](https://github.com/OpenAssetIO/OpenAssetIO/blob/2c14e29fde34e464ca190ace49b3917af9901834/doc/decisions/DR016-One-to-many-result-paging.md) for 👀
> [DR] Result paging strategy for related entities query

- doc/decisions/DR017-Entity-version-queries.md
TL;DR The versioning API (`entityVersion`, `entityVersions`, `getFinalizedEntityVersion`) will be removed from the core API, replaced by formal traits in MediaCreation. Explained with rationale [here](https://github.com/OpenAssetIO/OpenAssetIO/blob/a9d16ed5ce2825c1976e18e06bb8cbd750518b62/doc/decisions/DR017-Entity-version-queries.md#outcome)
Read all about the background and more details [here](https://github.com/OpenAssetIO/OpenAssetIO/pull/962/files?short_path=17bb0c7#diff-17bb0c753b5eaf352dbc0b5d4964c88b0bdf8f0ec14acbf11ab1ae8fe55cbfa6).
> [Docs] Add DR to move versions API to MediaCreation

- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
This was inadvertently missed when we updated the equivalent in Manager.
Closes #981
NB this is a copy-paste from `Manager.hpp`.
> [Docs] Fix ManagerInterface resolution overview

- doc/doxygen/src/styles.scss
Changes the width of the main content div to by default, always be 1100px. This is effectively the same as our prior max-width in  every case, as we always have prose that can push the width to that limit and cause a wrap.
The `width: min-content` flag, in combination with using min rather than max, overrides this in cases where the contents are fixed width and cannot wrap (like method sig tables,) and allows the frame to be pushed out to support its minimum width.
However, the problem with this approach would be that smaller frame sizes that _could_ support non-fixed widths, (ie, all of our pages that are just prose and can wrap very tightly), would no longer wrap below 1100px. To that end, use a media query to remove the minimum width when the frame gets that narrow.
I think this is a …
> [Docs] Add expand-to-content width

- src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
In #913 we changed the ordering of parameters to `ManagerInterface::getWithRelationship[s]`, but missed changing the order in the pybind11 bindings. This would mean incorrect auto-generated docstrings/error messages as well as incorrectly bound named arguments.
These are currently untested. See [#463](https://github.com/OpenAssetIO/OpenAssetIO/issues/463)
> [Core][Python] Fix getWithRelationship(s) kwarg order

- RELEASE_NOTES.md
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/include/openassetio/hostApi/EntityReferencePager.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/EntityReferencePagerInterface.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/src/hostApi/EntityReferencePager.cpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/src/managerApi/ManagerInterface.cpp
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/cmodule/src/PyRetainingSharedPtr.hpp
- src/openassetio-python/cmodule/src/_openassetio.cpp
- src/openassetio-python/cmodule/src/_openassetio.hpp
- src/openassetio-python/cmodule/src/hostApi/EntityReferencePagerBinding.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
- src/openassetio-python/package/openassetio/hostApi/__init__.py
- src/openassetio-python/package/openassetio/managerApi/__init__.py
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_entityreferencepager.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/managerApi/test_managerinterface.py
Adds paged GetWithRelationship methods.
Closes #971 
Split into 4 main commits, but will be squashed into 2 (maybe just 1)
This PR introduces a new pattern for PyRetainingSharedPtr in the ManagerInterfaceBinding. This needs to be factored out a bit, or at least docc'd.
We did some C++ testing for the pager object as part of a test-loop workflow. In theory these can be deleted now to fit with our python test philosophy, but I see no need to.
> Paged GetWithRelationship

- RELEASE_NOTES.md
- src/openassetio-python/bridge/src/python/converter.cpp
- src/openassetio-python/tests/bridge/python/test_converter.cpp
Closes #988. 
In real-world use cases, it is useful to get a `None` value from an uninitialised `shared_ptr` when passed to `castToPyObject`, rather than that being an error case. E.g. testing whether a manager (`ManagerPtr`) has been created or not.
Note that the converse was already the case, i.e. `castFromPyObject`, when given `None`, would return a `nullptr`, but we didn't have tests for that case (until now).
The behaviour when passing a `nullptr` `PyObject` to `castFromPyObject` has not been changed - we will still throw an exception in that case. This seems reasonable, since the alternative is a segfault.
> Return `None` when `castToPyObject` a `nullptr`

- RELEASE_NOTES.md
In #998 the `openassetio.constants` pure-Python module was migrated to a CPython submodule (`_openassetio.constants`), which has the unfortunate side-effect of no longer allowing the `import` of individual elements inside the module (i.e. `from constants import <something>`).
So update the release notes to call that out as an additional breaking change.
This was detected (and fixed) in BAL in OpenAssetIO/OpenAssetIO-Manager-BAL#55
> [Docs] Breaking change release note for `constants` import

- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/include/openassetio/hostApi/EntityReferencePager.hpp
- src/openassetio-core/include/openassetio/managerApi/EntityReferencePagerInterface.hpp
- src/openassetio-core/src/hostApi/EntityReferencePager.cpp
- src/openassetio-core/src/managerApi/EntityReferencePagerInterface.cpp
- src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_entityreferencepager.py
Add `close` method to pager interface, called upon destruction of pager
There were various subtle issues with tying the notification of the end of the page query to the destruction of the pager interface. Aside from relying on lifetime like that not being very pythonic (having to override del,) it creates an implicit usage assumption that the PagerInterface is not declared in a greater scope than the pager. Not to mention that the prior design encourages throwing in destructors moreso than this new one.
Adding a close method binds the cleanup entry hook directly to the lifetime of the Pager, rather than the PagerInterface.
Closes #990
~~I have updated all relevant user documentation.~~
This comes with a single additional test that just checks the method is called after a `del`. Tbh I …
> [Core] Add close method to PagerInterface

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/_implementation.py
It's very easy for manager plugin authors to accidentally miss defining a fixture, causing a test to be skipped erroneously. With the default report, it is difficult to discern which tests were skipped.
So increase the verbosity, so that all tests are printed along with their status, including the reason given for skipping a test.
This was highlighted when, on a hunch, I increased verbosity to find that BAL's fixtures file seems to be missing some definitions that should be there (see https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/61). Hopefully permanently increasing verbosity will help prevent this in future.
Run the API compliance suite against, say, BAL, and note that all test names are printed alongside their status.
> [Python] Increase verbosity of API compliance suite

- doc/contributing/CODING_STANDARDS.md
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #987.  Add a couple of tests to assert the finding that `unordered_set` is safe to use as a default argument value in pybind11 bindings.  Add a short explanation of pybind11 default argument pitfalls in CODING_STANDARDS.
TL;DR: the `unordered_set` we supply as a default value to `py::arg(...)` is copied into a Python `set` and stored by pybind11, then recalled when needed, where it is copied back to an `unordered_set` to pass to C++.
A common pitfall in pure Python is setting a default value for an argument in a function to a mutable value, e.g.
```python 
def someFunction(*args, resultTraitSet=set()): ... 
```
In the above, any mutation to the default-provided `resultTraitSet` will persist in the next invocation.
In our pybind11 bindings we have a similar pattern, i.e.
```c++ …
```
> Investigate pybind11 default args

- .github/workflows/build-wheels.yml
- RELEASE_NOTES.md
- doc/BUILDING.md
- resources/build/bootstrap-cibuildwheel-manylinux-2014.sh
- resources/build/conanfile.py
Closes #977 
Conflicting libuuid pacakges are in the build dependency tree for cpython at this time, causing our CI to fail. So just remove cpython.
See failure here: https://github.com/elliotcmorris/OpenAssetIO/actions/runs/5820687754/job/15781579400?pr=29
To be fixed in the `cpython` recipe upstream (eventually) here: https://github.com/conan-io/conan-center-index/pull/18558
Need to check dependent projects that build OpenAssetIO from source.
> [CI] Remove `cpython` dependency

- RELEASE_NOTES.md
- doc/doxygen/Doxyfile
Doxygen rendered the `Ptr` types (e.g. `ManagerPtr`, `Manager::Ptr`) as plain text because its preprocessor couldn't find `typedefs.hpp`, where the various macros are defined. Further, those macros were not on the allow-list.
So fix the `INCLUDE_PATH`, and augment the `EXPAND_AS_DEFINED` parameters. This makes the Doxygen output have much richer cross-references.
I came across this yet again when updating docs for [#1028](https://github.com/OpenAssetIO/OpenAssetIO/issues/1028). The fix is simple enough so I thought worth a cheeky PR.
Build the docs locally in `doc/doxygen` by simply typing `make`. Check against the current published docs at https://openassetio.github.io/OpenAssetIO/index.html
> [Docs] Fix Doxygen include path and macro expansion

- RELEASE_NOTES.md
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/Thumbnails.dox
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-python/cmodule/src/ContextBinding.cpp
- src/openassetio-python/package/openassetio/managerApi/ManagerInterface.py
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
- src/openassetio-python/tests/package/test/manager/test_harness.py
- src/openassetio-python/tests/package/test_context.py
https://github.com/OpenAssetIO/OpenAssetIO/issues/1016
Adds the `kCreateRelated` context access mode.
This is an access mode necessary to signal intent to create related entities, rather than mutations/versions of an entity. This comes up particularly in the "folder in a folder" case, where it's very likely that the regular method of determining version/new, (checking that the traitsets match,) will not be enough.
Also remove the idea of multiple writes, due to ther being no coherent use for these within the core API methods themselves, and so this behavior could be more accurately and coherently expressed as part of the UI layer itself.
Dosen't close the linked issue, as workflow tests havn't been explored yet. OpenAssetIO api surface has been prioritised, see …
> [Core] Refine Context.access modes

- RELEASE_NOTES.md
- doc/doxygen/src/Configuration.dox
- doc/doxygen/src/EntitiesTraitsSpecifications.dox
- doc/doxygen/src/Examples.dox
- doc/doxygen/src/ForHosts.dox
- doc/doxygen/src/ForManagers.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/MainPage.dox
- doc/doxygen/src/Thumbnails.dox
- src/openassetio-core-c/src/managerApi/CManagerInterfaceAdapter.cpp
- src/openassetio-core-c/src/managerApi/CManagerInterfaceAdapter.hpp
- src/openassetio-core/include/openassetio/BatchElementError.hpp
- src/openassetio-core/include/openassetio/errors.h
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/tests/hostApi/ManagerTest.cpp
- src/openassetio-python/cmodule/src/BatchElementErrorBinding.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #1028
Closes #1029
Changes the signature of `preflight` to accept a `TraitsData` per reference, rather than a single trait set applied to all references. Existing docs and examples updated.
Simultaneously relaxes the restriction that all batch published entities must be of the same type.
Combined two issues into one PR here, since it avoids adding an artificial restriction to `preflight` to ensure trait set homogeneity, just to remove it again in the next issue.
Commits split into roughly related chunks of work, intended to be squashed into a single commit once approved.
Minimal changes to BAL https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/63 to get these API changes in as soon as possible.
> Preflight `TraitsData` and relax `register` trait set homogeneity

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/include/openassetio/typedefs.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/src/managerApi/ManagerInterface.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
- src/openassetio-python/package/openassetio/hostApi/Manager.py
- src/openassetio-python/package/openassetio/managerApi/ManagerInterface.py
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/managerApi/test_managerinterface.py
Closes #996
Migrate the `updateTerminology` method to C++.
No behaviour changes, although interface updated from an in-out arg to a pass-by-value return-by-value formulation, in order to sidestep any python shenanigans with object references.
> [Core] Migrate `updateTerminology` to C++

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
Closes #1022
Alter the skip fixture in certain getWithRelation tests away from common shared ones  to the `a_relationship_trait_set`, which is less likely to be defined in a shared context.
This is helpful because relationships are an optional feature, so it is likely managers will want to skip all the relationship tests as a group, and this makes that more or less the default behaviour without thinking about it.
~~- [ ] I have updated all relevant user documentation.~~
Tested manually with BAL, checking that removing the fixtures causes tests to skip.
> [Test] Alter which fixture skips relation tests

- .github/workflows/integrations.yml
As we weren't actually installing BAL we were missing its dependencies, which breaks other tests that use it. BAL should also be up-to-date now too.
> [CI] Re-enable BAL integration tests

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
Detected whilst working on OpenAssetIO/OpenAssetIO-Manager-BAL#57.
If the manager is strict about which access modes it supports, then leaving it as the default `kUnknown` is likely to fail for many functions.
> Set the correct `Access` in API compliance tests

- RELEASE_NOTES.md
- doc/doxygen/src/Examples.dox
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/src/Context.cpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/tests/ContextTest.cpp
- src/openassetio-python/cmodule/src/ContextBinding.cpp
- src/openassetio-python/package/openassetio/_core/audit.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/test_context.py
Closes #1048
Remove retention enum from context, and from existence, as its usage is tenuous now we have compositional locales, and relationship methods for stable refs.
Tom kindly slapped the removal of retention into his USD PR, https://github.com/OpenAssetIO/usdOpenAssetIOResolver/pull/30/commits/a305b31598bde7b22e8383983f7a55b9c8dc69c3, so no other repos need changing.
> [Core] Remove retention from context

- doc/decisions/DR019-Remove-access-from-the-context.md
TL;DR - We want to break some things (well most things) to Make Everything Better™. We need to fix the ambiguity around how to use `Context.access` for both hosts and managers. Now is the last chance we have, before too many people have done a lot of harder-than-it-should-be typing.
Rendered version for 👀 [here](https://github.com/OpenAssetIO/OpenAssetIO/pull/1051/files?short_path=d32e611#diff-d32e611102451d160a468398b9f514d423484731dc41f3ac42183d2d4fc9dd6b)
We need to ratify this decision by e.o.d Thurs 24th August.
> [Docs] Add DR for the removal of `access` from `Context`

- doc/doxygen/Doxyfile
We're hiding this for now, as it is not functional.
Closes #1034
> [Docs] Skip C documentation until more progressed

- RELEASE_NOTES.md
- src/openassetio-core/src/TraitsData.cpp
- src/openassetio-python/tests/package/test_traitsdata.py
Raising if the trait was missing added significant boilerplate to many common access patterns.
Closes #970
Note: This felt too easy. Im sure I've missed something.
> [Core] Relax checks in `TraitsData::getTraitProperty`

- RELEASE_NOTES.md
- cmake/ThirdParty.cmake
- doc/BUILDING.md
- doc/contributing/CODING_STANDARDS.md
- resources/build/Dockerfile
- resources/build/Makefile
- resources/build/conanfile.py
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/src/hostApi/Manager.cpp
Closes #1070.
fmtlib allows for easy, safe string substitution in C++, adding advanced formatting functionality (e.g. rounding), and reducing bloat.
So add as a new private build-only header-only dependency.
Using header-only increases compile times, but subjectively it's not noticeable, and has the benefit of avoiding a possible public library dependency (if OpenAssetIO is built as a static library).
Tweak a single existing, tested, log string to make use of libfmt, to ensure basic usage is validated.
Added to openassetio-build Docker image: https://github.com/OpenAssetIO/OpenAssetIO/pkgs/container/openassetio-build
- ~~[ ] I have updated all relevant user documentation.~~
> Add fmtlib dependency

- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
Closes #1090. The manager should re-initialize with updated settings, rather than no-op. The corresponding docs in `Manager` were recently fixed. So add the fix also to the `ManagerInterface.initialize` member function.
> [Docs] Fix ManagerInterface reinitialize behaviour

- src/openassetio-core/include/openassetio/hostApi/ManagerFactory.hpp
Was accidentally with the env var version rather than the one with the file spec.
> [Docs] Fix placement of ManagerFactory var expansion docs

- doc/doxygen/Doxyfile
On the whole - we were in pretty reasonable shape. Checked 'black', 'white', 'master' and 'slave'. The remaining references are to either colors, or 'whitespace'.
> [Docs] Switch to inclusive terminology in `Doxyfile`

- doc/doxygen/Doxyfile
- doc/doxygen/src/ForHosts.dox
- doc/doxygen/src/ForManagers.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/MainPage.dox
- doc/doxygen/src/ManagerState.dox
- src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystemManagerPlugin.py
We were accidentally `@ref`ing Python hoists. This updates those refs, and then removes the hoists from scanning, which cleans up the class index.
Closes #1093
> Don't scan Python hoists

- .github/workflows/code-quality.yml
- resources/build/linter-requirements.txt
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/package/openassetio/test/manager/_implementation.py
- src/openassetio-python/pyproject.toml
- src/openassetio-python/tests/package/_core/test_audit.py
- src/openassetio-python/tests/package/hostApi/test_entityreferencepager.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/hostApi/test_managerfactory.py
- src/openassetio-python/tests/package/hostApi/test_managerimplementationfactoryinterface.py
- src/openassetio-python/tests/package/hostApi/test_terminology.py
- src/openassetio-python/tests/package/managerApi/test_host.py
- src/openassetio-python/tests/package/managerApi/test_hostsession.py
- src/openassetio-python/tests/package/managerApi/test_managerinterface.py
- src/openassetio-python/tests/package/managerApi/test_managestatebase.py
- src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystem.py
- src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystemmanagerimplementationfactory.py
- src/openassetio-python/tests/package/test/manager/conftest.py
- src/openassetio-python/tests/package/test/manager/test__implementation.py
- src/openassetio-python/tests/package/test/manager/test_harness.py
- src/openassetio-python/tests/package/test/manager/test_main.py
- src/openassetio-python/tests/package/test_batchelementerror.py
- src/openassetio-python/tests/package/test_context.py
- src/openassetio-python/tests/package/test_entityreference.py
- src/openassetio-python/tests/package/test_imports.py
- src/openassetio-python/tests/package/test_log.py
- src/openassetio-python/tests/package/test_traitsdata.py
Closes #807. The `--recursive` option added in Pylint v2.13.5 allows Pylint to use a directory of test modules that are not structured as a Python package, i.e. it avoids errors like
> No such file or directory: [...] \_\_init\_\_.py
This particular error, frustratingly, does not actually fail the check on CI, so we built up quite a backlog of Pylint warnings in the `tests` directory.
So pin to the latest v2 of Pylint, which supports this feature, and use it in the CI config.
Also fix the backlog of Pylint warnings.
As evidenced by the commits, this change relies on an upstream change to `fn-pylint-action`: https://github.com/TheFoundryVisionmongers/fn-pylint-action/pull/10
See [here](https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/6352847630/job/17256455739) for a recent example …
> Improve `pylint` coverage

- .github/workflows/integrations.yml
- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/EntityReferencePager.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/src/managerApi/ManagerInterface.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/managerApi/test_managerinterface.py
Closes #1125 
The commit that renames the callback is certainly up for debate, but it seemed more consistent with the new capabilities, etc, and allows future expansion of the (known) add relationship workflows later without a rename.
Has a drop commit targeting https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/78
> Remove non-paged relationship query methods

- RELEASE_NOTES.md
Also slightly tweaks the `hasCapability` wording to denote that it is required, and is used by the middlew too (or soon will be).
> [Docs] Fix `RELEASE_NOTES` sections

- RELEASE_NOTES.md
- doc/doxygen/src/ForHosts.dox
- doc/doxygen/src/ForManagers.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/MainPage.dox
- src/openassetio-core/include/openassetio/hostApi/ManagerImplementationFactoryInterface.hpp
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystemManagerPlugin.py
This is beyond specuative, also removes documentation referencing the non-existant UI layer. This was confusing people.
Closes #1150
> [Core] Remove `PPSManagerPlugin.uiDelegate`

- src/openassetio-core/src/managerApi/ManagerInterface.cpp
This is a relic from the old default implementation.
> [Core] Remove unused `EmptyEntityReferencePagerInterface`

- RELEASE_NOTES.md
- doc/contributing/CODING_STANDARDS.md
- doc/doxygen/src/ForManagers.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/MainPage.dox
- doc/doxygen/src/ManagerState.dox
- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
- src/openassetio-core/include/openassetio/managerApi/ManagerStateBase.hpp
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystemManagerPlugin.py
This came from good intentions but is ultimlately misleading, given the settings mechanism, etc.
This also updates to the American form of 're-enterant' to align with our US English docs poicy.
Closes #1143
> [Docs] Remove misleading use of the term 'stateless'

- RELEASE_NOTES.md
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
`Manager` will now verify that the wrapped interface implementation suports the required core capabilities. This is done here, as `hasCapability` can only be called post-initialize so we can support proxy interfaces etc...
Closes #1148
As ever, I have no idea any more what constitutes "best practice c++" these days, so attempted to go for 'readability'. C+C most welcome....
> [Core] Verify that managers support required capabilities

- RELEASE_NOTES.md
Trying to make the bigger picture a bit easier to grok...
Question - should we get rid of the emoji hammer for build until we have other ones we use for other areas? So its not all on its own? (or add ones for the other things now)
> Group related changes in RELEASE_NOTES

- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
The exceptional conveniences did not document that they threw. This was somewhat implicit, however with the addition of the NotImplementedException, it is now quite suspicious, as it looks like they only throw NotImplementedExceptions, which isn't true from the host perspective.
Didn't log an issue for this, comes from https://github.com/OpenAssetIO/OpenAssetIO/pull/1141#discussion_r1349794207, I just thought doing this as a seperate PR would avoid holding up the prior one.
Looks like :
> [Doc] Add throws doc to exception policy overloads

- examples/host/simpleResolver/simpleResolver.py
Hopefully illustrates best practice.
This is pretty bare-bones as we don't have an easy way to properly test this (as we don't have a mock manager that we can puppet the return value for).  We don't have comprehensive coverage of this example anyway, and so it feels better to at least have one example of `hasCapability` out there...
Closes #1166
> [Examples] Add `hasCapability` check to `simpleResolver.py`

- .github/workflows/integrations.yml
Fix regex used to detect if TraitGen's `requirements.txt` tries to uninstall `openassetio`.
In OpenAssetIO/OpenAssetIO-TraitGen#51 we had to remove the PyPI dependency on `openassetio` temporarily, since the project now depends on the breaking changes in the latest OpenAssetIO main branch. So `openassetio` was commented out in `tests/requirements.txt` in that project.
We now have two valid cases, either TraitGen's `requirements.txt` tries to install `openassetio` and short-circuits (saying it's already installed), or it doesn't try at all.
So update the guard regex to catch either case, i.e. assert that `pip` does not attempt to uninstall `openassetio`, for whatever reason.
Locally, from TraitGen project root
```
$ pip install openassetio==1.0.0a12
$ python -m pip install -r …
```
> [CI] More robust openassetio uninstall regex guard

- resources/build/bootstrap-ubuntu-20.04.sh
Part of #1114. The additional system packages for Linux builds are no longer necessary since #1038 - we now use the system-provided Python rather than the `cpython` Conan package, which required all these extra system dependencies.
> [CI] Remove `apt install` of Conan `cpython` deps

- README.md
Add some text to the contributing section of the main readme, explaining how OpenAssetIO is a challenging project. Otherwise, it can seem unfair to contributors who might be under the impression that we're a regular project with a big backlog available for work.
> [Doc] Add contribution difficulty warning

- .github/workflows/build-vfx-reference-platform.yml
- .github/workflows/build.yml
A continuation of : https://github.com/OpenAssetIO/OpenAssetIO/pull/1187
New PR because the approach changed significantly.
Part of https://github.com/OpenAssetIO/OpenAssetIO/issues/1181
Add archive behaviour to merges to main, so OpenAssetIO is built on all of our runner platforms and archived in github.
Intent is to unlock much better CI behaviour for us, as we are spending a lot of time and effort building OpenAssetIO across dependent repos, as well as just being generally convenient to have.
This will publish an artifact to every PR run, as well as one for each commit to main. The idea being that dependent repos are by default targetted to the `main` branch with the download-artifact action.
> Publish platform artifacts from CI.

- RELEASE_NOTES.md
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/cmodule/src/EntityReferenceBinding.cpp
- src/openassetio-python/tests/package/test_entityreference.py
We opted not to go for `EntityReference("theStr")` as it gives the impression they may be directly contructed. Outside of tests, this is discouraged, as `manager.createEntityReference` shoud be used instead.
The present implementation avoids quoting the reference and skirts the issue of escaping angle brackes, as this should only be used for debug introspection.
We were discussing the right way to identify the class. The first commit opts for brevity (`<EntityReference ...>`). The other option, which is perhaps better from a broader software ecosystem perspective in [this commit](https://github.com/OpenAssetIO/OpenAssetIO/pull/1197/commits/e76e5a87f5d2290abf1d779848776d5167659092) extends this to `<openassetio.EntityReference ...>`. This could be dropped if desired. Thoughts? It …
> Add `__repr__` support to `EntityReference`

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/Context.hpp
- src/openassetio-core/src/trait/TraitsData.cpp
- src/openassetio-core/tests/ContextTest.cpp
- src/openassetio-core/tests/TraitsDataTest.cpp
- src/openassetio-python/cmodule/src/ContextBinding.cpp
- src/openassetio-python/cmodule/src/trait/TraitsDataBinding.cpp
- src/openassetio-python/tests/package/test_context.py
- src/openassetio-python/tests/package/test_traitsdata.py
Closes #1153. 
Ensure `TraitsData` copy-construction throws an error, rather than segfaults, if given a null `TraitsDataPtr` to copy from.
Ensure the default no-argument constructor of `Context` creates a blank (rather than null) `locale`, so that copy-construction of the `locale` (e.g. in `createChildContext`) can succeed. Note that direct construction of `Context` is non-standard (`createContext` should be used instead), but is still used e.g. in tests.
> Ensure non-null `TraitsData` copy-construction

- .github/workflows/build.yml
- RELEASE_NOTES.md
- doc/contributing/CODING_STANDARDS.md
- src/openassetio-core/include/openassetio/errors/exceptions.hpp
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/cmodule/src/_openassetio.hpp
- src/openassetio-python/cmodule/src/errors/exceptionsAsserts.cpp
- src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp
- src/openassetio-python/cmodule/src/hostApi/HostInterfaceBinding.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerImplementationFactoryInterfaceBinding.cpp
- src/openassetio-python/cmodule/src/log/LoggerInterfaceBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/EntityReferencePagerInterfaceBinding.cpp
- src/openassetio-python/cmodule/src/managerApi/ManagerInterfaceBinding.cpp
- src/openassetio-python/cmodule/src/overrideMacros.hpp
- src/openassetio-python/private/include/openassetio/private/python/exceptions.hpp
- src/openassetio-python/tests/cmodule/resources/_openassetio_test/errorsTest.cpp
- src/openassetio-python/tests/cmodule/test_errors.py
Closes #947. Establish a strategy for single-sourcing Python<->C++ exception mapping, add a mechanism to translate OpenAssetIO-specific Python exceptions to corresponding C++ exceptions, and augment the pybind11 override macros to do the translation.
This only affects pybind11 "trampoline" functions - i.e. C++ virtual methods that can call out to a Python implementation.
The final commit is optional. A comment in the GitHub issue mentions `createPythonPluginSystemManagerImplementationFactory`, so the final commit was added to be able to use the new functionality there. However, on inspection it didn't actually seem necessary.
Testing every affected class isn't tackled. Instead, the macros are tested via dedicated contrived `cmodule` (`_openassetio_test`) tests. Testing for all classes can …
> Python->C++ exception translation

- doc/doxygen/src/Examples.dox
This has been removed upstream in MediaCreation pending #1209, which will provide a first-class mechanism for managing resolving future entity properties.
This change hopefully keepps the example essentially "legal" in the mean time, albeit cumbersome.
Closes #1210
> [Docs] Remove `ResolvesFutureEntities` use in examples

- .github/workflows/integrations.yml
Following on from https://github.com/OpenAssetIO/OpenAssetIO/pull/1214 and https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/93
Re-enable BAL integration tests now that `entityTraits` is supported in BAL.
> Re-enable BAL integration tests

- src/openassetio-python/pyproject.toml
Causing CI to fail when building wheels, because wheel builds request the latest cmake version via pip.
Looks to be due to a genuine cmake bug,
https://discourse.cmake.org/t/3-28-segmentation-fault-on-macos-11-runner/9588
This is temporary, we should revert this once cmake has shipped a patch.
> [CI] Limit cmake version in wheel builds to < 3.28

- .github/workflows/integrations.yml
Part of https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/72
Can remove this dependency workaround now that BAL is sorted properly.
I think this is the only case of installing BAL dependencies in CI.
This should be merged after https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/pull/91, which is why this is a draft.
> [CI] Remove mediacreation workaround

- src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp
- src/openassetio-python/private/include/openassetio/private/python/exceptions.hpp
- src/openassetio-python/tests/cmodule/resources/_openassetio_test/errorsTest.cpp
- src/openassetio-python/tests/cmodule/test_errors.py
Closes #1225. 
The `HybridException` mechanism used multiple inheritance to allow an exception to be caught as either an OpenAssetIO exception or a pybind11 exception, allowing it to propagate from Python through C++ and back out to Python without losing information.
However, this entailed diamond inheritance, where the two branches of the inheritance hierarchy had a root base class of `std::exception`.
This meant that a `HybridException` could not be caught as a `std::exception` due to the ambiguity. Frustratingly, this manifests as if `std::exception` wasn't part of the hierarchy at all, at least on GCC, and the exception would simply fall through the `catch`.
So rework the `HybridException` mechanism to use composition, rather than inheritance. I.e. we compose the Python exception …
> [Python] Fix HybridException base class RTTI

- .github/workflows/upload-release-builds.yml
- doc/contributing/PROCESS.md
Boy that took a while ... CI iteration eh?
Adds CI steps to automatically publish release artifacts when a release is made.
Adds additional build configs (release, debug), to the existing build matrix in order to upload these, but does not allow these additional builds to be run on PR's, instead only running on main. Tripling the agents doing the build and test workflow during PR iteration seemed too heavy to me.
Closes #1201 
~~- [ ] I have updated the release notes.~~
You can see a test release here : https://github.com/elliotcmorris/OpenAssetIO/releases/tag/v1.0.0-test.26
and you can see on the actions page of this PR that only one configuration (RelWithDebugInfo) actually runs anything significant : https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/7464239504/job/20310775805?pr=1 …
> Publish build artifacts

- RELEASE_NOTES.md
- cmake/templates/include/openassetio/version.hpp.in
- doc/contributing/PROCESS.md
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/tests/CMakeLists.txt
- src/openassetio-core/tests/versionTest.cpp
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/cmodule/src/_openassetio.cpp
- src/openassetio-python/cmodule/src/_openassetio.hpp
- src/openassetio-python/cmodule/src/versionBinding.cpp
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/tests/package/test_version.py
Closes #1173
Add generated Version.hpp header with version macros and getter methods. This allows for runtime and compile time library version introspection in C++ and Python. Useful for potential compatibility conversions, as well as general pipeline usefulness.
C++ tests to test the macros, which are technically public interface
Python tests the actual numbers based on a manually updated string
> [Core] Add Version Introspection

- doc/contributing/CODE_REVIEWS.md
This came out of a Retrospective meeting discussion. We often wish to make a note of something that requires no action by the contributor, but did not have an appropriate feedback ladder tag for this.
> [Docs] Add `[comment]` to review feedback ladder

- doc/BUILDING.md
New dependencies were added for the `FilePathUrlConverter` added in #1117. However, we forgot to update the list of dependencies in the BUILDING.md doc.
Whoops.
> [Docs] Update BUILDING.md with new dependencies

- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/src/hostApi/Manager.cpp
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-python/cmodule/src/errors/BatchElementErrorBinding.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/test_batchelementerror.py
Closes #1239.
* Refactor tests of batch-first callback-based methods to use a common base class. The base class includes assertion methods to capture the commonality between the test cases for the various methods. This is less compact than it could be, since an attempt has been made to future-proof against upcoming convenience signatures for other methods.
* Create a `ManagerConveniences.cpp` and move convenience overloads from `Manager.cpp`.
> Refactor convenience signatures

- .github/workflows/code-quality.yml
- doc/BUILDING.md
- doc/decisions/DR017-Entity-version-queries.md
- doc/decisions/DR018-Result-pager-design.md
Part of #737 
Add CI checker that asserts all the links in markdown files are valid. Fix broken links throughout the repo.
> [CI] Add markdown link check

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/cmodule/gil/test_manager_gil.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #1217. The batch-first callback-based API introduces a lot of boilerplate for hosts that only need to query a single entity, or prefer error cases to be realised as exceptions or alternate result types. Other API methods already have convenience signatures wrapping the core callback-based API, but many are still missing these, `entityTraits` being one of them.
So add convenience signatures mirroring those that exist for other member functions (e.g. `resolve`), largely duplicating the format of the docstrings for `resolve`.
> [Core] Add convenience signatures for entityTraits

- .github/workflows/build.yml
- .github/workflows/integrations.yml
- .github/workflows/upload-release-builds.yml
Closes #1245. We removed the Conan `cpython` package dependency in #1038, meaning this preamble is no longer needed.
Removing this should enable yet further CI simplification, i.e. #1114.
> [CI] Remove MacOS LDFLAGS preamble

- .github/workflows/build-instructions.yml
- .github/workflows/build-vfx-reference-platform.yml
- .github/workflows/build.yml
- .github/workflows/code-quality.yml
- .github/workflows/integrations.yml
GitHub runners currently provide 4 vCPUs, so we can reduce our CI wait times by bumping our `ctest` invocations to make use of the full number of processes.
Note that for builds where we use the Ninja generator, the builds are automatically parallel.
- ~~[ ] I have updated the release notes.~~
- ~~[ ] I have updated all relevant user documentation.~~
> [CI] Bump parallelism for ctests

- doc/decisions/DR023-Versioning-traits-and-specifications-method.md
Closes https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/issues/83
So the previous attempt at DR23 was, as we soon discovered, both underthought and attempting to tackle too much.
This DR attempts to take the learnings from that and make a more measured decision on a very specific point, which seems to be the root of the issue, that being in-data or out-of-data versioning.
Add initial draft of DR exploring mechanism of communicating trait and specifications library version in an OpenAssetIO session.
> [Docs] Add DR23 (again), trait versioning method

- doc/decisions/DR024-Manager-capability-introspection.md
Adds a (retrospective) DR that attempts to capture the rationale behind the current design of `managementPolicy`, and why it is constrained by trait set/access. Much of this information has been lost over the years, so this aims to help clarify prior decision's and inform any future iteration so the tradeoffs are better understood.
This is actually from this DR by @themissingcow : https://github.com/OpenAssetIO/OpenAssetIO/pull/1281, just moved over to my remote because of permissions issues.
> [Docs] Add DR for `managementPolicy` design

- src/openassetio-core/include/openassetio/managerApi/ManagerInterface.hpp
The docs for `ManagerInterface.getWithRelationship`(`s`) was polluted by docs that only make sense in `Manager.getWithRelationship`(`s`), i.e. how to access paged data, as opposed to how to provide it.
> [Docs] ManagerInterface.getWithRelationship doc fix

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/_implementation.py
- src/openassetio-python/tests/package/test/manager/test__implementation.py
When a python plugin of the provided identifier cannot be found when loading a test plugin, fallback to attempting to load a c++ plugin.
As specified during refinement, testing only that the initialisation of the factory is provided the correct type of implementation factory, via mocks, as the functionality for the `ManagerFactory` to load plugins once provided a correct implementation factory is tested elsewhere
Closes #1294
> [Test] Load C++ plugins in test harness

- .github/workflows/build-wheels.yml
- CMakeLists.txt
- CMakePresets.json
- RELEASE_NOTES.md
- cmake/Testing.cmake
- resources/build/Dockerfile
- resources/build/bootstrap-ubuntu-20.04.sh
- resources/build/requirements.txt
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/pyproject.toml
- src/openassetio-python/setup.py
- src/openassetio-python/tests/cmodule/resources/_testutils/gilTest.cpp
- src/openassetio-python/tests/package/_openassetio/test_pyi.py
Closes #1252. IDEs can use .pyi stub files located in the package to greatly enhance code-completion and documentation for Python C extension modules.
Add as part of `setup.py` installs, as well as CMake via new `OPENASSETIO_ENABLE_PYTHON_STUBGEN` variable (`ON` by default).
Note that stubs wont install with `pip install --editable`.  We can install them, but in local testing neither PyCharm nor Visual Studio Code could use them.
Worth checking alternative IDEs.
> Add .pyi stub generation

- RELEASE_NOTES.md
- examples/host/simpleResolver/test_simpleResolver.py
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystem.py
- src/openassetio-python/tests/bridge/resources/modulePlugin.py
- src/openassetio-python/tests/package/pluginSystem/conftest.py
- src/openassetio-python/tests/package/pluginSystem/resources/deprecated/deprecatedPlugin.py
- src/openassetio-python/tests/package/pluginSystem/resources/entryPoint/src/packaged_plugin/__init__.py
- src/openassetio-python/tests/package/pluginSystem/resources/pathA/modulePlugin.py
- src/openassetio-python/tests/package/pluginSystem/resources/pathB/packagedPlugin/__init__.py
- src/openassetio-python/tests/package/pluginSystem/resources/pathC/modulePlugin.py
- src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystem.py
- src/openassetio-python/tests/package/test/manager/resources/plugins/StubManager.py
Deprecate the top level `plugin` variable for the python plugin system in favour of the `openassetioPlugin` variable.
Closes #1290
> [Python] Deprecate `plugin` hook.

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/cmodule/gil/test_manager_gil.py
- src/openassetio-python/tests/conftest.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #973
Adds standard set of singular/batch conveniences for getWithRelationship(s), for both exceptional and variant error modalities.
Due to the inability to use the test framework for conveniences, it's all a bit rough & ready. I'm hoping just a happy path and a failure case are enough considering the scope of duplication involved.
Docs are in another commit. Just sort of worked out this way but I thought it's probably a better reviewer experience so left it like that. Will squash after.
Good luck trying to keep all the variations strait in your head when looking at docs & bindings ... I really struggled.
> GetWithRelationship(s) conveniences

- doc/contributing/PROCESS.md
This came out of a team retrospective action to address an issue whereby OpenAssetIO core was released with a breaking change, but the corresponding update to BAL (Basic Asset Library) was not yet ready. This meant there was a non-trivial period where the latest published version of BAL was incompatible with the latest published version of OpenAssetIO core. This then had a knock-on effect to host integrators, who could not use BAL to test conformance with the latest OpenAssetIO core API.
So update our release process so that we always consider if other projects in the ecosystem must be released simultaneously, and if so ensure they are ready for release, before finalising the OpenAssetIO core release.
> [Docs] Consider dependent projects in release process

- RELEASE_NOTES.md
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/include/openassetio/utils/substitute.hpp
- src/openassetio-core/src/utils/substitute.cpp
- src/openassetio-python/cmodule/src/utilsBinding.cpp
- src/openassetio-python/package/openassetio/utils.py
- src/openassetio-python/tests/package/utils/test_FileUrlPathConverter.py
- src/openassetio-python/tests/package/utils/test_substitute.py
Closes #1213. Many strings communicated between a host and a manager may contain placeholder tokens that are intended to be substituted by the host before use, e.g. an animated image sequence on disk as several files similarly named, except for a frame number, could be referred to collectively using `image.{frame}.exr`.
However, how is the host/manager to know what syntax to use for placeholder tokens, when they are, in general, separately developed codebases?
A related problem is how the host/manager knows whether and what placeholder tokens are allowed in a given string? This question has been moved out of the core library to be an industry-specific concern. Check the docs in the MediaCreation repository; but in short, the documentation of individual traits and properties dictate the …
> Add `substitute` utility function

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/errors/BatchElementError.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/errors/exceptionMessages.cpp
- src/openassetio-core/src/errors/exceptionMessages.hpp
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-core/tests/.clang-tidy
- src/openassetio-core/tests/BatchElementErrorTest.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/cmodule/gil/test_manager_gil.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #1169. Add overloads for `entityExists`, similar to other API methods. I.e. singular vs. batch, exception vs. result (variant).
Also fix a few sundry issues found along the way. 
In particular, for convenience overloads of various methods, add test cases for the default response when the manager is naughty and doesn't call any callback.
Hence set the default `code` of `BatchElementError` to `kUnknown` - this closes #1298.
> `entityExists` conveniences

- resources/build/conanfile.py
- src/openassetio-python/pyproject.toml
The tomlplusplus recipe got updated to include support for setting exceptions enabled explicitly.
Unfortunately, this seemed to disable exceptions no matter what. Pinning until this is resolved.
https://github.com/conan-io/conan-center-index/pull/24336
This was found by our `cibuildwheel` tests. As that runs in a fresh container each time. It dosen't have a conancache to depend on, so got the new recipe strait away. https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/9560287692/job/26352138550
> [Build] Pin tomlplusplus recipe

- src/openassetio-core/src/BatchElementError.cpp
Discovered whilst working on OpenAssetIO/usdOpenAssetIOResolver#39, which required use of VFX Reference Platform CY23, i.e. GCC 11. We currently work on CY22, i.e. GCC 9.3.
When bumping to GCC 11 `-Werror` causes the build to fail with `-Werror=deprecated-declarations` because we deliberately include the deprecated `BatchElementException` types in the binary, to satisfy symbol discovery on Windows.
The fact this isn't flagged as an error when compiling with GCC 9.3 is probably a deficiency in that compiler version.
> Disable internal BatchElementError deprecation warnings

- resources/build/conanfile.py
- src/openassetio-python/pyproject.toml
An update to the Conan recipe for tomlplusplus meant that exceptions were disabled and there was no way to re-enable them, so we had to pin the recipe to the previous revision.
An upstream fix has now been pushed (conan-io/conan-center-index#24385), so we can revert the recipe revision pin.
> Revert tomlplusplus recipe revision pin

- RELEASE_NOTES.md
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/include/openassetio/utils/ostream.hpp
- src/openassetio-core/src/utils/formatter.cpp
- src/openassetio-core/src/utils/formatter.hpp
- src/openassetio-core/src/utils/ostream.cpp
- src/openassetio-core/tests/CMakeLists.txt
- src/openassetio-core/tests/utils/PrintableTest.cpp
- src/openassetio-python/cmodule/src/ContextBinding.cpp
- src/openassetio-python/cmodule/src/EntityReferenceBinding.cpp
- src/openassetio-python/cmodule/src/errors/BatchElementErrorBinding.cpp
- src/openassetio-python/cmodule/src/trait/TraitsDataBinding.cpp
- src/openassetio-python/tests/package/test_batchelementerror.py
- src/openassetio-python/tests/package/test_entityreference.py
- src/openassetio-python/tests/package/test_traitsdata.py
- src/openassetio-python/tests/package/utils/test_printable.py
Add fmt formatters for most useful OpenAssetIO types.
Wrap this internal formatting behaviour to implement public <<
operators for logging and printing.
Not totally consistent, and not totally all-encompasing either. Lots of decisions were made in a pairing context.
Closes #1307
Kept a bit split between python and C++ just for review convenience.
> Printable TraitsData + other types.

- .github/workflows/build-vfx-reference-platform.yml
- .github/workflows/code-quality.yml
We have CI tests that use our Docker image, which is based on the ASWF VFX Reference Platform 2022 image, whose glibc version is rather old. This makes it incompatible with Node 20. We have been holding back the
version of `actions/checkout` to ensure Node 16 was still used. However, GitHub have started forcing Node 20 regardless. 
See
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Example failure [here](https://github.com/OpenAssetIO/OpenAssetIO/actions/runs/9807282377/job/27080742052?pr=1342)
That link gives a way to buy more time on Node 16 via a `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION` env var, which we can use for now.
The real fix will be to upgrade our Docker image, which will be done in …
> [CI] Allow use of Node 16

- cmake/DefaultTargetProperties.cmake
We were needlessly repeating the same work to compute platform warnings and IPO capability in the `openassetio_set_default_target_properties` function every time it was called.
On Linux the slowdown is barely noticeable. However, on Windows the slowdown is frustrating. A re-configure of a hot build directory goes down from 1 min 43 secs before this commit to a mere 8 secs, on Windows.
> Improve speed of CMake configure

- RELEASE_NOTES.md
- doc/doxygen/src/Examples.dox
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/cmodule/gil/test_manager_gil.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #856. There are many cases where hosts only need to query a single trait set.
So provide a convenient overload that takes a single trait set and returns a single policy `TraitsData`.
Ensure the result from the manager plugin is bounds checked, to avoid segfault. However, we don't use a custom human-readable exception, since that case is truly exceptional - it is against the API contract and so should never happen.
> Singular managementPolicy overload

- .github/workflows/integrations.yml
- CMakeLists.txt
- CMakePresets.json
- README.md
- RELEASE_NOTES.md
- cmake/ThirdParty.cmake
- examples/README.md
- examples/host/simpleResolver/simpleResolver.py
- examples/host/simpleResolver/test_simpleResolver.py
- examples/manager/SimpleCppManager/CMakeLists.txt
- examples/manager/SimpleCppManager/README.md
- examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
- examples/manager/SimpleCppManager/tests/CMakeLists.txt
- examples/manager/SimpleCppManager/tests/resources/fixtures.py
- examples/manager/SimpleCppManager/tests/resources/openassetio_config.toml
- examples/manager/SimpleCppManager/tests/test_SimpleCppManager.py
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
Closes #1324. OpenAssetIO now supports C++ plugins. However, the only C++ plugins that currently exist are stubs used in the unit tests, and these are insufficient for testing the usage of C++ plugins by host applications.
So add a simple C++ manager/plugin combination that only supports the minimal required capabilities plus `resolve`.
Also see https://github.com/OpenAssetIO/OpenAssetIO/issues/1340
> Add SimpleCppManager

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/harness.py
Discovered whilst working on OpenAssetIO/OpenAssetIO-Manager-BAL#84.
When developing test cases for the `openassetio.test.manager` API Compliance test suite, it is extremely useful to have code completion for the injected `Manager` instance (`self._manager`).
The previous PyCharm-specific type hint for `self._manager` no longer worked,  and the hint for `self._locale` was just plain wrong.
So use real type hints for these members.
> Add type hint to API Compliance cases for Manager

- examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
- examples/manager/SimpleCppManager/tests/test_SimpleCppManager.py
Part of #1202. The upcoming hybrid plugin system will work by locating multiple plugins that all advertise the same unique identifier and combining them.
In preparation for e2e testing of this, make the plugin identifier of SimpleCppManager configurable, so that it can be set to the same identifier as another plugin on the system.
See https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/pull/99 for context.
> Allow overriding of SimpleCppManager identifier

- examples/manager/SimpleCppManager/src/SimpleCppManager.cpp
- examples/manager/SimpleCppManager/tests/test_SimpleCppManager.py
Discovered whilst working on #1202. When capabilities were explicitly given as a list in the settings, the pre-existing capability set was not reset, meaning it wasn't possible to "switch off" the default capabilities.
So `clear()` the capability set when settings are detected that should override it, before filling up the set again with those settings.
> Fix SimpleCppManager override default capabilities

- .github/workflows/build-wheels.yml
- README.md
- RELEASE_NOTES.md
- doc/BUILDING.md
- doc/contributing/CODING_STANDARDS.md
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystem.py
- src/openassetio-python/pyproject.toml
- src/openassetio-python/tests/package/pluginSystem/resources/broken/src/missing_plugin/pyproject.toml
- src/openassetio-python/tests/package/pluginSystem/resources/broken/src/raises_exception/pyproject.toml
- src/openassetio-python/tests/package/pluginSystem/resources/entryPoint/src/pyproject.toml
- src/openassetio-python/tests/package/test/manager/test_main.py
Part of #1340, but it's been coming for a while.
The trigger for finally doing this is the need for `os.add_dll_directory` support.
So removed Python 3.7 PyPI distributions, and all mention of it from the codebase.
The new minimum supported Python version is now 3.9. The older versions may continue to work for a time, but this is no longer guaranteed nor supported.
> Remove support for Python 3.7

- .github/workflows/build-instructions.yml
- .github/workflows/integrations.yml
- CMakeLists.txt
- CMakePresets.json
- RELEASE_NOTES.md
- cmake/Testing.cmake
- doc/BUILDING.md
- doc/doxygen/src/Glossary.dox
- examples/manager/SimpleCppManager/CMakeLists.txt
- examples/manager/SimpleCppManager/tests/CMakeLists.txt
- src/openassetio-core/CMakeLists.txt
- src/openassetio-python/bridge/CMakeLists.txt
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/package/openassetio/_windows.py
- src/openassetio-python/setup.py
- src/openassetio-python/tests/package/test__windows.py
Closes #1340. 
Building OpenAssetIO as a static library almost certainly precludes loading C++ manager plugins.  This is due to plugins depending explicitly on the OpenAssetIO core C++ shared library and/or depending on the symbols of that library being exported and public, in order to link properly at runtime.
The most straightforward and universal fix to this is to ensure OpenAssetIO is only ever built as a bunch of shared libraries.
So update the Python distribution to bundle OpenAssetIO as several shared libraries, rather than a single extension module.
When building/installing as a CMake package on Windows, we must unfortunately duplicate the dlls, with one copy in the `lib` subdirectory, for use by C++ consumers, and one copy in the `site-packages/openassetio` directory, for use by …
> Fix C++ plugin loading from Python

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/hostApi/terminology.py
- src/openassetio-python/tests/package/hostApi/test_terminology.py
Discovered whilst working on  #1202. Since the `updateTerminology` API methods were moved to C++, the input terminology dictionary is no longer mutated. Instead, the dictionary is copied (by the Python bindings), and the manager plugin is expected to return a mutated copy.
The `Mapper` class was still assuming the input terminology dict would be mutated. This was never detected in the unit tests, because we were erroneously subclassing `Manager` rather than `ManagerInterface`, and so short-circuiting the Python->C++->Python code path.
So refactor the tests to instead create a mock `ManagerInterface` and catch this problem. Fix the problem by overwriting the `Mapper`'s internal terminology dictionary, rather than expecting it to be mutated.
> Fix terminology `Mapper` initialisation

- CMakeLists.txt
- cmake/Testing.cmake
Discovered whilst debugging #1340. When using a multi-config CMake generator (e.g. Visual Studio), running `ctest` would fail because the active configuration (Release, Debug, etc) wasn't propagated to the CMake subprocesses responsible for building/installing/running. The symptom, on Windows, was errors trying to link Release artifacts to Debug artifacts causing MSVCRT mismatches.
So fix the custom CMake subprocess targets so that the active configuration is propagated.
> Fix CTest for multi-config generators

- doc/BUILDING.md
Discovered whilst working on #1340. Some of our build instructions are out of date.
Requirements for CMake was too low, and pybind11-stubgen is a build requirement by default.
The warnings relating to Python were out of date, since they were written back when we used/recommended the `cpython` ConanCenter package. This had a bunch of problems (see #977), so we moved to relying on the system/user-provided Python.
Add some missing CMake options.
Remove docs for coverage and C API options. Coverage has never been tested and should be considered unsupported. The C API is woefully incomplete and needs rethink, so should be considered deprecated/unsupported.
> Fix outdated BUILDING instructions

- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystem.py
In #1115 we changed from `plugin` to `openassetioPlugin` for the hook that Python plugins must define, to better match the C++ plugin system, and head off any potential ambiguities.
However, we missed a docstring, which was still referring to the deprecated `plugin`. So update it.
> Update deprecated hook in scan_entry_points docstring

- RELEASE_NOTES.md
- src/openassetio-python/package/openassetio/test/manager/apiComplianceSuite.py
Part of #1202. The upcoming hybrid plugin system will allow multiple manager plugins that advertise the same unique ID to be initialised together and composed.
If the settings passed to the constituent manager plugins must be tailored for each one, then significant extra work must be done to design and implement a way to disambiguate and split up the settings.
A much simpler solution is to allow an arbitrary settings dict to be passed to a manager, and they can select which settings they are interested in. This way we can provide a single settings dictionary (as provided, for example, by the OpenAssetIO `.toml` config file mechanism), and distribute that single dict to all child plugins of a hybrid plugin.
The disadvantage is if two plugins require the same key to map to a different …
> Allow API compliance if `initialize`d with unknown settings

- RELEASE_NOTES.md
- src/openassetio-python/cmodule/src/hostApi/EntityReferencePagerBinding.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerFactoryBinding.cpp
- src/openassetio-python/cmodule/src/pluginSystem/CppPluginSystemBinding.cpp
- src/openassetio-python/cmodule/src/pluginSystem/CppPluginSystemManagerImplementationFactoryBinding.cpp
Discovered whilst working on #1202.
When a Python script defines a class that inherits from a C++ class, the natural expectation would be that calls to an overridden method in C++ via a C++ base class reference would call out to the Python method implementation.
However, this is not the case unless we have explicitly enabled it in the bindings by providing a so-called "trampoline" class.
So to prevent confusion, we add a tag to the Python bindings to declare the class as "final", so that it is an error at Python import time when a class inherits from that C++ class.
However, there were several classes that we had never added the `is_final` tag to.
So add this tag to appropriate Python bindings.
Also add to `CppPluginSystemManagerImplementationFactory`, despite it defining a trampoline …
> Make non-subclassable C++ Python bindings classes `final`

- RELEASE_NOTES.md
- doc/contributing/CODING_STANDARDS.md
- src/openassetio-core/include/openassetio/trait/collection.hpp
- src/openassetio-core/src/trait/TraitsData.cpp
- src/openassetio-core/tests/typedefsTest.cpp
Closes #1339.
C++ has set operation algorithms. However, these only work for sorted containers. `std::unordered_set` is not a sorted container, and so (ironically) cannot use set operations.
Most of our prototyping has been done in Python, where set operations are a part of the core language, and we have used them extensively to compare and combine trait sets.
The main benefit of `unordered_set` is the better average-case time complexity. However, for small sets the difference in performance between `std::set` and `std::unordered_set` is negligible (and may even favour `std::set`). In practice, we haven't seen any large 100k+ trait sets in the wild, which is where we'd expect the performance difference to show up (see links in GitHub issue for details).
Clearly this is a breaking change. …
> Use `std::set` for trait sets

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/errors/BatchElementError.hpp
- src/openassetio-core/include/openassetio/errors/errorCodes.h
- src/openassetio-core/src/errors/exceptionMessages.cpp
- src/openassetio-python/cmodule/src/errors/BatchElementErrorBinding.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
- src/openassetio-python/tests/package/test_batchelementerror.py
Closes #1009. 
Add a `kAuthError` error code to `BatchElementError`s so that manager's have a means to inform the user that they do not (currently) have access to an action or asset.
This then allows host applications to branch differently on authentication or authorization related errors, if they wish.
> Add kAuthError error code

- src/openassetio-core/tests/typedefsTest.cpp
Back in #918 we started ensuring that classes that have reference semantics (i.e. most objects, because Python) have a set of aliases to their associated `shared_ptr`s. To enforce this we added tests, but have not kept the tests up to date as new classes have been added.
So add the missing classes to the test.
Unfortunately there is no easy way to ensure these tests are kept up to date, other than remembering that they're there (or coming across them again months later).
> Add missing shared_ptr alias tests

- doc/doxygen/src/Configuration.dox
- doc/doxygen/src/Examples.dox
- doc/doxygen/src/ForHosts.dox
- doc/doxygen/src/ForManagers.dox
- doc/doxygen/src/Glossary.dox
- doc/doxygen/src/MainPage.dox
- doc/doxygen/src/Testing.dox
- examples/host/simpleResolver/simpleResolver.py
- src/openassetio-core/CMakeLists.txt
- src/openassetio-core/include/openassetio/pluginSystem/HybridPluginSystemManagerImplementationFactory.hpp
- src/openassetio-core/src/pluginSystem/HybridPluginSystemManagerImplementationFactory.cpp
- src/openassetio-core/tests/typedefsTest.cpp
- src/openassetio-python/cmodule/CMakeLists.txt
- src/openassetio-python/cmodule/src/_openassetio.cpp
- src/openassetio-python/cmodule/src/_openassetio.hpp
- src/openassetio-python/cmodule/src/pluginSystem/HybridPluginSystemManagerImplementationFactoryBinding.cpp
- src/openassetio-python/package/openassetio/pluginSystem/__init__.py
- src/openassetio-python/package/openassetio/test/manager/_implementation.py
- src/openassetio-python/tests/cmodule/gil/test_managerfactory_gil.py
- src/openassetio-python/tests/package/pluginSystem/test_hybridpluginsystemmanagerimplementationfactory.py
- src/openassetio-python/tests/package/test/manager/test__implementation.py
Closes #1202.
OpenAssetIO currently supports two different manager plugin backends in the core library, Python and C++. We expect more backends to be added in the future. For example, there has been active investigation into a gRPC backend.
By "backend" we specifically mean an implementation of the abstract base class `ManagerImplementationFactoryInterface`. The host application chooses an implementation, then injects it into a `ManagerFactory`, which is then responsible for producing `Manager` instances that the host application can use.
The idea of a hybrid plugin system is to allow multiple backend plugin providers to be composed, such that API calls can be routed to the most appropriate plugin. For example, performance-critical API requests could route to a C++ plugin, whilst less …
> Add hybrid plugin system

- doc/doxygen/README.md
Changing this due to this error I received on my Windows 11 machine when trying to build the docs.
```
docker: invalid reference format: repository name (OpenAssetIO/openassetio-doc-build) must be lowercase.
```
> Remove docker command from Doxygen README 

- .github/workflows/integrations.yml
Re-enable integration tests on Ubuntu now that downstream repos have been updated to work with the changes from https://github.com/OpenAssetIO/OpenAssetIO/pull/1391.
> Re-enable integration tests on Ubuntu 

- .github/markdown-link-check-config.json
- .github/workflows/code-quality.yml
- doc/doxygen/src/MainPage.dox
- examples/README.md
Closes #1399. Add a link to the Ftrack manager plugin in the `examples/README.md`. Also update the Doxygen API docs main page to link to this README rather than maintaining a separate list of examples.
To build the docs
```
cd docs/doxygen
make
```
The docs will be placed in a `html` directory under `docs/doxygen`.
> Add link to Ftrack plugin

- RELEASE_NOTES.md
- ROADMAP.md
- cmake/templates/include/openassetio/version.hpp.in
- doc/contributing/PROCESS.md
- doc/contributing/PULL_REQUESTS.md
- doc/doxygen/Doxyfile
- doc/doxygen/src/MainPage.dox
- src/openassetio-core/tests/versionTest.cpp
- src/openassetio-python/cmodule/src/versionBinding.cpp
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/pyproject.toml
- src/openassetio-python/tests/package/test_version.py
Closes #1401. Bump from beta to release candidate. 
Remove "beta" version introspection functions. We could have adapted these somehow, but that would be a lot of work for no current use-case.
> [Release] Bump version to v1.0.0-rc.1.0 

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/src/errors/exceptionMessages.cpp
- src/openassetio-core/src/errors/exceptionMessages.hpp
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-python/cmodule/src/hostApi/ManagerBinding.cpp
- src/openassetio-python/tests/cmodule/gil/test_manager_gil.py
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #1170. Add overloads for `defaultEntityReference`, similar to other API methods. I.e. singular vs. batch, exception vs. result (variant).
> Add convenience signatures for `defaultEntityReference`

- RELEASE_NOTES.md
- src/openassetio-python/cmodule/src/errors/exceptionsBinding.cpp
- src/openassetio-python/tests/cmodule/resources/_testutils/errorsTest.cpp
- src/openassetio-python/tests/cmodule/test_errors.py
Closes #1419. If a C++ exception occurs in a pybind11-bound C++ function, then we attempt to translate the C++ exception to a Python exception. As part of this we execute Python statements, in-particular we import `openassetio._openassetio.errors`. Attempting to do this import whilst the Python error indicator is set causes a fatal error in Python.
This can happen if e.g. in the call stack of a pybind11-bound function, some C++ code uses the CPython API, which triggers a Python exception, but then the C++ code goes on to throw its own exception too.
So handle this case by fetching the pre-existing exception, and setting the `__cause__` and `__context__` of the newly translated C++->Python exception.
The code duplicates the logic in `pybind11::raise_from`. We can't use that function …
> C++->Python exception "raise from" support

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/EntityReference.hpp
- src/openassetio-core/tests/CMakeLists.txt
- src/openassetio-core/tests/EntityReferenceTest.cpp
- src/openassetio-python/cmodule/src/EntityReferenceBinding.cpp
- src/openassetio-python/tests/package/test_entityreference.py
Closes #573. Entity references used to be simple strings. Now they are a strong type and lose the conveniences that come with strings.
In particular, they could not be used as keys in associative containers, in Python nor C++.
So add operators and hashing in both C++ and Python that allow entity references to be used in containers.
For completeness, add the similar operators that are not technically needed for container support, but may be useful in other situations. In particular noting that Python infers partner operators (e.g. `>` from `<`) whereas C++ (17) does not. So adding explicit support for these to C++ provides parity with Python functionality.
> `EntityReference` associative container support

- RELEASE_NOTES.md
- src/openassetio-core/src/hostApi/ManagerConveniences.cpp
- src/openassetio-python/tests/package/hostApi/test_manager.py
Closes #1196
An external manager plugin is expected to provide an implementation of a `ManagerInterface`. Most of its methods are batch-first and callback-based. That is, the manager plugin is expected to call a callback with the result for each element of an input batch. As such, the various callback signatures take an index argument to address a particular element in the batch.
The host-facing `Manager` middleware wraps the plugin's `ManagerInterface`. The `Manager` class adds convenience overloads that wrap each callback-based method provided by the plugin. These convenience methods include `std::vector`-returning signatures, where the `std::vector` is populated as callbacks are called, before being returned.
If the manager provides an invalid index as an argument to the callback, then …
> Bounds check array access in `Manager` convenience overloads

- README.md
- doc/decisions/DR019-Remove-access-from-the-context.md
- doc/decisions/DR023-Versioning-traits-and-specifications-method.md
- examples/host/simpleResolver/README.md
- examples/host/simpleResolver/simpleResolver.py
- src/openassetio-python/package/openassetio/__init__.py
- src/openassetio-python/pyproject.toml
Closes #1400. ASWF has set up a CNAME record for us for docs.openassetio.org, and this looks more polished.
Note that we have a CI job, markdown-link-check, that will check the URLs in markdown files.
> [Docs] Update API docs URL to docs.openassetio.org

- .github/workflows/build-vfx-reference-platform.yml
- .github/workflows/build-wheels.yml
- .github/workflows/build.yml
- .github/workflows/deploy-pypi.yml
`actions/upload-artifact` v3 is now unavailable on GitHub CI and is causing builds to fail, e.g. https://github.com/OpenAssetIO/OpenAssetIO/pull/1443
We had previously skipped a dependabot update due to NodeJS version requirement conflict with the old VFX22 Docker image, see #1232. Since we're now testing on VFX24 this shouldn't be a problem.
> [CI] Bump actions/upload-artifact to v4

- .github/markdown-link-check-config.json
For a few weeks now the `https://www.gnu.org/software/make` link in `docs/doxygen/README.md` frequently fails the `markdown-link-check` CI job with
```
ERROR: 1 dead links found!
[✖] https://www.gnu.org/software/make/ → Status: 0
```
That link invariably works when tried locally, yet fails most (but not all) of the time when `markdown-link-check` tries it on a GitHub runner.
So simply add a suppression for `https://www.gnu.org`.
> [CI] Add a suppression for GNU Make web link fail

- src/openassetio-core/include/openassetio/errors/exceptions.hpp
Discovered during #1445. This exception type seems to have slipped the net. It was designed for #1072, to be used in middleware classes such as `Manager`, whereby exceptions that are not derived from `OpenAssetIOException` and are thrown from a plugin's method would be caught and transformed into an `UnhandledException` and re-thrown. This was to allow hosts to detect exceptions that are caused by its OpenAssetIO integration.
However, that mechanism was never added, yet `UnhandledException` was added, with a docstring making false claims.
Removing the exception type is a breaking change, as is adding the functionality it was designed for (not to mention it's a lot of work for a potentially undesirable feature). So for now simply blank the erroneous docstring.
> Remove docs for UnhandledException

- doc/contributing/CODING_STANDARDS.md
When adding a new type to the OpenAssetIO API it can be easy to miss one or more of the many places scattered throughout the codebase that must be updated to properly support and test the type, even for devs with in-depth knowledge of the codebase.
So add a brief checklist to CODING_STANDARDS that can act as a memory aid. Don't go into much detail on what each bullet point means - explanations are located elsewhere, either within that same document or in the codebase.
> Add new type contribution checklist

- RELEASE_NOTES.md
- doc/doxygen/Doxyfile
- src/openassetio-core/include/openassetio/constants.hpp
- src/openassetio-core/include/openassetio/hostApi/HostInterface.hpp
- src/openassetio-python/cmodule/src/constantsBinding.cpp
- src/openassetio-python/package/openassetio/hostApi/HostInterface.py
- src/openassetio-python/package/openassetio/hostApi/__init__.py
- src/openassetio-python/tests/cmodule/resources/_testutils/CMakeLists.txt
- src/openassetio-python/tests/cmodule/resources/_testutils/HostInterfaceTest.cpp
- src/openassetio-python/tests/cmodule/resources/_testutils/_testutils.cpp
- src/openassetio-python/tests/cmodule/test_HostInterface.py
- src/openassetio-python/tests/package/hostApi/test_hostinterface.py
- src/openassetio-python/tests/package/test_constants.py
Part of #1445. OpenAssetIO is a mostly seamless dual-language library, but for some access patterns it may be necessary for managers to be aware that the host is written in Python to ensure correct behaviour.
For example, UI delegation may require UI elements to be passed to the host as Python object wrappers around native UI elements.
> Add "isPython" to `HostInterface.info()`

- RELEASE_NOTES.md
- src/openassetio-core/include/openassetio/pluginSystem/CppPluginSystem.hpp
- src/openassetio-core/include/openassetio/pluginSystem/CppPluginSystemManagerImplementationFactory.hpp
- src/openassetio-core/include/openassetio/pluginSystem/CppPluginSystemPlugin.hpp
- src/openassetio-core/src/hostApi/ManagerFactory.cpp
- src/openassetio-core/src/pluginSystem/CppPluginSystem.cpp
- src/openassetio-core/src/pluginSystem/CppPluginSystemManagerImplementationFactory.cpp
- src/openassetio-python/cmodule/src/pluginSystem/CppPluginSystemBinding.cpp
- src/openassetio-python/cmodule/src/pluginSystem/CppPluginSystemManagerImplementationFactoryBinding.cpp
- src/openassetio-python/cmodule/src/pluginSystem/CppPluginSystemPluginBinding.cpp
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystem.py
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystemManagerImplementationFactory.py
- src/openassetio-python/tests/cmodule/gil/test_cpppluginsystem_gil.py
- src/openassetio-python/tests/cmodule/resources/_testutils/gilTest.cpp
- src/openassetio-python/tests/package/hostApi/test_managerfactory.py
- src/openassetio-python/tests/package/pluginSystem/conftest.py
- src/openassetio-python/tests/package/pluginSystem/resources/pathB/packagedPlugin/PackagePlugin.py
- src/openassetio-python/tests/package/pluginSystem/resources/pathB/packagedPlugin/__init__.py
- src/openassetio-python/tests/package/pluginSystem/test_cpppluginsystem.py
- src/openassetio-python/tests/package/pluginSystem/test_cpppluginsystemmanagerimplementationfactory.py
- src/openassetio-python/tests/package/pluginSystem/test_cpppluginsystemplugin.py
- src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystem.py
- src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystemmanagerimplementationfactory.py
Part of #1445. In preparation for adding new types of plugin (i.e. UI delegates), refactor the C++ and Python plugin systems to move more logic into the common `CppPluginSystem` and `PythonPluginSystem` utility classes.
These changes do require a breaking change to the `CppPluginSystem` and `PythonPluginSystem` APIs. However, except for extremely unlikely advanced use-cases, these classes are an implementation detail, so changing their API should not cause any downstream breakages.
> Refactor plugin systems for re-usability

- src/openassetio-core/src/pluginSystem/CppPluginSystem.cpp
- src/openassetio-core/tests/CMakeLists.txt
- src/openassetio-core/tests/pluginSystem/CppPluginSystemTest.cpp
- src/openassetio-python/package/openassetio/pluginSystem/PythonPluginSystem.py
- src/openassetio-python/tests/package/pluginSystem/test_cpppluginsystem.py
- src/openassetio-python/tests/package/pluginSystem/test_cpppluginsystemmanagerimplementationfactory.py
- src/openassetio-python/tests/package/pluginSystem/test_pythonpluginsystem.py
~~Closes # (issue)~~
Typically, a host application will want to enable both Python and C++ manager plugins (via the Hybrid plugin system).
Python plugins support either `OPENASSETIO_PLUGIN_PATH` environment variable or Python entry-point plugins
(`importlib.metadata.entry_points)`. C++ plugins only support `OPENASSETIO_PLUGIN_PATH`.
We would like to warn the user when there is no possibility of loading a manager plugin, because neither entry-point nor
`OPENASSETIO_PLUGIN_PATH` is configured.
Conversely, we do _not_ want to issue this warning if one of these mechanisms is available.
However, we had a situation where, if `OPENASSETIO_PLUGIN_PATH` is not set, because the user expects a Python entry-point plugin to be used instead, then the C++ plugin system would still warn that no plugins …
> Reduce severity of CppPluginSystem search path warning

- src/openassetio-core/include/openassetio/errors/BatchElementError.hpp
- src/openassetio-core/include/openassetio/hostApi/Manager.hpp
- src/openassetio-core/include/openassetio/utils/path.hpp
- src/openassetio-core/src/utils/Regex.hpp
Closes #1179. Plus sundry other docs fixes.
`kEntityAccessError` still referred to `Context.access`, which was removed in #1054.
The exception raised, when `register()` is called with mismatched entity reference and traits data list lengths, was changed from `std::out_of_range` to our custom `InputValidationException` in #1071.
Windows `FileUrlPathConverter.pathFromUrl()` handling for `file://` URLs that, when decoded to a file path, exceeds the Windows MAX_PATH limit, was changed in #1257 to automatically convert to UNC device path style `\\?\`.
The `Regex` PCRE2 wrapper class, when initially written, was stateful and so not thread-safe. However, that was changed upon review (https://github.com/OpenAssetIO/OpenAssetIO/pull/1246#discussion_r1465151326), but the docstring was not updated …
> Fix a few out-of-date docs

- .github/markdown-link-check-config.json
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- RELEASE.md
- ROADMAP.md
- SUPPORT.md
- doc/contributing/PROCESS.md
- examples/README.md
In preparation for the project moving to the ASWF incubation phase, add various docs at the root level covering project governance and contribution guidelines, as listed in the annual review slide template (available [here](https://tac.aswf.io/process/review_cycle.html)) listing requirements for an Incubation stage project.
> Add project docs as per ASWF guidelines

- ADOPTERS.md
In preparation for acceptance for the ASWF Incubation project stage, add the last remaining requirement with respect to documentation add an ADOPTERS file, which simply points to the pre-existing examples README (see https://tac.aswf.io/process/lifecycle.html#incubation-stage).
> Add an ADOPTERS document
